### ISSUE TITLE
Where is ParseFacebookUtils?

### ISSUE THREAD

**Issue by ewintory** [ParsePlatform/Parse-SDK-Android#1]
First, thank you for open sourcing the SDK!

This is a question rather than an issue. Are you planning to open source other parts of the SDK such us ParseFacebookUtils and ParseTwitterUtils? So we could include the whole SDK from the gradle rather than copying distinct jar files.

**Comment by wangmengyan95** [comment]
Hi @ewintory, definitely we are going to that. It will happen soon.

**Comment by ewintory** [comment]
@wangmengyan95 Great, thank you :)

**Comment by kamoljan** [comment]
+1
