### ISSUE TITLE
Push notification maybe blocked in xiaomi phone

### ISSUE THREAD

**Issue by dominicsavb** [ParsePlatform/Parse-SDK-Android#100]
Hi,

do you know about security feature at xiaomi phone.... about autostart setting? it's setting block all parse notification. how to overide this setting?

Thank you

**Comment by wangmengyan95** [comment]
Hi @dominicsavb , could you please provide more details about the feature you mentioned? 
Thanks

**Comment by reachpuneetgulati** [comment]
Even I am facing the issue. Parse Push Notifications don't seem to work on Xiomi's phones. :(
