### ISSUE TITLE
Parse GCM push notifications not working on Android 6.0 Marshmallow Developer Preview 3

### ISSUE THREAD

**Issue by octohub** [ParsePlatform/Parse-SDK-Android#101]
Push notification via Parse are working great on pre-Android 6.0 devices, but for some reason push notifications are not working for me on Android 6.0 Marshmallow Developer Preview 3. I get a `Cannot use GCM for push because the app manifest is missing some required declarations. Please make sure that these permissions are declared as children of the root` even though all the necessary permissions are supplied.

I have outlined the issue in its entirety on [StackOverflow](http://stackoverflow.com/questions/32302450/parse-gcm-push-notifications-not-working-on-android-6-0-marshmallow-developer-pr?noredirect=1#comment52523731_32302450).

**Comment by wangmengyan95** [comment]
Hi @octohub I test our sample app for push and it works fine in the latest api 23 emulator. I check your StackOverFlow thread, it seems you are working on a sample app. So is it possible for you to share your sample project for us to debug for this issue?
Thanks.

**Comment by octohub** [comment]
@wangmengyan95 here is a sample app that is not registering for push on API 23 in the emulator:
https://github.com/octohub/parseSample

**Comment by octohub** [comment]
Fixed!

I simply updated the Parse lib, I was using 1.9.4. Now I am using 1.10.1.

**Comment by wangmengyan95** [comment]
@octohub Great! I test in your same project and it also works.

**Comment by daviddayag** [comment]
Yes, you can upgrade to this version of parse, but this version is CRAP!!!! 
lots of defects with the ACL.
I use 1.8.0 and no push are received with Marshmallow.
Parse is the worst piece of crap I've ever seen!

**Comment by Lx980** [comment]
Did anyone manage to make the notifications work?

**Comment by daviddayag** [comment]
I honestly don't know. 

Regards
David Dayag

On 16 May 2016, at 1:34 PM, Lx980 <notifications@github.com> wrote:

Did anyone manage to make the notifications work?
