### ISSUE TITLE
Parse Installation object receiving a lot of update requests (Android)

### ISSUE THREAD

**Issue by dpapazian** [ParsePlatform/Parse-SDK-Android#102]
Parse generate a lot of update request for no reason, and it's very very expensive!!

1. copy the Android push notification tutorial to subscribe to broadcast channel from the Application class and fill the manifest.xml exactly like on the tutorial
2. Launch the game on several devices, the bug appears only in production
3. Actually I don't think you can reproduce it, you have to investigate our data with us, we can share the code if needed, but it's exactly the same as the tutorial

The bug has already been opened here: https://developers.facebook.com/bugs/1436336080007223/?search_id but it's marked as fixed (and it's not) but I can't reopen it.

SDK version: Parse 1.9.4

**Comment by wangmengyan95** [comment]
Hi @dpapazian , in 1.9.4, we added some checking about if nothing change in the installation when users update the app, we don't update the installation to Parse. So for your case, one possible is when users update the app, google changes the devices' registration id so we have to update the installation. Right now we add some additional logging in our backend to see what is going on,  I will reply to you later.

**Comment by dpapazian** [comment]
No it's not related to the user updating the app. There are too many requests so it can't be the explanation. Thanks for tracking the request, I can't do it myself.

**Comment by dpapazian** [comment]
It's a critical issue.... it's been there for 2 years, could we try to solve this seriously once for all?

**Comment by dpapazian** [comment]
Since October 1st the requests per second reach 700, three time more than the previous day! We did not change anything and we don't have more downloads or updates. Can you at least send me the log to show me what kind of request you receive? You have a very serious bug here...

**Comment by wangmengyan95** [comment]
Hi @dpapazian, I replied to you in the bug tools two weeks ago. We still need some more information from you side. Let's discuss it there. Sorry about the confusion. I will close this issue.

**Comment by dpapazian** [comment]
Thanks, I did not check it because I thought it was not used anymore and everything was on github now. I will answer you there.
