### ISSUE TITLE
authData is undefined  after creating anonymous users

### ISSUE THREAD

**Issue by sabinv** [ParsePlatform/Parse-SDK-Android#104]
I'm using the below code to create anonymous users for my Android Parse app. It works correctly, but sometimes no authData will be saved for the user. I don't have an idea what causes this problem, because it's just a pretty easy user creation, and I think the implementation is correct, because it works sometimes. Do anybody have an idea what did I wrong? Or is it a bug? I would really appreciate if somebody could help me to solve this issue, I'm afraid to release our app before I don't know why this happens. 

![parse data](https://cloud.githubusercontent.com/assets/10012175/9680291/13472b0e-52f6-11e5-8efa-d2eb92abb409.png)

```java
protected void onCreate(Bundle savedInstanceState) {
 super.onCreate(savedInstanceState);
 setContentView(R.layout.activity_login);
 loginButton = (Button)findViewById(R.id.login_button);
 loginButton.setOnClickListener(new View.OnClickListener() {
 @Override
 public void onClick(View view) {
 if(ParseUser.getCurrentUser() == null) { //
 createUser(true);
 } else {
 // user exists
 showMain();
 }
 }
 });
}

 protected void onResume() {
 super.onResume();
 createUser(false);

 }
 }

 private void createUser(final boolean proceedToMain) {
 ParseAnonymousUtils.logIn(new LogInCallback() {
 @Override
 public void done(ParseUser currentUser, ParseException e) {
 if (e != null) {
 e.printStackTrace();
 Log.w(TAG, "Anonymous login failed!");
 if(proceedToMain) {
 Toast.makeText(LoginActivity.this, R.string.login_failed, Toast.LENGTH_LONG).show();
 }
 } else {
 currentUser.put("list", Arrays.asList("plchldr"));

 currentUser.put("type", "tp");
 currentUser.saveInBackground();
 if(proceedToMain)
 showMain();
 }
 }
 });

 }
```

**Comment by sabinv** [comment]
It seems an SDK update solved the problem.

**Comment by grantland** [comment]
Great to hear! I'll be closing this issue since you've resolved the problem.
