### ISSUE TITLE
Implement ParseObject.revert() and revert(key)

### ISSUE THREAD

**Issue by grantland** [ParsePlatform/Parse-SDK-Android#111]
Allow developers to revert all dirty changes on a `ParseObject` or just the dirty changes to a specific key. We already have these methods internally, we'll just need to clean them up and publicize them.

**Note: These methods will only revert changes since the last call to `save`.**

**Comment by artemidius** [comment]
Hello
I totally agree. Once I had a [practical problem](https://github.com/ParsePlatform/Parse-SDK-Android/issues/127) on that issue. 
Please accept the change proposed!
