### ISSUE TITLE
java.lang.IllegalStateException on Query when Local Datastore enabled (SDK 1.10.0)

### ISSUE THREAD

**Issue by stefanraffeiner** [ParsePlatform/Parse-SDK-Android#12]
We have one table with four fields of the type pointer. They point to four different tables (including _User).
When Local Datastore is enabled running find on this Query results in:
```
com.parse.ParseException: java.lang.IllegalStateException: ParseObject has no data for this key.  Call fetchIfNeeded() to get the data.
```

If we remove all pointers (set field to null) except the one to _User it works. We tried different scenarios with/without ACLs and CLPs on the table and on related tables. It's always the same. When we disable local datastore every tested scenario works.
iOS does not seem to have this problem.
We just need the pointer itself on the Android side (no includes), related objects are only used by Cloud Code.

The code where the error happens.
```
Parse.enableLocalDatastore(this);
Parse.initialize(this, PARSE_APPLICATION_ID, PARSE_CLIENT_KEY);
```
```
ParseQuery<MyClass> query = MyClass.getQuery();
query.findInBackground(new FindCallback<MyClass>(){
           @Override
           public void done(List<MyClass> list, ParseException e)
           {
              /* here we get the error */
           }
       });
```
When we remove the line Parse.enableLocalDataStore() everything works.

**Comment by stanleyw** [comment]
What version of SDK are you using?  Could you try to write a simplified unit test case that can cause a repro?  Please see our bug repro guidelines at https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md#bugs
