### ISSUE TITLE
Push notification with parse object

### ISSUE THREAD

**Issue by jyoungrok** [ParsePlatform/Parse-SDK-Android#123]
I think that Push notification with parse object is so important feature.
However, It isn't implemented yet.... It means that android user can't convert JSON object which is sent through notification to Parse obejct....it's so terrible...

Is there any proposal or plan to implement?

I guess there would be person saying workaround like fetching after getting notification.
However, I think it's so bad way....
At first, It's inefficient( as you know, it require additional request....)
Second, It's not reliable (request could be failed...)

**Comment by grantland** [comment]
Merging into #84

**Comment by jyoungrok** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

jyr3357@naver.com 님께 보내신 메일 <Re: [Parse-SDK-Android] Push notification with parse object (#123)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
