### ISSUE TITLE
Stetho integration to improve debugging Android SDK REST network requests

### ISSUE THREAD

**Issue by stanleyw** [ParsePlatform/Parse-SDK-Android#13]
Provide a Parse Android SDK integration with Stetho (http://facebook.github.io/stetho/) so developers can use the Chrome debugger to view REST API requests that Parse SDK is making to the backend.  This requires implementing a network interceptor interface in Parse SDK.  This will also make it easier for developers to differentiate between SDK client-side bugs and backend issues.

**Comment by wangmengyan95** [comment]
Check [ParseInterceptors-Android](https://github.com/ParsePlatform/ParseInterceptors-Android).
