### ISSUE TITLE
ParseImageView not importing

### ISSUE THREAD

**Issue by muhammadyousufsaif** [ParsePlatform/Parse-SDK-Android#131]
Hi,

I am working on an Android app and I need to use ParseImageView. I downloaded latest Parse libraries, version 1.10.1. I read about ParseImageView that it is now part of ParseUI. Can any body tell me how I can still use this in my Android project.

P.S. I am not using Android Studio.

Thanks in advance for your help.

**Comment by grantland** [comment]
You can find `ParseImageView` in [`ParseUI-Android`](https://github.com/ParsePlatform/ParseUI-Android), as well as instructions on how to use it.
