### ISSUE TITLE
Duplicate notification message sent

### ISSUE THREAD

**Issue by bigheadhiro** [ParsePlatform/Parse-SDK-Android#135]
Hello 
We use Parse targeting STB, it runs with Android OS
When trying to push notification receive duplicate messages, varying from 2~13 messages.
It happens randomly and cant find the reproduction factor.
Is there any work around for this issue?
Ubitus

**Comment by wangmengyan95** [comment]
Hi @bigheadhiro ，since there is no way to reproduce this from client, for me, it sounds like a backend issue. We continue to use the FB bug tool to track backend issues, where you can confidentially submit information about the exact app that you are having issues on. Could you file an issue there? https://www.parse.com/help? Thanks.

**Comment by ttagawa1011** [comment]
Let me ask a question on behalf of @bigheadhiro.

One month after the problem occurred, we cannot reproduce it. 
Do you detect bug and fix it, or nothing happened?
Could you please inform me of current status?

Ubitus tagawa

**Comment by ttagawa1011** [comment]
How about the progress?
Could you inform me the situation?

Ubitus Tagawa

**Comment by ttagawa1011** [comment]
How about this issue?

By the way I encountered sending duplicated messages yesterday.
This time, 10 duplicated messages sent.
Today I retried sending notification and it didn't happen.

Ubitus Tagawa

**Comment by ttagawa1011** [comment]
Further information.

1. I did sending notification for the first time in 20 days.
2. I select custom audience, platform Android and "channels" + "contains any of" + some.

**Comment by wangmengyan95** [comment]
Hi @ttagawa1011, have you submitted a bug report to https://www.parse.com/help? You can attach you appId, pushId, so our backend engineers can help you figure out what is happening to the push. Since there is no reliable way to repo it in the client side, there's nothing more we can do here.

**Comment by ttagawa1011** [comment]
Thank you.
You mean the URL below?
https://groups.google.com/forum/#!forum/parse-developers

Takahiro Tagawa

**Comment by grantland** [comment]
https://www.parse.com/help > Report a bug > REST API or other > Select your app > Continue to Facebook

**Comment by parseserverpush** [comment]
I also have the same problem . If user install and uninstall .
