### ISSUE TITLE
Pointer to user in cloudcode empties currentUser 

### ISSUE THREAD

**Issue by paatz04** [ParsePlatform/Parse-SDK-Android#138]
Hello,

we have cloud code functions that return ParseObjects containing a pointer to user. (ParseUser is subclassed to "User"). When the pointer is pointed to the currentUser all fields of the currentUser will be nulled except for the sessionToken. 
I tested it on the android sdk version 1.10.1 and it does not happen in iOS.
Before I had a similar problem, just reversed. Everything was here except for the sessionToken.

They told us at the meetUp in San Francisco that this issue was resolved.

I just saw that there is a new version 1.10.2. Going to test it right away.
Thanks 
Cheers

**Comment by wangmengyan95** [comment]
Hi @paatz04 , great, let us know whether the issue still exist once you finish testing, thanks.
