### ISSUE TITLE
ParseQuery.findInBackground() never calls FindCallback.done()

### ISSUE THREAD

**Issue by rafael-munoz** [ParsePlatform/Parse-SDK-Android#14]
After calling ParseQuery.findInBackground a couple of times the callback is not called anymore.

Looking at the code it seems that the continuation on ParseTaskUtils.callbackOnMainThreadAsync is never called.

Sample project that reproduces the problem: https://www.dropbox.com/s/gfc3bququt9pn3k/Parse-Starter-Project-1-3.zip?dl=0

Steps to reproduce the bug:
1.- In the first Activity tap on the text. 
2.- Search for a user.
3.- Tap on the user result.
4.- Go back to search.
5.- Search for a user.
6.- Notice there are no more results because done() in SPUser.usersForSearchTerm is never invoked.
7.- Also notice there is a deadlock when the user taps on any image in the profile. It is usually when calling ParseObject.getObjectId() or ParseObject.getString(). Maybe it is related.

**Comment by Kiloreux** [comment]
This issue is already reported here https://github.com/ParsePlatform/Parse-SDK-Android/issues/8

**Comment by wangmengyan95** [comment]
@rafael-munoz , the link you provided is not available, could you please check it again?

**Comment by stanleyw** [comment]
Merging into #8

**Comment by VictorOjeda** [comment]
Sorry for the duplicates. Since this issue has the best description lets discuss it here, unless there was another reason to close the bug. Also, here is the link for the project (ignore the first link):

https://www.dropbox.com/s/gfc3bququt9pn3k/Parse-Starter-Project-1-3.zip?dl=0
