### ISSUE TITLE
Delay when receiving push after toggling WiFi on/off

### ISSUE THREAD

**Issue by assizic** [ParsePlatform/Parse-SDK-Android#140]
Hi,

Push notifications are working great as long as I stay on WiFi or LTE. Once I toggle the WiFi and switch between WiFi/LTE, push messages are delayed for a minute or so.
The Parse Push dashboard shows the delayed messages as immediately delivered (successfully), but my onPushReceive that overrides ParsePushBroadcastReceiver.onPushReceive is called a lot later.

Any help will be much appreciated.

Cheers,
Assaf

**Comment by grantland** [comment]
This is most likely an issue with the Android OS or Google Play Services.

1. Could you enable logging via `Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE)` and ensure that you're using GCM by checking logcat for `Using GCM for Push`
2. Check to see if there's still a delay with your own `BroadcastReceiver` implementation for `com.google.android.c2dm.intent.RECEIVE`.

If you're using GCM and there's still a delay the problem isn't a Parse SDK problem, but a Android OS or Google Play Services issue.

**Comment by wangmengyan95** [comment]
Hi @assizic, if you are using GCM for push, the successfully delivered in our dashboard means we successfully send the push to google GCM services. Then google GCM push service will send the push to your device. So the delay you observe is probably a OS or Google Play Services issue.

**Comment by assizic** [comment]
@grantland and @wangmengyan95 - Thanks for the info. I have verified that I am using GCM.
I see this issue on a specific device we have in our lab, and would try to send high-priority GCM messages to see if it reduces the delay. How can I configure the message.priority field to "high" (instead of the default "normal")?

**Comment by grantland** [comment]
Unfortunately we do not support setting the priority for pushes at this moment.

**Comment by assizic** [comment]
This is pretty bad...
a. Can't build "chat-like" applications over parse.
b. Android M introduces doze mode, which makes use of high priority GCM to wake the device and grant network access to the app. 
Is this planned for the near future?

**Comment by grantland** [comment]
We're planning on adding support in the near future, but no ETA at the moment.

**Comment by assizic** [comment]
Thanks...

**Comment by INRIX-Owais-Ali** [comment]
@grantland is there any update on the high priority support?

**Comment by grantland** [comment]
not at the moment

**Comment by mmarshak** [comment]
Check this thread for some possible solutions - http://stackoverflow.com/questions/19560448/how-to-avoid-delay-in-android-gcm-messages-change-heartbeat
