### ISSUE TITLE
Getting undefined devicetoken in parse installation while developing my application

### ISSUE THREAD

**Issue by rajujin1** [ParsePlatform/Parse-SDK-Android#145]
Hi All,
I want to use the parse push notification in my app and while developing that functionality i need to install/uninstall the app . But many times i am unable to send the push because of undefined devicetoken.

I tried to recreate the issue with basic parsestarter project. Initially the project was working fine. But suddenly i started getting the deviceToken as null and as a result the app was crashing..
Need your help in resolving this. 
Need some one to help as i already spent 2-3 days and still clueless as the issue is appearing and disappearing with basic parsestarter project ..

Thanks In advance..
Rajender

***************************************Pase related msg in logcat:*********************************************\
09-20 19:44:16.782    1137-1158/? W/BroadcastQueue﹕ Receiver during timeout: ResolveInfo{2aacf016 com.parse.starter/com.parse.GcmBroadcastReceiver m=0x108000}
09-20 19:44:16.846    1137-1158/? I/ActivityManager﹕ Crashing app skipping ANR: ProcessRecord{23cd1d97 14135:com.parse.starter/u0a166} Broadcast of Intent { act=com.google.android.c2dm.intent.REGISTRATION flg=0x10 pkg=com.parse.starter cmp=com.parse.starter/com.parse.GcmBroadcastReceiver (has extras) }
09-20 19:44:18.230    1137-1311/? I/ActivityManager﹕ Force stopping com.parse.starter appid=10166 user=0: from pid 14409
09-20 19:44:18.231    1137-1311/? I/ActivityManager﹕ Killing 14135:com.parse.starter/u0a166 (adj 15): stop com.parse.starter
09-20 19:44:18.288    1137-2149/? W/ActivityManager﹕ Spurious death for ProcessRecord{23cd1d97 14135:com.parse.starter/u0a166}, curProc for 14135: null
09-20 19:44:18.952    1137-2151/? I/ActivityManager﹕ START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.parse.starter/.MainActivity} from uid 2000 on display 0
09-20 19:44:18.953    1137-2151/? V/WindowManager﹕ addAppToken: AppWindowToken{1fb98d52 token=Token{31a8addd ActivityRecord{6531db4 u0 com.parse.starter/.MainActivity t914}}} to stack=1 task=914 at 0
09-20 19:44:18.964    1137-1163/? V/WindowManager﹕ Adding window Window{2e18bb95 u0 Starting com.parse.starter} at 2 of 8 (after Window{2880d23b u0 com.android.launcher/com.android.launcher2.Launcher})
09-20 19:44:19.022    1137-2150/? I/ActivityManager﹕ Start proc 14451:com.parse.starter/u0a166 for activity com.parse.starter/.MainActivity
09-20 19:44:19.402  14451-14451/? D/raju_com.parse.push﹕ starting subscribed to the broadcast channel.
09-20 19:44:19.420  14451-14451/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.parse.starter, PID: 14451
    java.lang.RuntimeException: Unable to create application com.parse.starter.StarterApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4641)
            at android.app.ActivityThread.access$1500(ActivityThread.java:155)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5343)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
            at com.parse.starter.StarterApplication.onCreate(StarterApplication.java:56)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4638)
            at android.app.ActivityThread.access$1500(ActivityThread.java:155)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5343)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
09-20 19:44:19.424    1137-1150/? W/ActivityManager﹕ Force finishing activity 1 com.parse.starter/.MainActivity
09-20 19:44:19.518      271-271/? D/SFPerfTracer﹕ layers: (5:11) (FocusedStackFrame (0xb74b86f8): 1:175)* (DimLayer (0xb74b99a0): 0:256)* (DimLayer (0xb74bb320): 0:18)* (DimLayer (0xb74be770): 0:203)* (DimLayer (0xb751bf90): 0:49)* (StatusBar (0xb74e1898): 1:1946) (com.android.systemui.ImageWallpaper (0xb7540d88): 0:136) (NavigationBar (0xb74dd760): 0:232) (Application Error: com.parse.starter (0xb74f2228): 0:51)- (com.android.launcher/com.android.launcher2.Launcher (0xb751f5a0): 1:14) (Starting com.parse.starter (0xb753fae0): 5:8)
09-20 19:44:19.952    1137-1158/? W/ActivityManager﹕ Activity pause timeout for ActivityRecord{6531db4 u0 com.parse.starter/.MainActivity t914 f}
09-20 19:44:20.969    1281-1281/? W/PackageManager﹕ Failure retrieving resources for com.parse.starter: Resource ID #0x0

*****************************************StarterApplication.java***************************************************************
/*
 * Copyright (c) 2015-present, Parse, LLC.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */
package com.parse.starter;

import android.app.Application;
import android.provider.Settings;
import android.util.Log;

import com.parse.Parse;
import com.parse.ParseACL;
import com.parse.ParseException;
import com.parse.ParseInstallation;
import com.parse.ParsePush;
import com.parse.ParseUser;
import com.parse.SaveCallback;

public class StarterApplication extends Application {

  @Override
  public void onCreate() {
    super.onCreate();

    // Enable Local Datastore.
    Parse.enableLocalDatastore(this);

    // Add your initialization code here
    Parse.initialize(this, "***************************",
                                   "****************************");
    String  android_id = Settings.Secure.getString(getApplicationContext().getContentResolver(), Settings.Secure.ANDROID_ID);
    ParseInstallation.getCurrentInstallation().put("Unique_Id",android_id);
    ParseInstallation.getCurrentInstallation().saveInBackground();

//    try {
//      ParseInstallation.getCurrentInstallation().put("Unique_Id",android_id);
//      ParseInstallation.getCurrentInstallation().save();
//    } catch (ParseException e) {
//      e.printStackTrace();
//    }
    Log.d("raju_com.parse.push", "starting subscribed to the broadcast channel.");
    ParsePush.subscribeInBackground("", new SaveCallback() {
      @Override
      public void done(ParseException e) {
        if (e == null) {
          Log.d("raju_com.parse.push", "successfully subscribed to the broadcast channel.");
        } else {
          Log.e("raju_com.parse.push", "failed to subscribe for push", e);
        }
      }
    });
    Log.e("Raju_", "here i ak in--and_id--" + android_id + "---" + ParseInstallation.getCurrentInstallation().get("deviceToken").toString());
    
    ParseUser.enableAutomaticUser();
    ParseACL defaultACL = new ParseACL();
    // Optionally enable public read access.
    // defaultACL.setPublicReadAccess(true);
    ParseACL.setDefaultACL(defaultACL, true);
  }
}

*********************************************************Android_manifest.xml************************************
<?xml version="1.0" encoding="utf-8"?>

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.parse.starter" >

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

    
    <permission android:protectionLevel="signature"
        android:name="com.parse.starter.permission.C2D_MESSAGE" />
    <uses-permission android:name="com.parse.starter.permission.C2D_MESSAGE" />
    <application
        android:name=".StarterApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <meta-data
            android:name="com.parse.APPLICATION_ID"
            android:value="@string/parse_app_id" />
        <meta-data
            android:name="com.parse.CLIENT_KEY"
            android:value="@string/parse_client_key" />

        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <service android:name="com.parse.PushService" />
        <receiver android:name="com.parse.ParsePushBroadcastReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.parse.GcmBroadcastReceiver"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />

                
                <category android:name="com.parse.starter" />
            </intent-filter>
        </receiver>
    </application>

</manifest>

************************************MainActivity.java**********************************************************
/*
 * Copyright (c) 2015-present, Parse, LLC.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */
package com.parse.starter;

import android.os.Bundle;
import android.support.v7.app.ActionBarActivity;
import android.view.Menu;
import android.view.MenuItem;

import com.parse.ParseAnalytics;

public class MainActivity extends ActionBarActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    ParseAnalytics.trackAppOpenedInBackground(getIntent());
  }

  @Override
  public boolean onCreateOptionsMenu(Menu menu) {
    // Inflate the menu; this adds items to the action bar if it is present.
    getMenuInflater().inflate(R.menu.menu_main, menu);
    return true;
  }

  @Override
  public boolean onOptionsItemSelected(MenuItem item) {
    // Handle action bar item clicks here. The action bar will
    // automatically handle clicks on the Home/Up button, so long
    // as you specify a parent activity in AndroidManifest.xml.
    int id = item.getItemId();

    //noinspection SimplifiableIfStatement
    if (id == R.id.action_settings) {
      return true;
    }

    return super.onOptionsItemSelected(item);
  }
}

**Comment by rajujin1** [comment]
Figured the problem which helped me for 15 min only:-
I was displaying the deviceToken immediately after calling parseinstallation.saveinbackgound..
fixed the issue for 15 min because after 15 min again i am getting the same issue.. Below is my update application code:--
/*
 * Copyright (c) 2015-present, Parse, LLC.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */
package com.parse.starter;

import android.app.Application;
import android.provider.Settings;
import android.util.Log;

import com.parse.Parse;
import com.parse.ParseACL;
import com.parse.ParseException;
import com.parse.ParseInstallation;
import com.parse.ParsePush;
import com.parse.ParseUser;
import com.parse.SaveCallback;


public class StarterApplication extends Application {

  @Override
  public void onCreate() {
    super.onCreate();

    // Enable Local Datastore.
    Parse.enableLocalDatastore(this);

    // Add your initialization code here
    Parse.initialize(this, "4mj0RupNfYVgCWU2TFIu7xbLNsqp0GrvVzrNucNZ", "dCSjDWpurjZJ2VegtkKyFC3sJ7Am4FPiS3aHCstE");
    String  android_id = Settings.Secure.getString(getApplicationContext().getContentResolver(), Settings.Secure.ANDROID_ID);
    ParseInstallation.getCurrentInstallation().put("Unique_Id",android_id);
//    ParseInstallation.getCurrentInstallation().saveInBackground();

    try {
      ParseInstallation.getCurrentInstallation().put("Unique_Id",android_id);
      ParseInstallation.getCurrentInstallation().save();
    } catch (ParseException e) {
      e.printStackTrace();
    }
    Log.e("raju_--com.parse.push", "123 starting subscribed to the broadcast channel.--"+android_id);
    ParsePush.subscribeInBackground("", new SaveCallback() {
      @Override
      public void done(ParseException e) {
        if (e == null) {
          Log.d("raju_com.parse.push", "successfully subscribed to the broadcast channel.");
        } else {
          Log.e("raju_com.parse.push", "failed to subscribe for push", e);
        }
      }
    });
    Log.e("Raju_", "here i ak in--and_id--" + android_id + "---" + ParseInstallation.getCurrentInstallation().get("deviceToken").toString());

    ParseUser.enableAutomaticUser();
    ParseACL defaultACL = new ParseACL();
    // Optionally enable public read access.
    // defaultACL.setPublicReadAccess(true);
    ParseACL.setDefaultACL(defaultACL, true);
  }
}

**Comment by wangmengyan95** [comment]
Hi @rajujin1, we need to talk to Google GCM to get the `deviceToken ` of an installation, since we can not control the process, so there is no guarantee when `deviceToken` is available in a installation. In this situation it is not safe to call `ParseInstallation.getCurrentInstallation().get("deviceToken").toString()` without a null check.

**Comment by rajujin1** [comment]
Hi Mengyan,
Thanks a lot for the prompt response.
In that case how to rely on the push notification service because sometime
the deviceToken and PushType both are undefined..
So question is how to handle that kind of problem where deviceToken and
PushType both are undefined in the Installation object in the parse
database.

-Rajender Jindal

**Comment by wangmengyan95** [comment]
Hi @rajujin1 , if you device allow GCM pushing and the the permissions in your Manifest are set correctly, when we save the installation to Parse, at lease the PushType should be set to gcm. It is wried both PushType and deviceToken are undefined. Can you check your permissions in your Manifest? If you are sure everything is correct, can you still repo this issue?

**Comment by rajujin1** [comment]
Hi Mengyan,
Thanks for the reply..
Presently i am not seeing this issue. Thanks for your support..

-Thanks and Regards,
Rajender Jinda

**Comment by wangmengyan95** [comment]
Hi @rajujin1, cool, I will close this issue. Feel free to reopen it if it appears again.

**Comment by rajujin1** [comment]
Hi there,
I am getting undefined devicetoken after doing the following:
ParseInstallation.getCurrentInstallation().saveInBackground(new SaveCallback() {
            @Override
            public void done(ParseException e) {
                String deviceToken = (String) ParseInstallation.getCurrentInstallation().get("deviceToken");
                Log.e("Q4U", "tbr i got device token as " + deviceToken);
                if (e == null)
                    Log.e("Q4U", "tbr i am null ");
                else
                    Log.e("Q4U", "tbr i am not null" + e.getMessage());
            }
        });
