### ISSUE TITLE
parse invalid login parameters 

### ISSUE THREAD

**Issue by NomanJaved** [ParsePlatform/Parse-SDK-Android#146]
public static final String YOUR_APPLICATION_ID = "Key";
    public static final String YOUR_CLIENT_KEY = "Key";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);

        Parse.enableLocalDatastore(this);
        Parse.initialize(this, YOUR_APPLICATION_ID, YOUR_CLIENT_KEY);

        Button button = (Button) findViewById(R.id.loginButton);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                EditText text_name = (EditText) findViewById(R.id.loginpage_username);
                String login_username = text_name.getText().toString();

                EditText text_password = (EditText) findViewById(R.id.loginpage_password);
                String login_password = text_name.getText().toString();

                //this is the method that cause the error
                ParseUser.logInInBackground(login_username, login_password, new LogInCallback() {
                    @Override
                    public void done(ParseUser parseUser, com.parse.ParseException e) {
                        if (parseUser != null) {
                            // Hooray! The user is logged in.
                            Log.d(login_username, login_username+"success");
                            Intent intent = new Intent(login.this, socialApp.class);
                            startActivity(intent);
                            // Log.d(login_username, "hello username");
                            // Log.d(login_password, "hello password");
                        } else {
                            // Signup failed. Look at the ParseException to see what happened.
                            Log.d(login_username, login_username+"error", e);
                            Log.d(login_password, login_password+"error", e);
                        }
                    }// end of done method
                });// end of parseuser.loginbackground(login_username)

            }
        });// end of setonclicklistener

![image](https://cloud.githubusercontent.com/assets/8793822/9982839/bf4b1500-6002-11e5-9fe8-a74d9701674b.png)

also see the image and you will get the errors I do almost every thing right ....! 
I enter the right user name and right password but every time it say that 
invalid parameter....! what is the reason.

Also see the same question on StackOverFlow
http://stackoverflow.com/questions/29582229/parse-com-invalid-login-parameters

**Comment by grantland** [comment]
It looks like you're passing username for both username and password:

```
EditText text_name = (EditText) findViewById(R.id.loginpage_username);
String login_username = text_name.getText().toString();

EditText text_password = (EditText) findViewById(R.id.loginpage_password);
String login_password = text_name.getText().toString(); // Should be `text_password`
```

**Comment by dac2205** [comment]
I got the same error. It's fun that the problem is not from the source code.
In Parse, "invalid login parameters" means "Wrong username or password".
Just type the correct usename/password and it works!

**Comment by NomanJaved** [comment]
thanks grantland Solved my problem....!

**Comment by grantland** [comment]
Awesome, glad to hear!

**Comment by eddieberklee** [comment]
@dac2205 :eyes: oh wow - that saved me what would have been more minutes of debugging
