### ISSUE TITLE
"Bad protocol" Exception happening frequently

### ISSUE THREAD

**Issue by vrandon** [ParsePlatform/Parse-SDK-Android#147]
Hi all,
When executing simple queries (happening on almost all the queries in the App), out of 20 queries one usually ends up in a "Bad protocol" ParseException. We have about 10 apps based on Parse API and we're experiencing this bug only with this app (com.clapp.ontime). 
Whenever the query seems to take a long time to process, the bad protocol Exception appears, whether we're connected via Wi-Fi, 3G or 4G.
The app is also linked to a web page, which usually works okay, except for today: the queries also took a very long time to process, forcing our users to close the browser tab and reopen it. (I've checked that the Parse status today is "all system operational").
We're in the middle of a user-acquisition process (the app is a B2B system) and therefore need this issue to be solved ASAP.

Please let me know if you need any piece of code (although the queries experiencing this bug are all different, and we never had this kind of bug with any Parse based app before).
Thank you very much for your help.

**Comment by wangmengyan95** [comment]
Hi @vrandon, for me, bad protocol seems like a network issue, so you can do two things to help us debug 
1. Please paste the full stacktrace of the bug.
2. If the exception is related to network, we introduce [ParseInterceptos](https://github.com/ParsePlatform/ParseInterceptors-Android) to help us debug the network issue. Could you please try to use the `ParseLogInterceptor` or `ParseStethoInterceptor` in your app and paste the network information when the bug happens, thx.

**Comment by MarsVard** [comment]
On samsung devices this causes the devices to show an error claiming the app is slowing down and needs to be uninstalled.

**Comment by vrandon** [comment]
Hi @wangmengyan95 , I'm so sorry, I have been away these last 2weeks for family reasons and I haven't had time to look into what you told me at all. I'll let you know as soon as I can try ParseInterceptos (that I didn't know existed!). Thanks a lot for your help.

**Comment by wangmengyan95** [comment]
@vrandon, no worry. I will keep this issue open.

**Comment by wangmengyan95** [comment]
Feel free to re-open it.
