### ISSUE TITLE
Issue with FutureCallback

### ISSUE THREAD

**Issue by alxpereira** [ParsePlatform/Parse-SDK-Android#149]
Hi everyone,
I'm trying to install Parse in my app. Before everything was running (i'm using ION & FutureCallbacks to manage my REST calls). https://github.com/koush/ion

Since i'm adding the 2 installation lines in the build.gradle, the FutureCallbacks are throwing a NoClassDefFoundError (it was running well before adding the lines, if I remove them, it works back).

Any idea why we encounter this collision ?

I'm currently stuck on delivering this to my client.
Thanks !
Alex

**Comment by grantland** [comment]
There shouldn't be any collisions since we use a completely different package.

**Comment by alxpereira** [comment]
I can try in a new app to see but i think there's something wrong.

**Comment by alxpereira** [comment]
Hi @grantland,
Made this morning a test in a new app with nothing except the 2 librairies (ION + Parse), I encounter the same issue. The "FutureCallback" isn't working and crash the app since i'm adding the parse libs in the build.gradle.

You can download the test app here : http://we.tl/nDRhsrnTFV

Thanks
Alex

**Comment by grantland** [comment]
Your test project runs fine on my machine (although I had to add `android.permission.INTERNET`). Seems like it's a problem with your dev env.
