### ISSUE TITLE
.setEmail() for ParseUser isn't working: Invalid Email Address

### ISSUE THREAD

**Issue by timigod** [ParsePlatform/Parse-SDK-Android#152]
I'm using the Parse.com Android SDK (v1.10.2) and I'm trying to set the email address of the logged in ParseUser.

Any time I try my code (below), I keep getting "invalid email address"

```
   ParseUser parseUser = ParseUser.getCurrentUser();
    parseUser.setEmail(email);
    parseUser.saveInBackground(new SaveCallback() {
      public void done(ParseException e) {
        if (e == null) {
          // No exception
        } else {
          Log.d(Constants.REGISTRATION_STAGES[1], e.toString());
        }
      }
    });
```
I've copied and pasted the "invalid" email address (from the output in Logcat; "timi@helloworld.ng") into the Parse data browser and it works fine.

I don't know if this is important but I'm creating users as is done in the Anyphone (Parse + Twilio) example.

These are the questions I have:

1. What exactly does Parse look out for before setting email? i.e What are the properties/characteristics of a valid email address as is defined by Parse?

2. What possible reasons are there for .setEmail() not to work with this email address (and all the others I've tried), while pasting it into the data browser works?

**Comment by grantland** [comment]
I just tested this using `timi@helloworld.ng` and it worked successfully. Are you sure you're not accidentally inserting non-printable characters into `ParseUser#setEmail(email)`?

Could you try printing the raw string using and length using the following code?

```java
Log.d(TAG, "bytes: <" + email.getBytes(Charset.forName("UTF-8")) + ">");
Log.d(TAG, "length: <" + email.length() + ">");
```

And also try entering the email through code:

```java
user.setEmail("timi@helloworld.ng");
user.saveInBackground(...);
```

**Comment by timigod** [comment]
```
D/GETTING_EMAIL﹕ "mrbigheaddd@gmail.com"
D/GETTING_EMAIL﹕ bytes: <[B@45432410>
D/GETTING_EMAIL﹕ length: <23>
D/GETTING_EMAIL﹕ invalid email apache
```

You're right, apparently the response (from wit.ai) still has the quotation marks in the string. 
The last item from that log is due to me using apache commons validator.
Really sorry for bothering you with such a rookie mistake.

I had tried `user.setEmail("actually-typed-out-address") before and it worked.

**Comment by grantland** [comment]
All good, glad to hear everything is working now!
