### ISSUE TITLE
Can't parse dates from cloud code using JS SDK 1.6.+

### ISSUE THREAD

**Issue by d370urn3ur** [ParsePlatform/Parse-SDK-Android#157]
In reference to #130. Every time I call cloud code built with JS SDK 1.6.+ I get an error: "java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference".  The issue was closed but this is still not working for me. I am on JS SDK 1.6.2 and Android SDK 1.10.2.  Response format hasn't changed from #130's original post: "createdAt":{"__type":"Date","iso":"2015-09-24T09:39:21.972Z"}, seems like Android SDK is expecting "createdAt":"2015-09-24T09:39:21.972Z".  So it fails to parse the format and results in the Date object being null, then calling getTime() throws the error.

**Comment by andrewimm** [comment]
@d370urn3ur can you verify that you are using the JS SDK 1.6.2? The relevant changes were checked into 1.6.1, but we have an issue where specifying "latest" in cloud code reverts back to 1.6.0. We plan to have this solved in cloud code by tomorrow, but until then can you make sure you're hard-coding your JS version into `config/global.json`?

**Comment by d370urn3ur** [comment]
It's weird, I thought I had explicitly set it as 1.6.2 but apparently I was using "latest".  Didn't know about the "latest" bug, I can confirm that 1.6.2 is sending updatedAt in the correct format. Thanks for the quick response!
