### ISSUE TITLE
saveInBackground callback  not working 

### ISSUE THREAD

**Issue by mik-dass** [ParsePlatform/Parse-SDK-Android#158]
My app uses the saveInBackground callback method and it seems to have suddenly stopped working with no exception.The method is called but no callback is received from the server side.It was working fine till today.All my activities with saveInBackground callback  method cannot save data to the server anymore.The done method inside the method is never called.Everything else is working fine even the queries are working properly.Only the saveInBackground callback method is not functioning.Please help.Thank you.

**Comment by wangmengyan95** [comment]
Hi @mik-dass, since the code still worked yesterday, for me, it sounds like a backend or network issue.
For network issue, we introduce [ParseInterceptos](https://github.com/ParsePlatform/ParseInterceptors-Android) to help us debug. Could you please try to use the `ParseLogInterceptor` or `ParseStethoInterceptor` in your app and paste the network information?
If you see there is no data sends from our server, it is a backend issue. For backend issue, we continue to use the FB bug tool to track them, where you can confidentially submit information about the exact app that you are having issues on. Could you file an issue there? https://www.parse.com/help? Thanks.

**Comment by mik-dass** [comment]
Hi .I debugged my code and here is what I discovered .One of my activities is a like activity where a user can like a post object and that increments the points on that particular post owner .The code works fine the first time the activity is launched and also the like functionality works perfectly the first time and the dislike function works too.But if he tries to like the post again ,the same like function is called again(worked properly the first time and the disliked function too ) but this time it results in a error ->>>User::UserCannotBeAlteredWithoutSessionError.Here is my code-


 mheart.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mheart.setClickable(false);
                if (liked) {
                    ParseObject.createWithoutData("likes", likeId).deleteInBackground(new DeleteCallback() {
                        @Override
                        public void done(ParseException e) {
                            if (e == null) {
                                ParseObject parseObject = ParseObject.createWithoutData(ParseUser.class,post.getPosAuthorObjectId());
                                parseObject.increment("points", -1);
                                parseObject.saveInBackground();
                                ParseObject parseObject1 = ParseObject.createWithoutData("posts", post.getObjectId());
                                parseObject1.increment("likes", -1);
                                parseObject1.saveInBackground();
                                long i = post.getLikes();
                                post.setLikes(i - 1);
                                //Toggle the visibilty
                                //liked is false
                            } else {
                                //clickable is true
                            }
                        }
                    });
                }
            }
        });
        mheart_not_liked = (ImageButton) findViewById(R.id.image_viewer_not_liked);
        mheart_not_liked.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mheart_not_liked.setClickable(false);
                if (!liked) {
                    final ParseObject parseObject = new ParseObject("likes");
                    parseObject.put("ownerId", ParseObject.createWithoutData(ParseUser.class, ParseUser.getCurrentUser().getObjectId()));
                    parseObject.put("postId", ParseObject.createWithoutData("posts", post.getObjectId()));
                    parseObject.saveInBackground(new SaveCallback() {
                        @Override
                        public void done(ParseException e) {   //Error occurs here at e
                            if (e == null) {
                                likeId = parseObject.getObjectId();
                                ParseObject obj = ParseObject.createWithoutData(ParseUser.class, post.getPosAuthorObjectId());
                                obj.increment("points", +1);
                                obj.saveInBackground();
                                ParseObject obj1 = ParseObject.createWithoutData("posts", post.getObjectId());
                                obj1.increment("likes", +1);
                                obj1.saveInBackground();
                                long i = post.getLikes();
                                post.setLikes(i + 1);
                               //toggle the visibility of the button
                                //liked is true now
                            } else {
                               //clickable set to true
                            }
                        }
                    });
                }
            }
        });

**Comment by grantland** [comment]
Could you please verify what version of the SDK you're using and verify that this issue is still occurring when using latest?

**Comment by mik-dass** [comment]
My gradle build is like

 compile 'com.parse.bolts:bolts-android:1.+'
 compile fileTree(dir: 'libs', include: 'Parse-*.jar')

I don't know the exact sdk version .Can you tell me how to look for it???.....:)

**Comment by mik-dass** [comment]
Sorry ...My bad ...the exact sdk version is .......Parse-1.9.4

**Comment by mik-dass** [comment]
I upgraded to the latest version of the  sdk and the error ...User::UserCannotBeAlteredWithoutSessionError still persists.Please help as my entire development of my app is stuck here.

**Comment by wangmengyan95** [comment]
Hi @mik-dass, the problem is in this line
`ParseObject obj = ParseObject.createWithoutData(ParseUser.class, post.getPosAuthorObjectId());`
You actually create a ParseUser(which is a subclass of ParseObject) through this line. You can't save a user object unless you're logged in as them, so that is why you get the exception.

**Comment by mik-dass** [comment]
Yeah...You are right.I figured it out some hours ago.So basically now I have to create a cloud code with JavaScript and use master key to write a beforeSave function.Am I right??? Is there any other way to achieve this without writing any cloud code within Android itself??? Thank you very much for your help. Please reply. Thank you .

**Comment by wangmengyan95** [comment]
Hi @mik-dass, since I am not familiar with your app so this suggestion may not fit for your situation. But I think you can create a new ParseObject. In the new ParseObject,  there is a field `point` to store the point and there is another field `user` to point to the ParseUser. By doing this, you can update the ParseObject instead of the ParseUser when you want to increment the point. Hope it helps.

**Comment by mik-dass** [comment]
So you mean something like.

ParseObject obj =new ParseObject("_User");
obj.put("point',value);
obj.put("_User",pointer);
obj.save();


Is this correct??? Or Are you suggesting that I create a new Parse class to store points??? I didn't get the suggestion that you gave me. Can you write a few lines of code to make me understand your approach. Thank you for your help. Please reply.

**Comment by wangmengyan95** [comment]
No, what I mean is a new Parse class to store the points.
```java
ParseObject point = new ParseObject("Point");
point.put("point", 1);
point.put("owner", parseUser);
point.saveInBackground();
```

**Comment by mik-dass** [comment]
Ok. That is a great way . But I think I will first try the cloud code approach as it will give me flexibility like beforeSave and aftersave .If it doesn't work out for me then I will take this approach. Thank you . I really appreciate your help.

**Comment by mik-dass** [comment]
@wangmengyan95  Please review my cloud code.I am getting Reference error : posts is not defined error .Here posts is the name of my class stored in parse database

Parse.Cloud.beforeSave("likes",function(request,response){
        var id=request.object.get("ownerId").id;
        var user=Parse.Object.extend(Parse.User);
        var user=new Parse.User();
        user.id=id;
        user.increment("points",+1);
        Parse.Cloud.useMasterKey();
        user.save(null, {
                          success: function() {
                              var post_id=request.object.get("postId").id;
                              var post=Parse.Object.extend("posts");
                              var post=new posts();
                              post.id=post_id;
                              post.increment("likes",+1);
                              post.save();
                          },
                          error: function() {
                              response.error("The saved failed");
                          }
        });
});

I looked at the documentation but still I am not getting why the error occurs.Please help.

**Comment by mik-dass** [comment]
@wangmengyan95 @grantland I want some help to write my cloud code .I have three classes _User ,post and like .Post contain a pointer to the user class(postowner) and likes contains the pointer to the post class(likeowner).In my app ,on the click of a button the "like" row is created in the like class before which I want to change some attribute of the user to whom the post belongs.I have a beforeSave method in my cloud code.But how do I retrieve the particular _User class object id to whom the post belongs in this cloud code .I know how to get the id of the user making the request ,but how to get the id of the post owner .I don't want to use another query to find the id of the post owner as this will cost me 1 more api request .And is there any way of sending some string data to the beforeSave method .I just want the id of the _user who is the owner of the post without making a api "query" request.Please Help.
