### ISSUE TITLE
Parse Query WhereNear is giving wrong results

### ISSUE THREAD

**Issue by vayalasp** [ParsePlatform/Parse-SDK-Android#160]
I use query.whereNear with query.setLimit(20) and is retrieving very far results even when the are other possible results that are nearer.
 This is happening since this morning error:

Oct 1, 2015
Elevated Error Rates
Resolved - This incident has been resolved. 
Oct 1, 07:08 PDT
Investigating - We are experiencing elevated error rates for some applications. 
Oct 1, 05:49 PDT

**Comment by wangmengyan95** [comment]
Hi @vayalasp, for me, it sounds like a backend issue. We continue to use the FB bug tool to track backend issues, where you can confidentially submit information about the exact app that you are having issues on. Could you file an issue there? https://www.parse.com/help? Thanks.

**Comment by vayalasp** [comment]
I tried that already, but it sends me to GitHub...I cant report the issue
directly to parse....

2015-10-01 12:08 GMT-05:00 Mengyan Wang <notifications@github.com>:

**Comment by grantland** [comment]
You probably want to select "No specific platform" or "REST API/other"

**Comment by vayalasp** [comment]
Really I did it, then it sends me to facebook page, anthe I start doing
everything they ask and when submit, it says that I have to report it in
GitHub.....really frustrating.....

2015-10-01 14:41 GMT-05:00 Grantland Chew <notifications@github.com>:

**Comment by wangmengyan95** [comment]
Hi @vayalasp, in facebook page, you can choose like this to report your GeoPoints related bugs.
Hope it helps.
![image](https://cloud.githubusercontent.com/assets/4666935/10232983/a524766c-6840-11e5-88ec-26aada89bf1c.png)

**Comment by vayalasp** [comment]
Thank you, you have been so nice to me, My name is Victor by the way, from
Ecuador....thank you againg, I just did that...Hope I recieve
answers.....It's been very nice to recieve your help, hope we can be
friends........Thnk you...

2015-10-01 15:32 GMT-05:00 Mengyan Wang <notifications@github.com>:
