### ISSUE TITLE
PushService.setDefaultPushCallback with new API

### ISSUE THREAD

**Issue by MarkusN99** [ParsePlatform/Parse-SDK-Android#161]
Hello
I currently have the SDK version 1.10.2.

For me the device token is not entered. Read somewhere that is because I do not have "PushService.setDefaultPushCallback(getApplicationContext(), MainActivity.class)" in it.

As the alternative is that I can enter the?

**Comment by wangmengyan95** [comment]
Hi @MarkusN99, I do not quite understand your problem, could you tell me what do you want to do?
1. For `PushService`, it s a service which should be defined in your Manifest, you do not need to call it manually. It is used for receive the push notifications.
2. For device token, we do not use `PushService` to register your device. We try to register your device when you call `Parse.initialize()`.

**Comment by MarkusN99** [comment]
For me the problem is that the deviceToken is not entered. So I can not send push notifications. PushService I have defined in the manifest. The deviceToken is not registered with Parse.initialize ()

**Comment by wangmengyan95** [comment]
Hi @MarkusN99, for your case, could you provide us with the following information:
1. You test environment, emulator or a actual device.
2. Enable logging in our SDK with Parse.setLogLevel(Log.VERBOSE) and paste the logcat.
3. There is no device token for all of your installations or just some of them

Thanks

**Comment by MarkusN99** [comment]
It has resolved itself.

Had the ParsePushBroadcastReceiver not defined in the file AndroidManifest

Thanks anyway :)

**Comment by grantland** [comment]
Glad to hear everything is working for you. I'll be closing this task.
