### ISSUE TITLE
Can't set the notification color in Lollipop

### ISSUE THREAD

**Issue by mars3142** [ParsePlatform/Parse-SDK-Android#162]
It is not possible to set the notification color in Android Lollipop and above.

**Comment by mars3142** [comment]
I'll create a pull request.

**Comment by grantland** [comment]
This can be accomplished by extending `ParsePushBroadcastReceiver` and overriding `#getNotification()`.

**Comment by mars3142** [comment]
But the override for the getNotification is too much boilerplate code. This is not a possible solution for everyone. Why can't you include my pull request, because it's much easier with my solution!?

**Comment by grantland** [comment]
We try to balance adding useful helpers with keeping a clean and simple API. Making it easier for developers to solve complex problems is always great, but only if it solves common problems and the savings outweigh the added complexity of the additional APIs.

There are many ways to customize notifications, but the required minimum are `smallIcon`, `title`, and `text`. We supply `title` and `text` from the push payload and `smallIcon` is defined by overriding `getSmallIcon()` or defining meta-data in `AndroidManifest.xml`.

Outside of the bare minimum, there are various other attributes such as sound, lights, color, action, vibrate, sort key, etc. While it's possible to include various helper methods and meta-data attributes to allow customization, it doesn't make development significantly easier compared to the amount of extra API duplication that already exists in AOSP.

At the point when you're customizing something beyond the required minimum it isn't really boilerplate code, but app specific code.
