### ISSUE TITLE
Negative limit/unlimited for ParseQuery not working

### ISSUE THREAD

**Issue by benhk2005** [ParsePlatform/Parse-SDK-Android#167]
I use the follow code to get data from datastore
```Java
         ArrayList<ParseQuery<ParseObject>> queries = new ArrayList<>();
         for(int i = 0; i < 7; i++){
            ParseQuery<ParseObject> query = ParseQuery.getQuery("Program");
            query.whereEqualTo("year", String.valueOf(calendar.get(Calendar.YEAR)))
                    .whereEqualTo("month", String.valueOf(calendar.get(Calendar.MONTH)+1))
                    .whereEqualTo("day", String.valueOf(calendar.get(Calendar.DATE)+i))
                    .whereEqualTo("station", stationId);
            queries.add(query);
        }
        ParseQuery<ParseObject> totalQuery = ParseQuery.or(queries);
```
However, if i set negative number for limit using
```Java
totalQuery.setLimit(-1)
```
or I don't set any limit
it only return 100 results, but not up to 1000.

**Comment by wangmengyan95** [comment]
Hi @benhk2005, even your set limit to negative number, when we send the request to server, we check and turn the negative to 0. So negative limit should not be the cause of your issue. Have you tried to run those queries separate and then check how many results you get?

**Comment by benhk2005** [comment]
I just tried run the query separately
if I set the limit to -1 , it return 100 records
but if i set the limit to 1000, it returns more than 200 records.
and what i see on the android api, it wrote if i set limit to -1, it will return all rows.
but it seems that it is not the case.

**Comment by wangmengyan95** [comment]
Hi @benhk2005, it is a little bit wried for your case. For now, I think we need to take a look at the request your api send to Parse server to decide wether it is a SDK issue or a backend issue. We introduce [Parse-Interceptor](https://github.com/ParsePlatform/ParseInterceptors-Android) to make the process pretty easy. Could you try to use `ParseLogInterceptor` or `ParseStethoInterceptor` and paste your request's payload here?
