### ISSUE TITLE
Can not save ParseObject on Android 4.4.4 with the V1.10.2

### ISSUE THREAD

**Issue by jsding** [ParsePlatform/Parse-SDK-Android#170]
ParseObject parseObject = new ParseObject("Blog");
		parseObject.add("uid", user.getUid());
		parseObject.add("username", user.getUsername());
		parseObject.add("avatar", user.getAvatar());
		parseObject.add("content", mContent.getText().toString());
		parseObject.saveInBackground();

Simply failed with the following error:

Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7c53bf00: Failure in SSL library, usually a protocol error

error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (external/openssl/ssl/s23_clnt.c:769 0x7369dd74:0x00000000)

Here is a link with the same issue, but do not sure that's the case.

http://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han

Thanks

**Comment by wangmengyan95** [comment]
Hi @jsding, in Android 4.4, we use Android URLConnection library as our http client. I tested the code snippet and it worked fine in my Android 4.4.4 api level 19 emulator. So in your case, could you provide the following information
1. The full stacktrace
2. You test environment information
Thanks

**Comment by jsding** [comment]
My mistake. My network can not connect to api.parse.com, and the code throw this exception. Now, all are fine.

Thanks for your help.
