### ISSUE TITLE
ParseQueryAdapter doesn't exist?

### ISSUE THREAD

**Issue by ajfclark** [ParsePlatform/Parse-SDK-Android#171]
Reading through the guides and  tutorials available, there's a class called ParseQueryAdapter: https://www.parse.com/docs/android/guide#user-interface-parsequeryadapter
https://parse.com/tutorials/parse-query-adapter
https://parse.com/tutorials/mealspotting

It doesn't appear to be here though? It's also not listed in the SDK javadocs? Has it been deprecated?

**Comment by ajfclark** [comment]
I just noticed Issue #21 also addresses this so it can probably be closed.

It'd be nice if the tutorials were updated to reflect this change, particularly the ParseQueryAdapter tutorial.

**Comment by wangmengyan95** [comment]
Thanks for the suggestion, will do it.

**Comment by wangmengyan95** [comment]
[Commit](https://github.com/ParsePlatform/Docs/commit/45adb2703f3b7fb0ccee8693f3e0d493c91b1dea) in Parse-Doc.
