### ISSUE TITLE
SecurityException with Android Marshmellow

### ISSUE THREAD

**Issue by assizic** [ParsePlatform/Parse-SDK-Android#174]
Hi,

Multiple users with Nexus 6 who upgraded to Android Marshmallow are experiencing the following crash:

java.lang.SecurityException: ConnectivityService: Neither user 10128 nor current process has android.permission.ACCESS_NETWORK_STATE.
       at android.os.Parcel.readException(Parcel.java:1599)
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:974)
       at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:646)
       at com.parse.ConnectivityNotifier.isConnected(ConnectivityNotifier.java:43)
       at com.parse.ParsePinningEventuallyQueue.(ParsePinningEventuallyQueue.java:88)
       at com.parse.Parse.getEventuallyQueue(Parse.java:417)
       at com.parse.Parse$1.run(Parse.java:217)

Any idea?

Thanks a lot,
Assaf

**Comment by grantland** [comment]
`ACCESS_NETWORK_STATE` is considered a "Normal Permission", so there shouldn't be an issue with this permission with Android Marshmallow. Are you able to reproduce this?

https://developer.android.com/guide/topics/security/normal-permissions.html

**Comment by assizic** [comment]
Hi Grantland,

This does not happen to all our users, and happens sporadically. Here are the numbers:
- We have a few hundred beta users, out of them 32 have upgraded to Android 6.0.
- The crash happened a total of 49 times, to 9 different users (out of 32)
- It happens only with Android 6 (Nexus 5 & 6)
- When it happens to a user, it will often happen again and again immediately

Please let me know if I can provide any further info. We cannot roll out the version with this bug, as it seams to happen more and more as people upgrade their OS.

Thanks,
Assaf

**Comment by grantland** [comment]
Are you able to reproduce this? If so, could you please provide a working project along with concise reproduction steps that reproduces this issue?

**Comment by assizic** [comment]
No. This happened to 9 of our users, not in our lab.

**Comment by grantland** [comment]
Could you please describe the devices you tested this on (make/model, version, etc) and could you paste your `AndroidManifest.xml`? Feel free to remove any private information form your paste.

**Comment by assizic** [comment]
It happened to 6 users with nexus 5 (LG) and 3 with nexus 6 (Motorola).

Here's the permissions section of the manifest (as extracted from the APK):

N: android=http://schemas.android.com/apk/res/android
  E: manifest (line=2)
    A: android:versionCode(0x0101021b)=(type 0x10)0x6a9ef16
    A: android:versionName(0x0101021c)="1.118.00086-Rel" (Raw: "1.118.00086-Rel")
    A: android:installLocation(0x010102b7)=(type 0x10)0x1
    A: package="mobi.drupe.app" (Raw: "mobi.drupe.app")
    A: platformBuildVersionCode=(type 0x10)0x16 (Raw: "22")
    A: platformBuildVersionName="5.1.1-1819727" (Raw: "5.1.1-1819727")
    E: uses-sdk (line=8)
      A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
      A: android:targetSdkVersion(0x01010270)=(type 0x10)0x16
    E: permission (line=12)
      A: android:name(0x01010003)="mobi.drupe.app.permission.C2D_MESSAGE" (Raw: "mobi.drupe.app.permission.C2D_MESSAGE")
      A: android:protectionLevel(0x01010009)=(type 0x11)0x2
    E: uses-feature (line=17)
      A: android:name(0x01010003)="android.hardware.telephony" (Raw: "android.hardware.telephony")
    E: uses-permission (line=19)
      A: android:name(0x01010003)="mobi.drupe.app.permission.C2D_MESSAGE" (Raw: "mobi.drupe.app.permission.C2D_MESSAGE")
    E: uses-permission (line=20)
      A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
    E: uses-permission (line=21)
      A: android:name(0x01010003)="android.permission.ACCESS_WIFI_STATE" (Raw: "android.permission.ACCESS_WIFI_STATE")
    E: uses-permission (line=22)
      A: android:name(0x01010003)="com.google.android.c2dm.permission.RECEIVE" (Raw: "com.google.android.c2dm.permission.RECEIVE")
    E: uses-permission (line=23)
      A: android:name(0x01010003)="android.permission.WAKE_LOCK" (Raw: "android.permission.WAKE_LOCK")
    E: uses-permission (line=24)
      A: android:name(0x01010003)="android.permission.GET_ACCOUNTS" (Raw: "android.permission.GET_ACCOUNTS")
    E: uses-permission (line=25)
      A: android:name(0x01010003)="android.permission.MANAGE_ACCOUNTS" (Raw: "android.permission.MANAGE_ACCOUNTS")
    E: uses-permission (line=26)
      A: android:name(0x01010003)="android.permission.AUTHENTICATE_ACCOUNTS" (Raw: "android.permission.AUTHENTICATE_ACCOUNTS")
    E: uses-permission (line=27)
      A: android:name(0x01010003)="android.permission.READ_CONTACTS" (Raw: "android.permission.READ_CONTACTS")
    E: uses-permission (line=28)
      A: android:name(0x01010003)="android.permission.WRITE_CONTACTS" (Raw: "android.permission.WRITE_CONTACTS")
    E: uses-permission (line=29)
      A: android:name(0x01010003)="android.permission.CALL_PHONE" (Raw: "android.permission.CALL_PHONE")
    E: uses-permission (line=30)
      A: android:name(0x01010003)="android.permission.SYSTEM_ALERT_WINDOW" (Raw: "android.permission.SYSTEM_ALERT_WINDOW")
    E: uses-permission (line=31)
      A: android:name(0x01010003)="android.permission.GET_TASKS" (Raw: "android.permission.GET_TASKS")
    E: uses-permission (line=32)
      A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw: "android.permission.ACCESS_NETWORK_STATE")
    E: uses-permission (line=33)
      A: android:name(0x01010003)="android.permission.READ_CALL_LOG" (Raw: "android.permission.READ_CALL_LOG")
    E: uses-permission (line=34)
      A: android:name(0x01010003)="android.permission.WRITE_CALL_LOG" (Raw: "android.permission.WRITE_CALL_LOG")
    E: uses-permission (line=35)
      A: android:name(0x01010003)="android.permission.READ_PHONE_STATE" (Raw: "android.permission.READ_PHONE_STATE")
    E: uses-permission (line=36)
      A: android:name(0x01010003)="android.permission.RECEIVE_BOOT_COMPLETED" (Raw: "android.permission.RECEIVE_BOOT_COMPLETED")
    E: uses-permission (line=37)
      A: android:name(0x01010003)="android.permission.READ_EXTERNAL_STORAGE" (Raw: "android.permission.READ_EXTERNAL_STORAGE")
    E: uses-permission (line=38)
      A: android:name(0x01010003)="android.permission.WRITE_EXTERNAL_STORAGE" (Raw: "android.permission.WRITE_EXTERNAL_STORAGE")
    E: uses-permission (line=39)
      A: android:name(0x01010003)="android.permission.RECEIVE_SMS" (Raw: "android.permission.RECEIVE_SMS")
    E: uses-permission (line=40)
      A: android:name(0x01010003)="android.permission.WRITE_SYNC_SETTINGS" (Raw: "android.permission.WRITE_SYNC_SETTINGS")
    E: uses-permission (line=41)
      A: android:name(0x01010003)="android.permission.WRITE_SETTINGS" (Raw: "android.permission.WRITE_SETTINGS")
    E: uses-permission (line=42)
      A: android:name(0x01010003)="android.permission.SEND_SMS" (Raw: "android.permission.SEND_SMS")
    E: uses-permission (line=43)
      A: android:name(0x01010003)="android.permission.READ_CALENDAR" (Raw: "android.permission.READ_CALENDAR")
    E: uses-permission (line=44)
      A: android:name(0x01010003)="android.permission.WRITE_CALENDAR" (Raw: "android.permission.WRITE_CALENDAR")
    E: uses-permission (line=45)
      A: android:name(0x01010003)="android.permission.ACCESS_COARSE_LOCATION" (Raw: "android.permission.ACCESS_COARSE_LOCATION")
    E: uses-permission (line=46)
      A: android:name(0x01010003)="android.permission.ACCESS_FINE_LOCATION" (Raw: "android.permission.ACCESS_FINE_LOCATION")

LMK if I can provide anything further. Thanks.

**Comment by grantland** [comment]
Sorry, I meant the devices you personally or your team tested this on that it didn't reproduce.

**Comment by assizic** [comment]
It didn't reproduce in our lab on Nexus 5 with Android 6 and 5.1.1, Samsung S6 edge with Android 5.1, One plus with 5.1, Samsung S3 with 4.3.
Note that out of 700 beta users who ran this version, 9 users experienced the crash, all of them with Android 6 at the same day the Android M was released.

**Comment by grantland** [comment]
Since you aren't able to reproduce this with devices that that you are getting reports on, you're getting a very limited number of reports, and I've double-checked that our androidtTest suit passes on android-23, I'm going to close this as won't fix.

If you end up being able to reproduce this, we'll take another look at it.

**Comment by assizic** [comment]
Note that it is compiled with Android-22, but runs on devices with Marshmellow
