### ISSUE TITLE
Installation Object Creation Takes Too Much Time

### ISSUE THREAD

**Issue by hbabhishek** [ParsePlatform/Parse-SDK-Android#176]
Hi,

We are saving the installation object in our Android Application class using following code:

        Parse.initialize(this, PARSE_APP_ID, PARSE_APP_CLIENT_KEY);
		ParseUser.enableAutomaticUser();
		ParseACL defaultACL = new ParseACL();
		ParseInstallation.getCurrentInstallation().saveInBackground(new SaveCallback() {

			@Override
			public void done(ParseException exception) {
				if (exception == null) {
					UserDetails.getInstance(GlobalContext.this).setGCMRegistrationId(
							ParseInstallation.getCurrentInstallation().getObjectId());
				} else {
					exception.printStackTrace();
				}
			}
		});
		defaultACL.setPublicReadAccess(true);
		ParseACL.setDefaultACL(defaultACL, true);

It takes too much time in slow internet connection to save. 

We are sending the installation object id to our server to map installation object to particular user. 

If user leaves the app before we get the installation object saved and never returns then we have no means to map the user with its installation object id.

Can you please suggest a way to overcome the issue? Any best practices to save the installation object id on our third party server without missing a single installation?

**Comment by grantland** [comment]
If the problem is a user's slow internet connection, nothing really can be done to make it faster. As long as you're persisting the `ParseInstallation` `objectId` to your server after a successful `save()`, you should always have the data persisted to your server, without missing any installations.
