### ISSUE TITLE
ParseException on linking Anonymous user with Facebook

### ISSUE THREAD

**Issue by alphanso** [ParsePlatform/Parse-SDK-Android#18]
Summary of the bug:
ParseException Code : 999
message:  Linking to an external account not supported yet with signup_or_login. Use update instead.

Parse SDK version: 1.9.2
Facebook Android SDK version : 4.1.0
ParseFacebookUtils: V4-1.9.2

Steps to reproduce the bug:
https://github.com/alphanso/fb-bug-961932597190142

Steps :-
1. Launch app
2. Press 'Skip now'
3. Re-launch app
4. Press 'login with facebook'
5. Notice error message in console.

Previous bug report on facebook bug tool: https://developers.facebook.com/bugs/961932597190142

**Comment by grantland** [comment]
Could you try to write a simplified unit test case that can cause a repro? Please see our bug [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md#bugs).
