### ISSUE TITLE
Pinned data suddenly isn't available anymore

### ISSUE THREAD

**Issue by paatz04** [ParsePlatform/Parse-SDK-Android#181]
Hey,

sometimes (undefined time/couldn't reproduce it) I get a "this object is not availble in offline cache" exception when querying for a local object. In the first place I fetch the data from the backend with an include and pin it. The data is stored and available for a few days, until it suddenly disappears. 

I'm never unpinning something. I'm not doing an include for the backend query, for performance reasons, but I gather the data via fetchFromLocalDataStore once it is required. That call then throws the exception.

Does parse get rid of data if it consumes to much space? Or what else could cause this?

It's not a lot of data at all....

(Happens on simulator, nexus 4 and nexus 5 - running 5.1.1 and 6 )

**Comment by grantland** [comment]
We don't do any explicit unpinning behind the scenes, although there is a currently a known issue where nested objects of a pinned object might be lost under certain circumstances.

Would you be able to include any details of your object structure, queries, and pins?

**Comment by paatz04** [comment]
Is there any workaround to solve this known issue? 
Can I sent you the code in a private conversation? I'm not allowed to post bigger snippets public.

**Comment by grantland** [comment]
> Is there any workaround to solve this known issue?

The current workaround is to explicitly pin children that you require.

> Can I sent you the code in a private conversation? I'm not allowed to post bigger snippets public.

We don't really have something for that at the moment, would you be able to produce a small sample app that this reproduces with?

**Comment by paatz04** [comment]
I can do that - but it might take me another 2 weeks until I find the time. It's not easy extractable...

**Comment by grantland** [comment]
No problem, please keep us updated on your progress. Thanks!
