### ISSUE TITLE
Missing Parse.jar from the SDK download on QuickStart guide

### ISSUE THREAD

**Issue by jerefrer** [ParsePlatform/Parse-SDK-Android#184]
Hey guys,

I just tried to use Parse for the first time and was very confused when trying to follow the QuickStart guide. When I downloaded the `Parse-1.10.3` zip file there was just no `Parse-1.10.3.jar` file in it.

Then I started looking around and found [this StackOverflow issue](http://stackoverflow.com/questions/33028503/parse-com-parse-sdk-download-no-parse-1-10-3-jar-file-in-the-sdk) stating that now one should just add this line `compile 'com.parse:parse-android:1.10.3'` to the build.gradle file and that's it.

You may want to update the QuickStart guide to prevent losing future beginner users like me due to this ...

**Comment by enginegl** [comment]
Also, ParseCrashReporting.jar is missing.

**Comment by mnazemi** [comment]
Unfortunately we are unable to update to version 1.10.3 as ParseCrashReporting.jar is missing form Android SDK zip file.

**Comment by wangmengyan95** [comment]
Hi @jerefrer, thanks for your suggestion. There is a bug in our build script and we are working on fixing that. 
Right now, you can import Parse through maven as we described in README.md.
```groovy
dependencies {
  compile 'com.parse:parse-android:1.10.3'
}
```
or 
download the jar file [here](https://search.maven.org/remote_content?g=com.parse&a=parse-android&v=LATEST).

**Comment by tortabevonas** [comment]
I started despairing...

**Comment by odbol** [comment]
How does something like this pass the tests? Perhaps you should write a test to verify all the files are in the write place before pushing them to production?

**Comment by feedm3** [comment]
Had the same issue. Please update your [Quick Start](https://parse.com/apps/quickstart#parse_data/mobile/android/native/new) manual. Downloading the jar and adding it to the libs folders sounds like an advice from my grandpa ;) 

Adding just one line to the gradle file is all what is necessary.

**Comment by andreiasandei** [comment]
Can you also provide a link to the ParseCrashReporting.jar file?

**Comment by wangmengyan95** [comment]
We update our website. The new zip file contains all jars.

**Comment by tallior** [comment]
I just downloaded the zip from the website (here: https://parse.com/downloads/android/Parse-Starter-Project/latest)

It still doesnt include the ParseCrashReporting.jar file...

**Comment by mnazemi** [comment]
ParseCrashReporting.jar file is included in the Android SDK zip file which you should download from https://www.parse.com/downloads/android/Parse/latest

**Comment by tallior** [comment]
Thanks. There's another zip for a "new project" that doesnt include this
... (it downloads the SDK from gradle, and this jar is not there).

**Comment by rsweny** [comment]
ParseCrashReporting.jar is again missing in the 1.11.0 zip file and from all the starter projects.

**Comment by wangmengyan95** [comment]
@rsweny, please check #247
