### ISSUE TITLE
Unable to download Parse Android SDK

### ISSUE THREAD

**Issue by andreiasandei** [ParsePlatform/Parse-SDK-Android#187]
I know this is probably not the best place to ask this, but I didn't find a better one. On the parse website, at this link - https://parse.com/apps/quickstart#analytics/events/mobile/android/native/existing - there are instructions to download a zip file and get the parse-*.jar file(s).

Unfortunately, there are no such files in the zip file and therefore I can't use the SDK. Please adivse.

**Comment by wangmengyan95** [comment]
Same with #184, I will close this issue.
