### ISSUE TITLE
parserequest exception i/o failure on uploading parse file

### ISSUE THREAD

**Issue by Arash-gm** [ParsePlatform/Parse-SDK-Android#188]
i cannot upload any photo to parse and the exception is : 

    com.parse.ParseRequest$ParseRequestException: i/o failure

i'm using sdk version 1-9-4 and also checked 1-10-3 with no success , it was working just fine.

**Comment by grantland** [comment]
It sounds like you might just having internet connectivity issues.

* Can you post the full stack trace?
* Have you tested this on other devices/emulator/internet connections?

**Comment by Arash-gm** [comment]
Thx for the consideration i've looked for same issues and found this one on StackOverflow : 
http://stackoverflow.com/questions/32654945/cant-upload-image-file-to-parse-android
so i don't think that its connectivity issue , because it works just fine when i've tested my module about 3 weeks ago successfully and now its not working anymore and its also reported to me by our client.

Exception code is : 100 which is equal with : ErrorCodes.ParseErrorCodes.ERROR_CONNECTION.getValue() 

e : com.parse.ParseRequest$ParseRequestException: i/o failure
and caused by : java.net.SocketTimeoutException: Read timed out
detail message : i/o failure

**Comment by grantland** [comment]
Could you provide a small working sample that repros this and the environment you're using?

**Comment by Arash-gm** [comment]
its 2:45 am here , so its a bit hard to make a small project now ;) , i will send you a working copy to your email address tomorrow if its ok with you? also i wanted to mention that my network connection is working just fine and other requests to parse successfully interact with my app , also i can fetch parse file but i just can't upload.

**Comment by grantland** [comment]
Thanks! Looking forward to checking this out tomorrow

**Comment by Arash-gm** [comment]
@grantland : i've checked on some other devices and issue is gone , it was related to network upstream , so i close this issue and thanks for your help

**Comment by grantland** [comment]
No problem, thanks for updating us!

**Comment by yfsx** [comment]
same problem here, but what just happening here really strange :(

i have 5 phone to be tested (xiaomi 4i, asus zenfone 5, samsung galaxy tab, samsung s4, and sony c5) in same network with same apps. error 100 i/o failure appeared on samsung galaxy tab and sony c5, meanwhile the three (xiaomi 4i, zenfone 5 and s4) working perfectly. what just happen?

thanks
