### ISSUE TITLE
Update compileSdkVersion to 23 (Marshmallow)

### ISSUE THREAD

**Issue by grantland** [ParsePlatform/Parse-SDK-Android#189]
Required:
- [ ] Add legacy Apache Http Client support:

```
android {
  useLibrary 'org.apache.http.legacy'
}
```
- [ ] Add [`ParseSQLiteCursor#setExtras`](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseSQLiteCursor.java)
- [ ] Find solution to our `org.apache.http` usage for android-9 through android-18 (#231)
- [ ] Find a replacement for [`Notification#setLatestEventInfo(Context, CharSequence, CharSequence, PendingIntent)`](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/NotificationCompat.java#L60) (Solution Needed)

**Comment by rogerhu** [comment]
We have a PR open for this one now and just awaiting Maven/Sonatype push credentials.
