### ISSUE TITLE
Unable to Upload Image File to Parse

### ISSUE THREAD

**Issue by stanleyps** [ParsePlatform/Parse-SDK-Android#19]
Hello,
I have been having dificulties uploading my image file to parse. 
I have been using the same code and it used to work. But for some unknown reason, it stops working.
Please refer to a question I made in stackoverflow to for more details and hopefully you can also give me an answer to solve this problem.

This is the link:
http://stackoverflow.com/questions/31993831/upload-imagefile-to-parse-is-broken

**Comment by grantland** [comment]
Hi @stanleyps,

This doesn't seem like an actual SDK bug so I'll be closing this for now. Please refer to our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md) for proper bug reporting.
