### ISSUE TITLE
GCM regId problem

### ISSUE THREAD

**Issue by kardeslik** [ParsePlatform/Parse-SDK-Android#192]
Hi,

For GCM registration, instead of using the methods suggested by Google , `com.google.android.c2dm.intent.REGISTER` action has been explicitly started in `GCMRegistrar` and `com.google.android.c2dm.intent.REGISTRATION` action has been handled in `GCMService`.

This causes Parse to get raw registrationId from GCM instead of the final value when using Google Play Services library version 7.5.0 and later. Due to that raw value, push messages cannot be sent to the device.

Below are logging output I have put in `GCMRegistrar.handleRegistrationIntentAsync`, for single run:
Note that: It receives three different ids from GCM consecutively and the last one which contains some prefix overrides former ones.

    10-15 09:31:40.968 19752-19832/com.kardeslik.playground D/emmar:Parse regId = APA91bHv84H5zvFWWjHGQ1AQONAus3dzRLkEDA5i31alyKWariUb2T4MDyHbwPz3x_0RM0yuaA4VXtdDwzLxZYSa9iMORjtP0DG8x8JvC8dPGckGZVfKMANzMZ1XNpDfrMKxV3Ewcg4q

    10-15 09:31:42.872 19752-19832/com.kardeslik.playground D/emmar:Parse regId = APA91bEDXeU2a833_-NLbjVYZyOJB58LSlxRMw7maT7O9v7dWSDA7zdwBkjvBOdNThYI5vaTOOBq4BU2GItSHgyfpV6ahT2QZrAGTBJMP4uFP8ikoAO2C5miUvRhh8StfR9U4ZKMZbTT

    10-15 09:31:44.187 19752-19903/com.kardeslik.playground D/emmar:Parse regId = |ID|1|:dcma27oEKhk:APA91bEEhBNN3yh0eLlnXesonBhFrxu5x2pWTIS6Y7hMQA6OKD7TuXwqJw6EGsrOXXyp4pf-HVjSkvf7o7eUl1FZie4LQ509WOCW1tJDwkVPcJ9plD1D5hBpGY-YvOsayVf6gR__4BOz

**Comment by wangmengyan95** [comment]
Hi @kardeslik, I tried with a clean push project. I added log in `GCMRegistrar.handleRegistrationIntentAsync` and only saw one registrationId which returned from GCM. I could also get push notifications successfully. So, could you please provide more info like:
1. Could you see this issue consistently?
2. More detailed steps to repo this issue
3. You test environment
Thanks

**Comment by kardeslik** [comment]
Hi @wangmengyan95 ,
I have found the cause.
Together with Parse, I also use my own GCM registration implementation based on [Google's Set Up doc] (https://developers.google.com/cloud-messaging/android/client).

Since Parse receives all `com.google.android.c2dm.intent.REGISTRATION` actions, the action belonging to my own implementation is also being processed by `GCMRegistrar.handleRegistrationIntentAsync`.

Do you have any idea how can I use both together?

**Comment by wangmengyan95** [comment]
Hi @kardeslik, right now there is no good way to solve this problem since Parse `GCMRegistrar ` can not distinguish between different `com.google.android.c2dm.intent.REGISTRATION` actions. We are sorry but it is very hard to use them together.
