### ISSUE TITLE
ParseDateForm doesn't work - getTime() Error

### ISSUE THREAD

**Issue by dekrandroid** [ParsePlatform/Parse-SDK-Android#193]
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat: could not parse date: {"__type":"Date","iso":"2015-10-15T13:44:06.020Z"}
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat: java.text.ParseException: Unparseable date: "{"__type":"Date","iso":"2015-10-15T13:44:06.020Z"}" (at offset 0)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at java.text.DateFormat.parse(DateFormat.java:571)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at com.parse.ParseDateFormat.parse(ParseDateFormat.java:42)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at com.parse.ParseObject.mergeFromServer(ParseObject.java:986)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at com.parse.ParseObject.fromJSON(ParseObject.java:686)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at com.parse.ParseDecoder.decode(ParseDecoder.java:125)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at com.parse.ParseDecoder.convertJSONArrayToList(ParseDecoder.java:45)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at com.parse.ParseDecoder.decode(ParseDecoder.java:71)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at com.parse.ParseCloudCodeController.convertCloudResponse(ParseCloudCodeController.java:52)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at com.parse.ParseCloudCodeController$1.then(ParseCloudCodeController.java:36)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$14.run(Task.java:784)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.completeImmediately(Task.java:775)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.continueWith(Task.java:574)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.continueWith(Task.java:585)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$12.then(Task.java:679)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$12.then(Task.java:667)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$15.run(Task.java:825)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.completeAfterTask(Task.java:816)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.access$200(Task.java:32)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$11.then(Task.java:621)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$11.then(Task.java:618)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.runContinuations(Task.java:861)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.access$600(Task.java:32)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$TaskCompletionSource.trySetResult(Task.java:916)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$TaskCompletionSource.setResult(Task.java:950)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$15$1.then(Task.java:842)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$15$1.then(Task.java:829)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$14.run(Task.java:784)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.completeImmediately(Task.java:775)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.continueWith(Task.java:574)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.continueWith(Task.java:585)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$15.run(Task.java:829)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.completeAfterTask(Task.java:816)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.access$200(Task.java:32)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$11.then(Task.java:621)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$11.then(Task.java:618)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.runContinuations(Task.java:861)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.access$600(Task.java:32)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$TaskCompletionSource.trySetResult(Task.java:916)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$TaskCompletionSource.setResult(Task.java:950)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$15$1.then(Task.java:842)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$15$1.then(Task.java:829)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$14.run(Task.java:784)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.completeImmediately(Task.java:775)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.continueWith(Task.java:574)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task.continueWith(Task.java:585)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at bolts.Task$15.run(Task.java:829)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-15 15:44:08.895 15139-16265/com.kikocosmetics.android.app.debug V/ParseDateFormat:     at java.lang.Thread.run(Thread.java:818)
10-15 15:44:08.925 15139-15139/com.kikocosmetics.android.app.debug W/System.err: com.parse.ParseException: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
10-15 15:44:08.925 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:113)
10-15 15:44:08.925 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
10-15 15:44:08.925 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-15 15:44:08.925 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at android.os.Looper.loop(Looper.java:145)
10-15 15:44:08.925 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5832)
10-15 15:44:08.925 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-15 15:44:08.935 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-15 15:44:08.935 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
10-15 15:44:08.935 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
10-15 15:44:08.935 15139-15139/com.kikocosmetics.android.app.debug W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
10-15 15:44:08.935 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at com.parse.ParseObject$State$Init.createdAt(ParseObject.java:133)
10-15 15:44:08.935 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at com.parse.ParseObject.mergeFromServer(ParseObject.java:986)
10-15 15:44:08.935 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at com.parse.ParseObject.fromJSON(ParseObject.java:686)
10-15 15:44:08.935 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at com.parse.ParseDecoder.decode(ParseDecoder.java:125)
10-15 15:44:08.935 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at com.parse.ParseDecoder.convertJSONArrayToList(ParseDecoder.java:45)
10-15 15:44:08.935 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at com.parse.ParseDecoder.decode(ParseDecoder.java:71)
10-15 15:44:08.935 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at com.parse.ParseCloudCodeController.convertCloudResponse(ParseCloudCodeController.java:52)
10-15 15:44:08.935 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at com.parse.ParseCloudCodeController$1.then(ParseCloudCodeController.java:36)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$14.run(Task.java:784)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.completeImmediately(Task.java:775)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.continueWith(Task.java:574)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.continueWith(Task.java:585)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$12.then(Task.java:679)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$12.then(Task.java:667)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$15.run(Task.java:825)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.completeAfterTask(Task.java:816)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.access$200(Task.java:32)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$11.then(Task.java:621)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$11.then(Task.java:618)
10-15 15:44:08.945 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.runContinuations(Task.java:861)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.access$600(Task.java:32)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$TaskCompletionSource.trySetResult(Task.java:916)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$TaskCompletionSource.setResult(Task.java:950)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$15$1.then(Task.java:842)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$15$1.then(Task.java:829)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$14.run(Task.java:784)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.completeImmediately(Task.java:775)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.continueWith(Task.java:574)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.continueWith(Task.java:585)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$15.run(Task.java:829)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.completeAfterTask(Task.java:816)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.access$200(Task.java:32)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$11.then(Task.java:621)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$11.then(Task.java:618)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.runContinuations(Task.java:861)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.access$600(Task.java:32)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$TaskCompletionSource.trySetResult(Task.java:916)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$TaskCompletionSource.setResult(Task.java:950)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$15$1.then(Task.java:842)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$15$1.then(Task.java:829)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$14.run(Task.java:784)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-15 15:44:08.955 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.completeImmediately(Task.java:775)
10-15 15:44:08.965 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.continueWith(Task.java:574)
10-15 15:44:08.965 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task.continueWith(Task.java:585)
10-15 15:44:08.965 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at bolts.Task$15.run(Task.java:829)
10-15 15:44:08.965 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-15 15:44:08.965 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-15 15:44:08.965 15139-15139/com.kikocosmetics.android.app.debug W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-15 1

**Comment by dekrandroid** [comment]
ParseDateFormat: could not parse date: {"__type":"Date","iso":"2015-10-15T16:59:53.538Z"}

It looks Android SDK doesn't handle new parse Data type.

**Comment by grantland** [comment]
This seems to be a duplicate of #130.

Could you please verify if you're using JS SDK 1.6.2+?

**Comment by dekrandroid** [comment]
With JS SDK 1.6.2+ the problem is still there. We've rollbacked to 1.5.0 and everything works.Thanks.

**Comment by grantland** [comment]
FYI, this might be related to a fix in JS SDK 1.6.7: https://github.com/ParsePlatform/Parse-SDK-JS/releases/tag/v1.6.7
