### ISSUE TITLE
Parse Push channel subscriptions  and unsubscriptions for Android

### ISSUE THREAD

**Issue by adriansavarese** [ParsePlatform/Parse-SDK-Android#194]
I have a list of Channels in my android app (like a gridview with 15 elements) and user should select one or more options. Each option is a channel for Parse Push.

I am getting serius delay and in some cases lost of subscriptions and unsubscriptions channel request

I am using for each option 
ParsePush.subscribeInBackground("vegan"); and
ParsePush.unsubscribeInBackground("vegan");

Is there something wrong with my app?!
Thanks

**Comment by wangmengyan95** [comment]
Hi @adriansavarese, for me, it sounds like a backend issue. We continue to use the FB bug tool to track backend issues, where you can confidentially submit information about the exact app that you are having issues on. Could you file an issue there? https://www.parse.com/help? Thanks.

**Comment by grantland** [comment]
This doesn't actually seem like backend issue, nor does it seem like a SDK issue as your requests might just be failing for one reason or another. It might be worthwhile to ensure that your requests are failing or not by checking the result of your asynchronous task:

```java
ParsePush.subscribeInBackground("vegan").continueWith(new Continuation<Void, Void>() {
  @Override
  public Void then(Task<Void> result) {
    if (task.isFaulted()) {
      Log.d(TAG, "subscription failed", task.getError());
      return;
    }
    Log.d(TAG, "subscription succeeded");
  }
});
```

If you feel this issue has been mislabeled, feel free to follow up with us.
