### ISSUE TITLE
Parse SDK ParseQuery .include query error

### ISSUE THREAD

**Issue by darshana-ios** [ParsePlatform/Parse-SDK-Android#196]
Using .include query

The following code snippet sometimes returns "forum_mom" null even if exist in database,
```java
ParseQuery<ParseObject> forumQuery = ParseQuery.getQuery(ParseDefine.FORUM_CLASS);
ParseGeoPoint userLocation = momProfileObject.getParseGeoPoint(ParseDefine.KEY_MOM_LOCATION);
        int userDistance = momProfileObject.getInt(ParseDefine.KEY_MOM_DISTANCE);

        if (userDistance != 0 && userLocation != null) {
            if (forumFilter == ParseDefine.forumFilter.FORUM_FILTER_LOCAL) // Local
            {
                forumQuery.whereWithinMiles(ParseDefine.KEY_FORUM_LOCATION, userLocation, userDistance);
            } else if (forumFilter == ParseDefine.forumFilter.FORUM_FILTER_ALL) // ALL
            {
                forumQuery.orderByDescending("updatedAt");
            }

      forumQuery.setLimit(25);
            forumQuery.setSkip(skip);
            forumQuery.whereExists("forum_mom");
            forumQuery.include(String.format("%s.%s", "forum_mom" , "momUser"));
```

More info: 
Calss Forum --> Field --> forum_mom pointer<MomProfileData>
Calss MomProfileData --> momUser Pointer<_User>

However due to the fact that this problem seems to only affect few record in same table randomly,

**Comment by wangmengyan95** [comment]
Hi @darshana-ios, since you mention it works sometimes, it sounds like a backend issue. We continue to use the FB bug tool to track backend issues, where you can confidentially submit information about the exact app that you are having issues on. Could you file an issue there? https://www.parse.com/help? Thanks.
