### ISSUE TITLE
Implement Filterable on ParseQueryAdapter

### ISSUE THREAD

**Issue by elliottross23** [ParsePlatform/Parse-SDK-Android#20]
I need to implement filterable on ParseQueryAdapter but the list of objects is a private field. I'd be happy to implement a solution for this and contribute to the Parse Android SDK but I couldn't find the ParseQueryAdapter class here. Is it open source?

**Comment by grantland** [comment]
It was actually noted in our [release notes](https://github.com/ParsePlatform/Parse-SDK-Android/releases/tag/1.10.0) that `ParseQueryAdapter` and `ParseImageView` were moved to [ParseUI](https://github.com/ParsePlatform/ParseUI-Android).

**Comment by elliottross23** [comment]
Thanks @grantland
