### ISSUE TITLE
push notification not working at v.1.10.3

### ISSUE THREAD

**Issue by OlegTarashkevich** [ParsePlatform/Parse-SDK-Android#205]
I used push notifications at my project with parse-1.9.4 and all was OK. All pushes appear.
But then I decide to update parse library to 1.10.3 pushes become not work.

PLEASE HELP!!!
WHAT HAPPENED???

my code:

MANIFEST:

 < uses-permission android:name="android.permission.INTERNET" />
    < uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    < uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    < uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    < uses-permission android:name="android.permission.WAKE_LOCK" />
    < uses-permission android:name="android.permission.GET_ACCOUNTS" />
    < uses-permission android:name="android.permission.READ_PHONE_STATE" />
    < uses-permission android:name="com.android.vending.BILLING" />
    < uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    < uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

        <service android:name="com.parse.PushService" />

        <receiver
            android:name=".parse.NParsePushBroadcastReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />

                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.RECEIVE_BOOT_COMPLETED" />
                <action android:name="android.intent.action.USER_PRESENT" />
            </intent-filter>
        </receiver>
        

APPLICATION:

public class App extends com.activeandroid.app.Application {
@Override
    public void onCreate() {
        super.onCreate();
Parse.initialize(this, MY_APP_ID, CLIENT_KEY);
Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE);
}

BROADCASTRECEIVER:

public class NParsePushBroadcastReceiver extends ParsePushBroadcastReceiver {
    private static final String TAG = "NParsePushBroadcastReceiver";
    private Context context;

    @Override
    public void onReceive(Context context, Intent intent) {
        this.context = context;
        Logger.log(TAG, "NParsePushBroadcastReceiver onReceive()");

        if (intent != null && intent.getExtras() != null) {
            String jsonData = intent.getExtras().getString("com.parse.Data");
            Logger.log(TAG, "jsonData: " + jsonData);
            if (jsonData != null) {
                ParsePush push = Utility.getGSON().fromJson(jsonData, ParsePush.class);
            }
        } 
    }
}

**Comment by grantland** [comment]
Could you enable logging and paste the logcat output to help us identify the issue?

```java
Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE);
```

**Comment by sudotong** [comment]
I'm also having this issue. Will try enabling log level verbose.. Quick question-- are the 

<action android:name="android.intent.action.BOOT_COMPLETED" />
            <action android:name="android.intent.action.RECEIVE_BOOT_COMPLETED" />
            <action android:name="android.intent.action.USER_PRESENT" />

intent filters needed/useful? In the documentation it doesnt seem to require them. (https://parse.com/apps/quickstart#parse_push/android/native/existing)

**Comment by grantland** [comment]
@sudotong  They are not needed for GCM.

**Comment by sudotong** [comment]
Great. BTW I seemed to have solved the issue by populating the GCMSenderId field in parse with the GCM sender ID. Note that this wasn't needed for parseVersion 1.9.3, but it was needed for 1.10.3

**Comment by grantland** [comment]
@sudotong This should only be used if you've ported your installations from another push provider or you're using your own GCM Sender ID to send pushes:

From https://parse.com/docs/android/guide#push-notifications-installations
> GCMSenderId: This field only has meaning for Android ParseInstallations that use the GCM push type. It is reserved for directing Parse to send pushes to this installation with an alternate GCM sender ID. This field should generally not be set unless you are uploading installation data from another push provider. If you set this field, then you must set the GCM API key corresponding to this GCM sender ID in your Parse application's push settings.
