### ISSUE TITLE
OutOfMemoryError ParseURLConnectionHttpClient.java line 51

### ISSUE THREAD

**Issue by OlegTarashkevich** [ParsePlatform/Parse-SDK-Android#206]
Parse v.1.10.3
Fatal Exception: java.lang.OutOfMemoryError
	
java.io.ByteArrayOutputStream.expand (ByteArrayOutputStream.java:91)
com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream (HttpsURLConnectionImpl.java:254)
com.parse.ParseURLConnectionHttpClient.executeInternal (ParseURLConnectionHttpClient.java:51)
com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed (ParseHttpClient.java:158)
com.parse.ParsePlugins$1.intercept (ParsePlugins.java:115)
com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed (ParseHttpClient.java:147)
com.parse.ParseHttpClient.execute (ParseHttpClient.java:122)
com.parse.ParseRequest$3.then (ParseRequest.java:150)
com.parse.ParseRequest$3.then (ParseRequest.java:147)
bolts.Task$15.run (Task.java:825)
bolts.BoltsExecutors$ImmediateExecutor.execute (BoltsExecutors.java:105)
bolts.Task.completeAfterTask (Task.java:816)
bolts.Task.continueWithTask (Task.java:628)
bolts.Task.continueWithTask (Task.java:639)
bolts.Task$13.then (Task.java:731)
bolts.Task$13.then (Task.java:719)
bolts.Task$15.run (Task.java:825)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.lang.Thread.run (Thread.java:841)

![2015-10-20 23 23 16](https://cloud.githubusercontent.com/assets/13828110/10620060/c32479f0-7781-11e5-95e1-36a6929fc3e1.png)

**Comment by grantland** [comment]
OOM exceptions are generally just a side affect of a memory leak somewhere else in your application. Would you be able to provide a project with reliable repro steps with just the Parse SDK?
