### ISSUE TITLE
Fatal Exception: java.lang.IncompatibleClassChangeError Couldn't find com.parse.ParseClassName.value

### ISSUE THREAD

**Issue by OlegTarashkevich** [ParsePlatform/Parse-SDK-Android#207]
Parse v.1.10.3
![2015-10-20 23 27 29](https://cloud.githubusercontent.com/assets/13828110/10620214/7d5ac9fa-7782-11e5-8a2c-9e1dcc7751c6.png)

Fatal Exception: java.lang.IncompatibleClassChangeError
Couldn't find com.parse.ParseClassName.value
 raw
libcore.reflect.AnnotationAccess.toAnnotationInstance (AnnotationAccess.java:659)
java.lang.Class.getAnnotation (Class.java:343)
com.parse.ParseObject.getClassName (ParseObject.java:3642)
com.parse.ParseObject.registerSubclass (ParseObject.java:522)
com.parse.ParseObject.registerParseSubclasses (ParseObject.java:3676)
com.parse.Parse.initialize (Parse.java:202)
com.lucky.notewidget.App.onCreate (App.java:66)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1020)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:5245)
android.app.ActivityThread.access$1600 (ActivityThread.java:181)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1537)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:6134)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1194)

**Comment by grantland** [comment]
This seems like you've possibly improperly set up your ParseObjects.

If this has been incorrectly closed, feel free to reopen with the information outlined in our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md).

**Comment by OlegTarashkevich** [comment]
I have 100.000 users and all working fine. But I have troubles with samsung devices and only with 8 users (see screenshot). In general gson annotations sometimes not working with samsung. Can you check it or somehow fix from parse side???

**Comment by grantland** [comment]
In order for us to be able to debug this issue, you'd need to provide more information to help us reproduce the issue. Check out our Contributing Guidelines for more information.
