### ISSUE TITLE
Where is ParseQueryAdapter?

### ISSUE THREAD

**Issue by Nidre** [ParsePlatform/Parse-SDK-Android#21]
I can't seem to be able to find ParseQueryAdapter?

I've extended ParseQueryAdapter in our application with Parse SDK 1.9.4, but I can't seem to be able to find ParseQueryAdapter in 1.10.0.

I could not find it here in the github either. Is it removed/replaced or am I missing something?

**Comment by grantland** [comment]
It was actually noted in our [release notes](https://github.com/ParsePlatform/Parse-SDK-Android/releases/tag/1.10.0) that `ParseQueryAdapter` and `ParseImageView` were moved to [ParseUI](https://github.com/ParsePlatform/ParseUI-Android).

**Comment by Nidre** [comment]
My bad :) I've checked everywhere(Google) but release notes.

**Comment by kamoljan** [comment]
thank you!

**Comment by juampavilla** [comment]
add to build.gradle this:
    compile 'com.parse:parseui-login-android:0.0.1'
    compile 'com.parse:parseui-widget-android:0.0.1'
