### ISSUE TITLE
Parse not registering device.

### ISSUE THREAD

**Issue by rajkotraja** [ParsePlatform/Parse-SDK-Android#210]
i followed all steps listed at https://parse.com/apps/quickstart#parse_push/android/native/existing

But my device is not registering only.
i edited my main java activity with pash initialize and ParseInstallation.getCurrentInstallation().saveInBackground();

And edited manifest xml with given changes in documentation.
Please tell me why it is not registering device.

**Comment by grantland** [comment]
I'm not sure I understand the problem you're having. Please refer to our Contributing Guidelines for more information regarding reporting issues with our SDK.
