### ISSUE TITLE
ParseFile crash app if pressed BackButton

### ISSUE THREAD

**Issue by Whbcc** [ParsePlatform/Parse-SDK-Android#212]
This is my code 

    final ParseFile parseFile = parseObject.getParseFile("image");
                  parseFile.getDataInBackground(new GetDataCallback() {
                      @Override
                      public void done(byte[] bytes, ParseException e) {
                          
                      }
                  });

Problem:  If i press the back button before the image is load in the imageView, the app will crash.
I tried using parsefile.cancel(); but no solution.
Is there any other implementation to avoid ParseFile crashing if it is not fully ready to be load into the UI View.

**Comment by wangmengyan95** [comment]
Hi @Whbcc, could you paste your stacktrace?

**Comment by Whbcc** [comment]
Solved.. Thanks
