### ISSUE TITLE
Parse doesn't seem to pin correct data if the query used for pinning is restricted

### ISSUE THREAD

**Issue by ajfclark** [ParsePlatform/Parse-SDK-Android#217]
I was finding that my application was displaying the incorrect number of items in an index. On further investigation, I found the following:

In my init code is something like:
```
ParseQuery query = ParseQuery.getQuery("class").whereEquals("appVersion", "1.0");
List list = query.find();
ParseObject.fetchAll(list);
ParseObject.pinAll(list);
```
Then in my query to generate the index:
```
ParseQuery query = ParseQuery.getQuery("class").whereEquals("appVersion", "1.0").fromLocalDatastore();
List list = query.find();
Log.d(list.size());
```
This output 46 in the logcat.

Removing the restriction from the initial query used for pinning:
```
ParseQuery query = ParseQuery.getQuery("class");
List list = query.find();
ParseObject,fetchAll(list);
ParseObject.pinAll(list);
```
Then in my query to generate the index:
```
ParseQuery query = ParseQuery.getQuery("class").whereEquals("appVersion", "1.0").fromLocalDatastore();
List list = query.find();
Log.d(list.size());
```
And now the logcat has 48 and the index has the right number of objects.

Am I missing something? Shouldn't a query with the same restrictions return the same objects?

**Comment by wangmengyan95** [comment]
Hi @ajfclark, when you call `query.find()`, we fecth the data from Parse server. So could you please verify for this query
```
ParseQuery query = ParseQuery.getQuery("class").whereEquals("appVersion", "1.0");
List list = query.find();
```
and for this query
```
ParseQuery query = ParseQuery.getQuery("class");
List list = query.find();
```
the results(list) returned from Parse server are the same?

**Comment by ajfclark** [comment]
No the result sets are not the same.

If the initial pinning query has restriction set A on it, a query which also has restriction set A on it returns 46 items.

If the initial pinning query has no restrictions, a query with restriction set A on it returns 48 items.

Given that the same restriction sets are used in all cases, the numbers returned should be the same, correct?

**Comment by wangmengyan95** [comment]
Hi @ajfclark, I do not think so, since your initial pinning queries have different results, when you pin these results, that means different data has been saved to the local datastore. In this time, even you use same queries to fetch the data, since for the two times, the data is different, the results should be different, right?

**Comment by ajfclark** [comment]
Basic set theory makes me think:

Select * from data where conditionA
save
select * from saved data where conditionA

Should be the same result as:

select * from data
save
select * from saved data where conditionA

eg.

I have a pile of apples and oranges.

In the first instance, only select the oranges and put them in the saved box. Now pull all the oranges out of the saved box and count them.

In the second, put all the fruit in the saved box. Now pull out all the oranges and count them.

In both cases the number of oranges found should be the same. The behaviour I'm seeing with Parse indicates it's not.

**Comment by wangmengyan95** [comment]
Hi @ajfclark, I got you point, thanks for the explanation. Since it is really hard for us to reproduce it, is it possible for you to upload a sample app for us to debug? Thx.

**Comment by ajfclark** [comment]
I'm not going to have a chance to look at this for a while. I'm going to close it and if I get a chance and can produce something repeatable, I'll reopen.
