### ISSUE TITLE
Why so many RuntimeExceptions?

### ISSUE THREAD

**Issue by axm** [ParsePlatform/Parse-SDK-Android#22]
For example in `ParseUser`, `ParseACL`, `Parse` etc. A lot of the exceptions that are thrown (often as a result of `JSONException`s) are `RuntimeException`s. What's the reason for this? So you don't pollute everything with checked exceptions?

**Comment by grantland** [comment]
You pretty much guessed it. We use this pattern in areas where we can guarantee that the JSON operations wouldn't cause a `JSONException`, such as copying a `JSONObject`.

**Comment by axm** [comment]
Thanks ;)
