### ISSUE TITLE
Crashes don't show up on console

### ISSUE THREAD

**Issue by Arash-gm** [ParsePlatform/Parse-SDK-Android#221]
i've used parse crash reporting on my other apps , so i know how ti use it , but the problem is the console doesn't update and it shows always "you don't have any crashes yes"
i've added 
    throw new RuntimeException("Test Exception!");
and logcat shows : 

    10-28 00:24:32.945    3022-3022/com.xxx .xxx D/CrashReporting﹕ Generating report file for crash
    10-28 00:24:33.042    3022-3022/com.xxx.xxx D/CrashReporting﹕ Retrieving logcat output...
    10-28 00:24:33.079    3022-3022/com.xxx.xxx D/CrashReporting﹕ Retrieving logcat output...
    10-28 00:24:33.119    3022-3022/com.xxx.xxx D/CrashReporting﹕ Retrieving logcat output...
    10-28 00:24:33.269    3022-3022/com.xxx.xxx V/CrashReporting﹕ About to start ReportSenderWorker from #handleException
    10-28 00:24:33.272    3022-3080/com.xxx.xxx D/CrashReporting﹕ #checkAndSendReports - start
    10-28 00:24:33.273    3022-3080/com.xxx.xxx D/CrashReporting﹕ Looking for error files in /data/data/com.xxx .xxx /files/com.parse/cr/reports
    10-28 00:24:33.273    3022-3080/com.xxx.xxx D/CrashReporting﹕ Loading file 1445979272945-RuntimeException-1.stacktrace
    10-28 00:24:33.290    3022-3080/com.xxx.xxx I/CrashReporting﹕ Sending file 1445979272945-RuntimeException-1.stacktrace
    10-28 00:24:33.290    3022-3080/com.xxx.xxx D/CrashReporting﹕ Sending crash report to Parse...
    10-28 00:24:33.299    3022-3080/com.xxx.xxx D/CrashReporting﹕ #checkAndSendReports - finish

**Comment by grantland** [comment]
This looks to be a backend issue since the crash reports are successfully being sent.

**Comment by sierbrat** [comment]
I have the same problem

**Comment by grantland** [comment]
Closing since we only track SDK issues here.

**Comment by wangbourne** [comment]
I also have been troubled in the same problem for weeks. Is there any update after you say "Closing since we only track SDK issues here"? 
 I tried to raise a question on Parse.com, but your guys give me following message. 
"The Parse Android SDK is now open source so bugs will not be handled through the bug tool anymore but at its own GitHub repository. Please use the following link to report an issue:https://github.com/ParsePlatform/parse-sdk-android/issues"
