### ISSUE TITLE
Parse Local Datastore on Android and Pinning Issue

### ISSUE THREAD

**Issue by WanClem** [ParsePlatform/Parse-SDK-Android#222]
Hi guys,was trying out the Parse SDK on android and noticed something quite unusual.I fetched a long list of Parse Objects from online and Pinned them on the local data store to be shown later in case the user is offline.It worked pretty well,but when I long Click the Home Button on my android Device and clears cache,if I go back to the app,my local data store content is all gone.Pls look into this.Thanks.

**Comment by wangmengyan95** [comment]
Hi @WanClem, what do you mean clear caches? If this means you clear the cache directory of your app, it will cause problems of local data store since we use that directory to store the SQLite database.

**Comment by WanClem** [comment]
On my android Device(Infinix),If I long Click the HOME Button and clears all recent applications,I get the feed back "Cache Cleared" from the 'Recent Apps Clearing Task' and not from my app.Now,when I reopen my app offline to see if the local datastore content I pinned Previously can be displayed,the list  returned is now empty.This is not the case when the Home button is not long clicked and Recent Apps are not cleared(I mean the Local Datastore works fine if Recent Apps are not cleared by long clicking the Home Button).

**Comment by wangmengyan95** [comment]
Hi @WanClem, what do you mean Recent Apps Clearing Task? It is your device specific function or some log output in your app's console. Could you verify the behaviour in a standard emulator?

**Comment by WanClem** [comment]
Simply put if I remove my app from recent apps by long clicking home button,on reopening my app again gets local datastore wiped out.

**Comment by wangmengyan95** [comment]
Hi @WanClem, I tried with my device and emulator but I still could not repo this issue. I am not sure whether it is our SDK's issue or your device's issue. Could you verify the behaviour in a standard emulator and upload a sample project for us to debug if possible?
