### ISSUE TITLE
parseobject.deleteInBackground(callback) fails when stetho is enabled

### ISSUE THREAD

**Issue by jmfayard** [ParsePlatform/Parse-SDK-Android#226]
Hello,

We have found out that deleting objects did not work anymore.

```java
parseobject.deleteInBackground(new DeleteCallback() {
           @Override
           public void done(ParseException e) {
               Log.d("BUG","BUG");
           }
       });
```

gave the exception **`com.parse.ParseException: java.lang.ClassCastException: com.squareup.okhttp.RequestBody$2 cannot be cast to com.parse.ParseOkHttpClient$ParseOkHttpRequestBody`**

No logs whatsoever with `$ parse logs -f `

Investigating the bug, we found out that object is deleted correctly when we disable https://github.com/facebook/stetho 

```java
       // called when the application starts
        Stetho.InitializerBuilder initializerBuilder =  Stetho.newInitializerBuilder(application);

        // Commenting those lines solves the bug
        initializerBuilder.enableWebKitInspector(
                Stetho.defaultInspectorModulesProvider(application)
        );
        Parse.addParseNetworkInterceptor(new ParseStethoInterceptor());
```

For reference, here are the versions of the libs we are using

```gradle
ext.libs = [
            bolts:                       "com.parse.bolts:bolts-android:1.2.1",
            okhttp:                     "com.squareup.okhttp:okhttp:2.5.0",
            okhtturlconnection:  "com.squareup.okhttp:okhttp-urlconnection:2.5.0",
            parse:                      "com.parse:parse-android:1.10.2",
            stetho:                      "com.facebook.stetho:stetho:1.2.0",
            stethookhttp:            "com.facebook.stetho:stetho-okhttp:1.1.1",
            stethoparse:             "com.parse:parseinterceptors:0.0.1",
    ]
```

**Comment by wangmengyan95** [comment]
Hi @jmfayard, I test the empty sample app with the following dependency and it works fine.
```gradle
    compile 'com.android.support:appcompat-v7:22.2.0'

    compile 'com.parse.bolts:bolts-android:1.2.1'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.5.0'
    compile 'com.parse:parse-android:1.10.3'
    compile 'com.facebook.stetho:stetho:1.2.0'
    compile 'com.facebook.stetho:stetho-okhttp:1.1.1'
    compile 'com.parse:parseinterceptors:0.0.1'
```
The only different is I initialize Stetho in a different way like this as the Stetho reccommends
```java
    // called when the application starts
    Stetho.initializeWithDefaults(this);
    Parse.addParseNetworkInterceptor(new ParseStethoInterceptor());
```
Could you try that to see wether you still see the exception. If you still have the issue, is it possible for you to upload a sample project for us to debug?

**Comment by jmfayard** [comment]
@wangmengyan95 

I don't have my computer right now, but the setup you are referring to does not include the new debugging tool that allows to watch Parse Network Requests from `chrome://inspect` described in this blog post http://blog.parse.com/announcements/parse-debugging-tools-identify-client-side-issues-faster/

![parse + chrome tools](http://blog.parse.com/wp-content/uploads/2015/09/image-1024x585.png)


And the proposed setup is this one

```java
Stetho.initialize(
    Stetho.newInitializerBuilder(this)
        .enableWebKitInspector(Stetho.defaultInspectorModulesProvider(this))
        .build());
Parse.addParseNetworkInterceptor(new ParseStethoInterceptor());
// Interceptor should be added before your initialize Parse
Parse.initialize(this);
```

**Comment by wangmengyan95** [comment]
@jmfayard, since Stetho updates after we release Parse Interceptor, so the blog is actually a little bit out-dated. Please always check out repo [wiki](https://github.com/ParsePlatform/ParseInterceptors-Android/wiki) as the latest reference.

**Comment by slimmii** [comment]
I get the same exception (and I'm not using Stetho)

If I add a networkinterceptor:

                .addNetworkInterceptor(new com.parse.interceptors.ParseLogInterceptor())

I get the same exception and when I remove it I no longer get the exception.

**Comment by renegens** [comment]
I have the same problem over a year later. What is the status of this?

**Comment by kamauwairegi** [comment]
I have the same issue too, any fix?

**Comment by AmitGoenka** [comment]
I have the same issue too

**Comment by kamauwairegi** [comment]
I managed to fix my problem by commenting this line of code, maybe I will help someone going though same issue like me

//builder.addNetworkInterceptor(new LoggingParseNetworkInterceptor());

**Comment by renegens** [comment]
Yes as posted by @slimmii  but this is neither a work around nor a solution. You simple disable a feature.

**Comment by dev-JE02** [comment]
I'm having the same problem. It also doesn't go away even after removing the loggingInterceptors. I'm using 1.13.1

**Comment by dev-JE02** [comment]
Any updates on this issue?

**Comment by AlejandroHCruz** [comment]
Any updates on this issue?
