### ISSUE TITLE
Use URLConnection http client for android versions >= 2.3 (Gingerberad)

### ISSUE THREAD

**Issue by yairkukielka** [ParsePlatform/Parse-SDK-Android#227]
If okhttp is not present, URLConnection http client is being used if android version is KITKAT and above. I think URLConnection http client could be used for Ginberbread and above. See this article (notably the last part) for more detailed info: http://android-developers.blogspot.com/2011/09/androids-http-clients.html

This would be a small change in the ParseHttpClient.createClient() method.

**Comment by wangmengyan95** [comment]
Hi @yairkukielka, we are working on that right now. Since we got several bugs related to URLConnection about file upload/download for android 2.3, we need to verify them before make the changes.

**Comment by rogerhu** [comment]
@wangmengyan95 did these bugs ever get fixed?  happy to talk offline if we need to discuss the issues

**Comment by Jawnnypoo** [comment]
I would opt instead to just use Okhttp as a hard dependency on all versions and not bother with other HttpClients (reduce the number of potential bugs with other HttpClients)

**Comment by rogerhu** [comment]
Yeah let's go that direction.
