### ISSUE TITLE
Advanced push targeting not working initially

### ISSUE THREAD

**Issue by deepak2510** [ParsePlatform/Parse-SDK-Android#229]
I am building a group chatting tool, which uses advanced targeting to target push notifications to users from a specific group like so : 

    ParseQuery parseQuery = ParseInstallation.getQuery().whereEqualTo("groups", group_id);

In my App onCreate, I am doing this : 

     if(!ParseInstallation.getCurrentInstallation().containsKey("groups")){
            List<String> groups = new ArrayList<>();
            ParseInstallation.getCurrentInstallation().put("groups", groups);
        }

And then every time a new message comes in(via XMPP) I am doing this : 

    List<String> parse_groups = (ArrayList<String>) ParseInstallation.getCurrentInstallation().get("groups");
            // Subscribe to GCM notifications for this group if not already subscribed.
            if(!parse_groups.contains(group_id)) {
                parse_groups.add(group_id);
            }

--
When I send a message to this query : 
    
    ParseQuery parseQuery = ParseInstallation.getQuery().whereEqualTo("groups", group_id);

It initially does not send it to all the participants, in the group. 

However, after a day or so, it starts sending notifications to all members (not the old notifications, but any new ones).

I have checked the dashboard, and it correctly reflects the installation objects for the above query when I  filter the data, i.e the correct number of installation objects show up for a particular group_id. So the data is being saved correctly, but the pushes are not being sent. 

When I check the push dashboard, it shows only 1 push sent, when there are actually 2 users and therefore 2 installation objects.

I can't use channels for this purpose as my group_id can contain some special characters which channels doesn't support, hence using this approach. 

Thanks.

**Comment by grantland** [comment]
This sounds like a backend issue as the SDK doesn't handle compiling the list of receipients for a push notification, so I'll be closing this issue. I recommend opening up a backend ticket at http://parse.com/help

Additionally, you can utilize `ParseObject#addUnique(key, value)` instead of `#contains(key)` and `#add(key, value)`.

> It initially does not send it to all the participants, in the group. However, after a day or so, it starts sending notifications to all members (not the old notifications, but any new ones).

This is also a backend issue, which was probably a hiccup in our push queues. If this is still persisting I'd recommend opening up a separate backend ticket for it.
