### ISSUE TITLE
Cannot update current user parseSDK1.10.0

### ISSUE THREAD

**Issue by kenilt** [ParsePlatform/Parse-SDK-Android#23]
I got error message Parse::UserCannotBeAlteredWithoutSessionError
Please tell me why?

    if (ParseUser.getCurrentUser() != null) {
        ParseUser currentUser = ParseUser.getCurrentUser();
        if (edtEmail.getText().toString().length() > 0) {
            currentUser.setEmail(edtEmail.getText().toString());
        }
        currentUser.setUsername(edtUsername.getText().toString());
        currentUser.put(Constants.K_FE_PARSE_USER_BIO, edtBio.getText().toString().trim());
        currentUser.put(Constants.K_FE_PARSE_USER_LOCATION, edtLocation.getText().toString().trim());
        currentUser.put(Constants.K_FE_PARSE_USER_HEIGHT, sbHeight.getProgress());
        if (edtPassword.getText().toString().length() > 1) {
            currentUser.setPassword(edtPassword.getText().toString());
        }
        if (countryCode == null) {
            countryCode = new CountryCodes().getCode(edtLocation.getText().toString());
        }
        currentUser.put(Constants.K_FE_PARSE_USER_COUNTRY_CODE, countryCode);

        final MaterialDialog dialog = MaterialDialogUtils.createProgressDialog(activity);
        dialog.show();
        currentUser.saveInBackground(new SaveCallback() {
            @Override
            public void done(ParseException e) {
                dialog.dismiss();
                if (e != null) {
                    ParseManager.getInstance().checkAndShowErrorMessage(activity, e);
                } else {
                    if (isNeedToSendEmail) {
                        ParseUser currentUser = ParseUser.getCurrentUser();
                        if (currentUser != null) {
                            ParseManager.getInstance().sendVerifyEmailTo(activity, currentUser.getEmail(), currentUser.getObjectId(), currentUser.getString(Constants.K_FE_PARSE_USER_FIRST_NAME));
                        }
                    }
                }
            }
        });
    }

**Comment by vishweshwarp** [comment]
I think this bug is same as https://developers.facebook.com/bugs/898928300168631. I am also facing same issue. This issue started from SDK 1.9.3 and exists in 1.10.0 also.

Please fix the issue ASAP.

**Comment by grantland** [comment]
@kenilt Please update your original issue with information listed in our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md), such as a link to a PR with a failing unit test, stack trace, etc.

@vishweshwarp Until this issue is updated, I'm not certain that this is the same issue reported in that bug. In either case, that bug is currently being addressed in #3.

**Comment by kenilt** [comment]
Yeah, great. It was fixed after update to 1.10.1

**Comment by ominfowave** [comment]
This issue is still present in 1.26.0

**Comment by mtrezza** [comment]
@ominfowave Please open a new issue and reference this issue if you encounter the same or a similar bug. This issue has been closed.
