### ISSUE TITLE
Issue with android M compilesdkversion 23

### ISSUE THREAD

**Issue by RahulRvR** [ParsePlatform/Parse-SDK-Android#231]
I am getting the following gradle error after updating to latest sdk version 

>Warning:com.parse.ParseApacheHttpClient: can't find referenced method 'org.apache.http.conn.ssl.SSLSocketFactory getHttpSocketFactory(int,android.net.SSLSessionCache)' >in library class android.net.SSLCertificateSocketFactory

I am using "useLibrary" option in the gradle file to include legacy apache
android {
useLibrary 'org.apache.http.legacy'
}

**Comment by grantland** [comment]
This seems related to #189. Unfortunately I thought this was only an issue with compiling the SDK with `compileSdkVersion = 23`, but it's actually a problem using it as well. I'll try to get a fix out soon.

**Comment by RahulRvR** [comment]
@grantland  cool , Thanks. When I can expect the fix for this.

**Comment by grantland** [comment]
A workaround for now would be to lower the `compileSdkVersion` as long as you're not using any specific M APIs.

**Comment by grantland** [comment]
Unfortunately this looks like a deeper problem than I originally thought. We're utilizing some APIs that were completely removed from android-23 that aren't even in the Apache Http Legacy support library:

```java
SSLCertificateSocketFactory.getHttpSocketFactory(socketOperationTimeout, sslSessionCache)
```

Originally I thought we could use the code that the above method used internally, but it looks like that was no longer exist as well:

```java
public static org.apache.http.conn.ssl.SSLSocketFactory getHttpSocketFactory(
        int handshakeTimeoutMillis, SSLSessionCache cache) {
    return new org.apache.http.conn.ssl.SSLSocketFactory(
            new SSLCertificateSocketFactory(handshakeTimeoutMillis, cache, true));
}
```
(from https://android.googlesource.com/platform/frameworks/base/+/lollipop-release/core/java/android/net/SSLCertificateSocketFactory.java#158)

The above is necessary to cache SSL sessions and removing it would slow down all requests for all devices utilizing `org.apache.http`.

Using `compileSdkVersion = 22` is still a valid workaround as long as you're not using APIs from android-23. 

We'll be looking into completely removing Apache from our codebase pending some testing of whether or not `HttpURLConnection` works well on android-9 through android-18, which we'll do by the end of the week.

**Comment by RahulRvR** [comment]
I am looking into updating the support libraries to the latest version , which require us to update the compileSdkVersion to 23. A tentative date for the fix would help me plan accordingly.

**Comment by grantland** [comment]
If everything works smoothly with HttpURLConnection, end of next week.

By the way, I'm trying to reproduce this issue and have tried both running a debug app with `compileSdkVersion = 23` and building a signed release, but neither turn up this error. Could you specify some repro steps? /cc @iampawan

**Comment by RahulRvR** [comment]
Did you enable 
>android {
useLibrary 'org.apache.http.legacy'
>}
I am using the legacy apache on my project , So had to include this.

**Comment by grantland** [comment]
Yes I did enable that. Are you pulling in the SDK from source or are you using the compiled `jar` or Maven Central repository? Are you able to reproduce this issue with the ParseStarterProject?

**Comment by RahulRvR** [comment]
I haven't tried the parseStarterProject . I am including the following dependency in gradle for parse 

>compile 'com.parse:parse-android:1.10.3'

**Comment by grantland** [comment]
Could you attempt to reproduce this issue with the blank ParseStarterProject and post your repro steps here?

**Comment by iampawan** [comment]
i am using   compile 'com.parse:parse-android:1.10.3'
and still getting same error .
How cani use parsestarter?Can u explain

**Comment by sichevoi** [comment]
Hello Parse team!

I've reproduced the issue with the ParseStarterProject, it only happens with proguard minifyEnabled setting (which is off by default in the starter project).
Please find the failing project sample here: https://github.com/sichevoi/Parse-Starter-Project
It's basically the original started project with latest compile SDK and build tools + minify.
Note, that I'm actually getting two errors compiling with the laster SDK:

>Warning:com.parse.NotificationCompat$NotificationCompatImplBase: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification
>Warning:com.parse.ParseApacheHttpClient: can't find referenced method 'org.apache.http.conn.ssl.SSLSocketFactory getHttpSocketFactory(int,android.net.SSLSessionCache)' in library class android.net.SSLCertificateSocketFactory

**Comment by grantland** [comment]
Thanks for the concise repro steps! I've successfully reproduced this issue and have found a solution.

Could you try updating `proguard-rules.pro` with the changes from #234 to see if this resolves your issues?

**Comment by sichevoi** [comment]
Yes, that change resolves the issue. 
It's good, that a description is provided, explaining the usage of the methods in question.
And thanks for a quick response!

**Comment by grantland** [comment]
Great to hear! much happier that the solution was easier than I originally thought :smile:

**Comment by RahulRvR** [comment]
I just tried this. It works for me too.

**Comment by leo-one** [comment]
Is it fixed ?
I am using :
```java
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    useLibrary 'org.apache.http.legacy'

    release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
// ...
}

// ...

compile 'com.facebook.android:facebook-android-sdk:4.10.1'
compile 'com.parse.bolts:bolts-android:1.3.0'
compile 'com.parse:parse-android:1.13.0'
compile 'com.parse:parsefacebookutils-v4-android:1.10.4@aar'
```

and the error below continues when generate release apk using proguard:

```
Warning: com.parse.NotificationCompat$NotificationCompatImplBase: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification
Warning: com.parse.ParseApacheHttpClient: can't find referenced method 'org.apache.http.conn.ssl.SSLSocketFactory getHttpSocketFactory(int,android.net.SSLSessionCache)' in library class android.net.SSLCertificateSocketFactory
```

**Comment by rogerhu** [comment]
setLatestEventInfo() has also been deprecated.

It would have to be something like:
```
      Notification result = b.setContentTitle(b.mContentTitle)
              .setContentText(b.mContentText)
      .setContentIntent(b.mContentIntent).build();

```
