### ISSUE TITLE
Compiled version 23 gives error when generating signed apk

### ISSUE THREAD

**Issue by iampawan** [ParsePlatform/Parse-SDK-Android#232]

**Comment by grantland** [comment]
Could this be a duplicate of #231?

**Comment by iampawan** [comment]
@grantland  yeah exactly

**Comment by iampawan** [comment]
it is the same query as of #231 @grantland @parse-github-bot 
Please fix it .. I have to upload app

**Comment by grantland** [comment]
I'll close this since it's a duplicate. See #231 for workaround for now.
