### ISSUE TITLE
Crash Reports Not Being Displayed in Dashboard

### ISSUE THREAD

**Issue by knappador** [ParsePlatform/Parse-SDK-Android#235]
```
11-06 15:07:33.986    6474-6474/com.onedepth.search.debug D/CrashReporting﹕ Generating report file for crash
11-06 15:07:34.066    6474-6474/com.onedepth.search.debug D/CrashReporting﹕ Retrieving logcat output...
11-06 15:07:34.126    6474-6474/com.onedepth.search.debug D/CrashReporting﹕ Retrieving logcat output...
11-06 15:07:34.156    6474-6474/com.onedepth.search.debug D/CrashReporting﹕ Retrieving logcat output...
11-06 15:07:34.356    6474-6474/com.onedepth.search.debug V/CrashReporting﹕ About to start ReportSenderWorker from #handleException
11-06 15:07:34.356    6474-6701/com.onedepth.search.debug D/CrashReporting﹕ 
#checkAndSendReports - start
11-06 15:07:34.356    6474-6701/com.onedepth.search.debug D/CrashReporting﹕ Looking for error files in /data/data/com.onedepth.search.debug/files/com.parse/cr/reports
11-06 15:07:34.356    6474-6701/com.onedepth.search.debug D/CrashReporting﹕ Loading file 1446790054001-RuntimeException-77.stacktrace
11-06 15:07:34.376    6474-6701/com.onedepth.search.debug I/CrashReporting﹕ Sending file 1446790054001-RuntimeException-77.stacktrace
11-06 15:07:34.376    6474-6701/com.onedepth.search.debug D/CrashReporting﹕ Sending crash report to Parse...
11-06 15:07:34.376    6474-6701/com.onedepth.search.debug D/CrashReporting﹕ 
#checkAndSendReports - finish
```

My package name is included in this report, so someone at Parse has what they need to drill down the issue.  We've done everything we can.  Parse the library is telling us that Parse the backend should have the report.  Where is the crash report?  The world wonders.

**Comment by knappador** [comment]
Okay, I'm closing this on Github.  I can confirm that we're not seeing any client misbehavior, just crickets on the Parse dashboard.

**Comment by wangbourne** [comment]
@knappador i have the same problem with you, have you got it fixed?

**Comment by knappador** [comment]
Liang Wang.  Facebook has a separate bug reporting platform for the backend
issues on Parse.  Go to this link:

https://www.parse.com/help

I gave them all of the same information, including our package name etc.
Parse Crash reports showed up again.  We actually moved on to Crashlytics
for bug reports and I must say it's a more mature platform for bug reports.

**Comment by knappador** [comment]
Be sure to open a new bug as being with the Rest API.  We didn't change
anything in our code.  The crash reports just started showing up again.
I'm assuming they either fixed some invalid data or changed backend code,
but if you still don't have reports, I would assume the cause is some bad
data that has gotten into the DB and won't be fixed by them fixing the
backend bug that causes it in the first place because the bad data might
already be there.
