### ISSUE TITLE
Unit testing code using ParseQuery

### ISSUE THREAD

**Issue by masterjefferson** [ParsePlatform/Parse-SDK-Android#237]
I prefer to run as much testing as possible in the JVM before moving to on-device testing. So far everything has worked nicely except for code that uses queries.

There does not appear to be a way to mock `ParseCurrentUserController` or mock any sort of user behavior. I've seen what needs to be done [here](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/test/java/com/parse/ParseTestUtils.java), but obviously our application code is not at the same package level.  

Are there any plans to improve this?

**Comment by grantland** [comment]
We don't have any plans for this right now as any APIs we make public we're constrained to keep. You are free to access those from the same package, just be aware that the APIs may change.

Another common practice is to wrap any static method functionality with a wrapper object that you can mock the instance of. There's an example of this [here](https://github.com/ParsePlatform/ParseFacebookUtils-Android/blob/master/library/src/main/java/com/parse/FacebookController.java#L175).

**Comment by masterjefferson** [comment]
Thanks for the response and suggestion. I was able to get things working using Robolectric.

[Here's a base class](https://gist.github.com/masterjefferson/f4e899215174e376ef45) if anyone else encounters problems.

**Comment by grantland** [comment]
Awesome, I'll be closing this issue then. Feel free to reopen it if anything else occurs.
