### ISSUE TITLE
Parse usage periodically dropping to zero 

### ISSUE THREAD

**Issue by giladHaimov** [ParsePlatform/Parse-SDK-Android#238]
Hi guys,

For a long time now we have experienced a non linear behaviour of Parse events (see attached image from Analytics).

Our app constantly interact with Parse, and is used by millions worldwide.

Additionally - it does not use any sort of time-of-day-based logic in our client, 

All this brings us to suspect that the graph may indicate non-availability of service at the Parse server end. 

Could you guys check this behaviour and assist us in solving the problem?

Thanks,
Gilad

<img width="960" alt="parse down time" src="https://cloud.githubusercontent.com/assets/7197566/11019431/6c7e4458-8601-11e5-8732-f4ddde44d6b7.png">

**Comment by shaikof** [comment]
I am experiencing the same in my Parse account and thinking of leaving it because of this. Please answer ASAP!!

**Comment by wangmengyan95** [comment]
Hi @giladHaimov @shaikof, we only track SDK issues in this repo. For your case, it sounds like a backend issue to me. We continue to use the FB bug tool to track backend issues, where you can confidentially submit information about the exact app that you are having issues on. Could you file an issue there? https://www.parse.com/help? Thanks.
