### ISSUE TITLE
Quick Start Documentation

### ISSUE THREAD

**Issue by justdan0227** [ParsePlatform/Parse-SDK-Android#246]
Missing how you add the jar to your android project.  

"Add ParseFacebookUtilsV4.jar to your Android project."  You don't say how to do that.  In a quick start guide I would expect steps.

**Comment by wangmengyan95** [comment]
Hi @justdan0227, could you paste the link of the documentation, thanks.

**Comment by justdan0227** [comment]
Sure ... https://www.parse.com/docs/android/guide#users-facebook-users  halfway down, step 4 where it says 

Setup

To start using Facebook with Parse, you need to:

**Comment by wangmengyan95** [comment]
Hi @justdan0227, I just update the doc. Thanks.

**Comment by justdan0227** [comment]
Awesome!!!! Thanks!
