### ISSUE TITLE
Parse Dashboard not showing same data as Mixpanel

### ISSUE THREAD

**Issue by abhinav-koppula** [ParsePlatform/Parse-SDK-Android#252]
We have setup Mixpanel events to get fired when a push notification is received and when a push notification is opened.
Mixpanel Push Open data and Parse Push Open data are tallying exactly with only one problem - The Parse dashboard shows x date's data in x-1.
![screenshot from 2015-11-17 14 07 24](https://cloud.githubusercontent.com/assets/3524245/11206355/93ae37b0-8d34-11e5-89cf-7a742685cf1e.png)
![screenshot from 2015-11-17 14 07 58](https://cloud.githubusercontent.com/assets/3524245/11206467/50d1ffd4-8d35-11e5-8924-c810efaaf4bc.png)
As we can see, mixpanel data of 16th Nov is shown on Parse for 15th Nov. 
- Please confirm that this is either an issue in the parse dashboard (dates not showing correctly) or please suggest if we have to make any changes in the timezone etc in the settings of Parse.

We have a major issue in the push received event shown by Parse and by Mixpanel.
Parse dashboard data:
![screenshot from 2015-11-17 14 15 02](https://cloud.githubusercontent.com/assets/3524245/11206512/a0e2dc82-8d35-11e5-8ea4-6064b6694c67.png)
![screenshot from 2015-11-17 14 15 05](https://cloud.githubusercontent.com/assets/3524245/11206515/a7ef7e7c-8d35-11e5-91fe-7ffd61592da8.png)
Mixpanel dashboard data:
![screenshot from 2015-11-17 14 13 59](https://cloud.githubusercontent.com/assets/3524245/11206528/b9b0bc48-8d35-11e5-91a6-c992fa9a8ce2.png)
![screenshot from 2015-11-17 14 14 03](https://cloud.githubusercontent.com/assets/3524245/11206532/c185f8c0-8d35-11e5-9361-c37e9dd330dc.png)

Can you please help us out in understanding what should be the correct way of measuring these funnels?

**Comment by wangmengyan95** [comment]
Hi @abhinav-koppula , we only track SDK issues in this repo. For your case, it sounds like a backend or dashboard issue to me. We continue to use the FB bug tool to track these issues, where you can confidentially submit information about the exact app that you are having issues on. Could you file an issue there? https://www.parse.com/help? Thanks.
