### ISSUE TITLE
Raw data for sent/opened push notifications

### ISSUE THREAD

**Issue by abhinav-koppula** [ParsePlatform/Parse-SDK-Android#253]
Can we get the raw data(csv, json) for all the push notifications which have been sent successfully from Parse or have been tracked as opened on Parse ?

**Comment by wangmengyan95** [comment]
You can subclass `ParsePushBoradcastReceiver` and overwrite `onPusheReceive`. Then you can get the raw json from the `intent`. You can check our [tutorial](https://parse.com/docs/android/guide#push-notifications-receiving-pushes) and the source code of `ParsePushBroadcastReceiver` [source code](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParsePushBroadcastReceiver.java#L138).

**Comment by abhinav-koppula** [comment]
Hi @wangmengyan95 , I think you misunderstood my question. I want a report of all the push notifications which have been successfully sent via parse. 
For example, I am sending 1000 pushes to different users using the Parse REST Api but there is no way to check which users received the push notification except from the Parse Push notification dashboard.
Request 1 -> send a notification to a user with "xyz" message where the uuid of user is "abc"(uuid of user1 is stored in the parse installation object)
Request 2 -> send a notification to a user with "wbc" message where the uuid of user is "def"(uuid of user2 is stored in the parse installation object)
...

Thus 1000 such requests are made to Parse. I would want to check how many users are receiving notifications on a daily basis and of those how many users opened them.

**Comment by grantland** [comment]
Unfortunately this issue still isn't relevant to this repository. A better place would be opening a ticket at http://parse.com/help.
