### ISSUE TITLE
Unable to receive push notification on Android

### ISSUE THREAD

**Issue by thomasdao** [ParsePlatform/Parse-SDK-Android#254]
Hi,

My app KigoStaging recently is unable to receive push notification, even though I upgraded to latest SDK 1.11.0. I have tried deleting the app and reinstall many times. Below is my code:

```java
private void subscribePushNotification() {
        // Subscribe to my own channel
        // Save the current Installation to Parse.
        ParseInstallation.getCurrentInstallation().saveInBackground(new SaveCallback() {
            @Override
            public void done(ParseException e) {
                if (e != null) {
                    e.printStackTrace();
                    return;
                }

                final String channel = "user_" + ParseUser.getCurrentUser().getObjectId();
                ParsePush.subscribeInBackground(channel, new SaveCallback() {
                    @Override
                    public void done(ParseException e) {
                        LogHelper.log("Subscribed to channel " + channel);
                        if (e != null) {
                            e.printStackTrace();
                        }
                    }
                });
            }
        });
    }
```

This works fine, and I am able to see the log `Subscribed to channel user_WHPNfPYMYN`. I also see the device is registered into the database.

My AndroidManifest.xml is as below (strip unnecessary content):

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="me.keygo" >

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

    <permission
        android:name="me.keygo.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />

    <uses-permission android:name="me.keygo.permission.C2D_MESSAGE" />

    <application
        android:name=".app.App"
        android:allowBackup="false"
        android:icon="@drawable/app_icon"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:theme="@style/AppTheme"
        tools:replace="android:icon, android:allowBackup" >

        <service android:name="com.parse.PushService" />

        <receiver
            android:name="com.parse.GcmBroadcastReceiver"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />

                <category android:name="me.keygo" />
            </intent-filter>
        </receiver>
        <receiver
            android:name=".receiver.KeygoParsePushReceiver"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>
    </application>

</manifest>
```

I have created many test push notification but does not see any of them. Some of the push ID is ncOJ8p0iSJ, fkdUxSZ5vW, 2yM0VON6sX

Please let me know anything I can do to fix this issue, thanks

**Comment by tgamez** [comment]
I also have this issue. Inconsistent Notification delivery to two devices that we use for testing.

Here are a Push notification that have been received by one device and not the rest,

https://www.parse.com/apps/masterapp/push_notifications/ZyJ6NOJu6o

And following another push to the same devices that It haven't been received by any device:

https://www.parse.com/apps/masterapp/push_notifications/YSceXmTHno

Thanks,

**Comment by wangmengyan95** [comment]
Hi @thomasdao:
`Manifest.xml` and your code look good to me. In your case, could you provide some additional information to us
1. Logcat output of the device in question launching the application. You can do this via `Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE)`
2. Could you open the data dashboard and check whether the deviceToken column of the ParseInstallation has value or not.
Thanks.

**Comment by thomasdao** [comment]
Hi @wangmengyan95 

Thanks for reply. I have enabled LOG_LEVEL_VERBOSE and the log is as below:

```
V/com.parse.ParseHttpClient: Using net.java.URLConnection library for networking communication.
V/com.parse.ManifestInfo: Using gcm for push.
V/InstallationId: Couldn't find existing installationId file. Creating one instead.
V/com.parse.GcmRegistrar: Sending GCM registration intent
```

In the _Installation table, the deviceToken exists, you can see it in the screenshot https://dl.dropboxusercontent.com/u/52035303/installation.png

Please let me know if you need more info, thanks

**Comment by wangmengyan95** [comment]
Hi @thomasdao, what our client SDK does for the push is trying to create the ParseInstllation, talking to GCM(google cloud message) to get the deviceToken, then waiting for the push notification from GCM. It seems the first and second steps are fine for you. So what you can do now is 
1. I see you use your custom ParsePushReceiver, can you verify whether the `onPushReceive` function has ever been triggered?
2. Can you check the delivery report in our website to see whether it has been successfully delivered?

**Comment by thomasdao** [comment]
Hi, the first step is never triggered and as in my first report the notification is not delivered to my android app, the number of deliveries is always 0. I suspect Parse does not send notifications to GCM yet

**Comment by wangmengyan95** [comment]
Hi @thomasdao, since we check every piece client SDK should do, then it sounds like a backend issue to me. We continue to use the FB bug tool to track these issues, where you can confidentially submit information about the exact app that you are having issues on. Could you file an issue there? https://www.parse.com/help? Thanks.

**Comment by thomasdao** [comment]
Sure I will do that, thanks

**Comment by thomasdao** [comment]
New bug report is created at https://developers.facebook.com/bugs/531379753692118/, it seems like a lot of people have problem with push notification but no clear solution has been identified yet. Thanks for helping here, I will close the issue for now
