### ISSUE TITLE
Errors when searching in Array and location

### ISSUE THREAD

**Issue by icardenasr** [ParsePlatform/Parse-SDK-Android#256]
Hi.

I'm using Parse.com for an Android app, with de Android SDK.

I'm having problems when trying to query objects based in "whereContainsAll" over an Array, and "whereWithinKilometers" over a Location.

I have 2 objects with class "Menu" with an Array field named "ingredients" with values: ["test", "object1"] and ["test", "object2"] , and a field named "location" with type GeoPoint, both with same value (28.1055674, -15.4168011).

Then I'm doing this query, and I only get 1 result:
```java
ParseQuery<ParseObject> query = ParseQuery.getQuery("Menu");
String[] ingredientsArray = searchDescription.split(" ");  // searchDescription is only "test"
ArrayList<String> ingredientsList = new ArrayList<String>(Arrays.asList(ingredientsArray));  //ingredientsList is only [test]
query.whereContainsAll("ingredients", ingredientsList);
query.whereWithinKilometers("location", centerGeoPoint, searchRadius);   // centerGeoPoint is a GeoPoint with user location, searchRadius is 5 km
query.findInBackground(new FindCallback<ParseObject>() {
    @Override
    public void done(List<ParseObject> dishes, ParseException arg1) {
        // here "dishes" only included 1 object "Menu"
    }
});
```
If a remove the "location" restriction, I get both 2 results:
```java
ParseQuery<ParseObject> query = ParseQuery.getQuery("Menu");
String[] ingredientsArray = searchDescription.split(" ");  // searchDescription is only "test"
ArrayList<String> ingredientsList = new ArrayList<String>(Arrays.asList(ingredientsArray));  //ingredientsList is only [test]
query.whereContainsAll("ingredients", ingredientsList);
query.findInBackground(new FindCallback<ParseObject>() {
    @Override
    public void done(List<ParseObject> dishes, ParseException arg1) {
        // here "dishes" only included 1 object "Menu"
    }
});
```
Both objects have same "location" values, I have checked it. If a work with both objects, they include the "location" field with GeoPoint type and exactly the same value, and I can work with this value without problems.

I think there is a problem using "whereContainsAll" and "whereWithinKilometers" in the same query. It does not return all available and possible results.

**Comment by wangmengyan95** [comment]
Hi @icardenasr, I test with some similar cases and I can not repo the issue. Since all the query matching and processing are done in our backend, for your case, it sounds like a backend or dashboard issue to me. We continue to use the FB bug tool to track these issues, where you can confidentially submit information about the exact app that you are having issues on. Could you file an issue there? https://www.parse.com/help? Thanks.

**Comment by icardenasr** [comment]
Hi.

I will try to open the issue in FB bug tool, but it does not give the
chance to choose "Backend". I will use API REST.

In any case, is there any time or process limitation in every query?
I have seen the query is correct when I remove the "whereWithinKilometers"
expression in the query, or the number of items in Array where I search
with "whereContainsAll" is low. In these cases, the query returns all the
correct results.
But if the Array has too any items (about 100), and I make a query
with "whereWithinKilometers"
and "whereContainsAll", it does not return all the correct results. Only a
few of them.
Then, are the queries time or process limited?

Thanks!









2015-11-19 23:40 GMT+01:00 Mengyan Wang <notifications@github.com>:

**Comment by wangmengyan95** [comment]
Hi @icardenasr, we do have a time limitation, it is around 30 second and if you reach that limitation, you will receive an exception, not partial results. So I do not think it fits for your case. I will close this issue for now, feel free to reopen it if you think it is actually a SDK issue.
