### ISSUE TITLE
Android devices not receive Push GCM notifications

### ISSUE THREAD

**Issue by tgamez** [ParsePlatform/Parse-SDK-Android#257]
Hi,

We are unable to receive Push notifications on a correct registered devices with type GCM.
We have tried several times with differents devices and we have seen only from time to time a device that receive well notifications.

The most interesting test is one where the same device has received the first notification and none of the followings notifications. All with the same App installation, "akG0OqVfQE",  with no further manipulation.

The Pushes are:

Received and notified in Parse info:
----------------------------------------
https://www.parse.com/apps/masterapp/push_notifications/Lksscslw0n 

Not received:
----------------
https://www.parse.com/apps/masterapp/push_notifications/IU8iCOluXR 
https://www.parse.com/apps/masterapp/push_notifications/IVGV6vV699
https://www.parse.com/apps/masterapp/push_notifications/DJd0mn7GGb

May be is related with the other issue: 
https://github.com/ParsePlatform/Parse-SDK-Android/issues/254

build.gradle:

    compile ('com.facebook.android:facebook-android-sdk:4.5.0') {
        // To avoid conflicts with bolts-tasks from parse
        exclude module: 'bolts-android'
    }
    compile 'com.google.android.gms:play-services-maps:8.3.0'
    compile 'com.google.android.gms:play-services-location:8.3.0'
    compile 'com.google.android.gms:play-services-plus:8.3.0'
    compile 'com.google.android.gms:play-services-gcm:8.3.0'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    // Now gradle is resolving parse-android dependencies and add: bolts-tasks-1.3.0
    // compile 'com.parse.bolts:bolts-android:1.2.1'
    compile 'com.parse:parse-android:1.11.0'

This is the AndroidManifest declaration:

<application>

      <service android:name="com.parse.PushService" />
        <receiver android:exported="false" android:name="com.parse.ParsePushBroadcastReceiver">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.parse.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" android:priority="470" />

                <category android:name="com.spotlio.spotliomaster" />
            </intent-filter>
        </receiver>
   </application>

We are really lost with this issue.
Thanks,

**Comment by tgamez** [comment]
Solved:

It was a problem because using together our own Push Service without following Parse instructions for that.

As explained here: 

https://github.com/ParsePlatform/Parse-SDK-Android/issues/153

Instructions on how to use: 

https://github.com/ParsePlatform/Parse-SDK-Android/issues/39#issuecomment-133077876

Sorry for any inconvenience,

Thanks

**Comment by rosatof** [comment]
@tgamez Can you provide a working snippet of your implementation?
