### ISSUE TITLE
There are empty deviceToken in core panel

### ISSUE THREAD

**Issue by ThanawatMas** [ParsePlatform/Parse-SDK-Android#259]
I have been updated Parse version from 1.9.2 to 1.10.3 and found the problem 
that many new installed app's devices 
haven't
- deviceToken Id
- pushType.

I do follow instruction of help 
https://www.parse.com/tutorials/android-push-notifications
and
https://parse.com/docs/android/guide#push-notifications-troubleshooting
```java
push.sendPushInBackground(new SendCallback() {
  public void done(ParseException e) {
    if (e == null) {
      Log.d("push", "The push campaign has been created.");
    } else {
      Log.d("push", "Error sending push:" + e.getMessage());
    }
  }
});
```

The log shows 
>"The push campaign has been created.". 

Anyway I version of jar from 1.10.3 to 1.11.0 ; it still not work.

How could I do to solve this problem?

**Comment by wangmengyan95** [comment]
Hi @ThanawatMas, normally, the pushType is empty means something wrong in your `AndroidManifest` and we can not decide wether to use gcm or ppns to send push notifications to your device. Could you paste the logcat output of the device when you launch the application. You can do this via `Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE)`.

**Comment by ThanawatMas** [comment]
I found what it failed, that is I forgot to declare internet permission in AndroidManifest.xml file, 
so thank you for pointing me and figure out what the root cause problem.
