### ISSUE TITLE
Under certain conditions, a query that should return some results returns empty list.

### ISSUE THREAD

**Issue by noughts** [ParsePlatform/Parse-SDK-Android#26]
Frequency: 100%

Environment:
Android 4.1.1
Parse SDK 1.10.0

When setting query's include() to a certain condition, ParseObject.saveAll() fails, and the query doesn't function properly after restarting the app.

Below is the repro code with Parse Starter Project.
https://dl.dropboxusercontent.com/u/309225/androidIssue14.zip

I commented out the lines causing the problem, so when running it straight, a Feed object is created to Parse, then a query fetches it with 1 result, flag it as "read" and save to Parse. Then the same should happen when running it again. This is the expected behavior.

Then, when uncommenting the line 94 in MainActivity.java and running, an error "object not found for update" occurs upon saving the "read" flag to Parse.
Then, when running it again, very weirdly, the query's results becomes 0. 
This doesn't change after re-running repeatedly, but when deleting the app and running it again, the same error code happens with 1 result.

The server side is clean, haven't set up CloudCode nor any Class Level Permissions.

I've reported before a problem with pin ( https://developers.facebook.com/bugs/901559459903544/ ), and I thought I could go forward now that it's finally fixed, but now stopped by this error.

Thanks in advance for your advice.

**Comment by grantland** [comment]
This was actually fixed by #3 and released in [1.10.1](https://github.com/ParsePlatform/Parse-SDK-Android/releases/tag/1.10.1).

Verified working with supplied project.

**Comment by noughts** [comment]
It works in with 1.10.1!
Thanks!

**Comment by grantland** [comment]
Great to hear :smile:
