### ISSUE TITLE
ParseAnonymousUtils, add API for custom UUID

### ISSUE THREAD

**Issue by letzgame** [ParsePlatform/Parse-SDK-Android#263]
As currently, Anonymous login use built-in UUID, and reinstalled app will lost all data.
We hope to use the open UUID for anonymous login, so that we can keep the old data.
It would be better to add an API like LoginBackground(string customUUID).

**Comment by letzgame** [comment]
@wangmengyan95 
any schedule for this feature?

**Comment by grantland** [comment]
This is actually working as expected. The use case for anonymous users is to reduce the friction for users to start using your application initially by not requiring them to sign up, but if they wish to have their data persisted across app installs and devices they should be expected to "sign up".

**Comment by letzgame** [comment]
But I know that if I use the rest API to anonymous login, I have to supply a UUID by self. 
I think it should give an option to use custom UUID in SDK  with the same as REST api.

**Comment by grantland** [comment]
Re-authenticating anonymous users this ways is not recommended nor do we guarantee that it will continue to work this way in the future.
