### ISSUE TITLE
In app purchase or in app billing support

### ISSUE THREAD

**Issue by doozMen** [ParsePlatform/Parse-SDK-Android#264]
I am evaluating the for a large book selling company. I could find grate documentation about in app purchase for iOS but as it seams support for something similar on Android is limited?

I found out that there is a problem with:
* receipt verification : http://stackoverflow.com/questions/26653270/parse-com-cloud-code-rsa-verification-android-in-app-purchase-verification/31435777#31435777
* Unclear if it is fully supported. I could only find error codes  **Purchase related errors** that hint to the existence like something PFPurchase:

Is it so that we can use the PFProduct that is created for iOS also on Android but that we have to do the receipt validation our self?

**Comment by wangmengyan95** [comment]
Hi @doozMen, unlike iOS, in-app purchase is a functionality of Google play service or other platform service, not Android system, so it is not available on all Android devices. It is not easy to find a universal solution for this so we do not have the plan to support this on Android.

**Comment by doozMen** [comment]
@wangmengyan95  thanks this clarifies a lot!
