### ISSUE TITLE
Push notification does not work only in Android 4

### ISSUE THREAD

**Issue by kamoljan** [ParsePlatform/Parse-SDK-Android#265]
**Android 4 devices:**
Samsung S4, 4.4.2
Samsung Grand II, 4.4.2
Red mi, 4.4.4
Samsung Grand neo, 4.4.4
HTC Desire, 4.4.2
HTC One, 4.4.2

PUSH ID
W1ykLqqkgq

TARGETING
channels is "push-oOt2R7gQky"
SENDING TIME
November 23rd, 2015 at 3:36 PM

EXPIRATION
None

FULL TARGET
{ 
  "channels": "push-oOt2R7gQky" 
}

FULL DATA
{ 
  "alert": "Mudah Mudah: Hey", 
  "badge": "Increment", 
  "chatInfo": { 
    "channel": "fG5WZ1dtHr-oOt2R7gQky-XOuiFuJfCV", 
    "displayName": "Mudah Mudah", 
    "lastMessage": "Hey" 
  }, 
  "sound": "default" 
}

Installation table's
objectId:cifZbg9qRU of . 
deviceToken:
APA91bHWj3PDPyaAayibAe_ZTTsegm5RQKca8PmEeQkee0m4golw_fpeLqGn29k5T5DVgwF8ZL2GrjWy4Szz3vc9WPMQAxhUmPKr0zXQBD7poUgCWSoeeqEC8_e2OGlBkr49Mo9c96FS
channel:["","apptentive","push-oOt2R7gQky"]

Cloud Code:

    var pushNotification = function (channel, chatInfo, response) {
        var pushQuery = new Parse.Query(Parse.Installation);
        pushQuery.equalTo('channels', "push-" + channel);
        Parse.Push.send({
            where: pushQuery,
            data: {
                "alert": chatInfo.displayName + ": " + chatInfo.lastMessage.substr(0, 30),
                "badge": "Increment",  // iOS only
                "sound": "default",  // iOS only
                "chatInfo": chatInfo
            }
        }, {
            success: function () {
                // Push was successful
            },
            error: function (error) {
                throw "Got an error " + error.code + " : " + error.message;
            }
        });
    };

**Comment by wangmengyan95** [comment]
Hi @kamoljan, do you mean the push does not work on all listed devices or some of them. Have you tested your code in a standard emulator?

**Comment by kamoljan** [comment]
@wangmengyan95 correct.
The push does not work only on all these devices (Android 4):
Samsung S4, 4.4.2
Samsung Grand II, 4.4.2
Red mi, 4.4.4
Samsung Grand neo, 4.4.4
HTC Desire, 4.4.2
HTC One, 4.4.2

**Comment by wangmengyan95** [comment]
Hi @kamoljan, I do not have all the devices. But I test push notification in my Samsung S4, 4.4.2, it works fine. So I want to know could you repo this issue in a standard Android 4.4 emulator?

**Comment by kamoljan** [comment]
@wangmengyan95  strange it was related to SenderID (Mixpanel) issue with GCM.
Going to close this issue. Thank you for your help.

**Comment by ramjoshi210589** [comment]
@kamoljan I understand this is long since this ticket get closed, however we are using mixpanel for one of our project, and facing similar issue, where push notification do not work for samsung device, and all good with Nexus devices.

Can you please share your solution, that can help us to resolve the issue.

Regards
Ram
