### ISSUE TITLE
logInInBakcground leaves invalid login parameters

### ISSUE THREAD

**Issue by jas10022** [ParsePlatform/Parse-SDK-Android#268]
i have been trying to create a simple login feature to my app and it keeps giving me invalid login parameters. this is my code:

package edu.self.ludus;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;

import com.parse.LogInCallback;
import com.parse.ParseException;
import com.parse.ParseUser;

import java.util.List;

public class LoginPage extends AppCompatActivity {

    private EditText mPasswordInput;
    private EditText mUsernameInput;
    private String mPassword;
    private String mUsername;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login_page);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        mPasswordInput = (EditText) findViewById(R.id.password_input);
        mUsernameInput = (EditText) findViewById(R.id.email_input);
        final Button loginButton = (Button) findViewById(R.id.login);
        Button forgotPasswordButton = (Button) findViewById(R.id.forgot_password);

        mPassword = mPasswordInput.getText().toString();
        mUsername = mUsernameInput.getText().toString();

        loginButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                ParseUser.logInInBackground(mUsername, mPassword, new LogInCallback() {
                    @Override
                    public void done(ParseUser user, ParseException e) {
                        if (user != null ){
                            Log.d("LoginPage","it was a succes");
                        }else{
                            Log.d("LoginPage","error is "+e);
                        }
                    }
                });

            }

        });
    }
}

**Comment by wangmengyan95** [comment]
Hi @jas10022, since we do not have the full context of your app, it is a little bit hard for us to tell you where the issue is. Could you try to use our REST api to see whether you still have this issue?
