### ISSUE TITLE
Parse query from local datastore is dead slow on android

### ISSUE THREAD

**Issue by aivknowtech** [ParsePlatform/Parse-SDK-Android#273]
Hi I am working on Andorid
I am  trying to query from local data store and it takes more than 30 seconds to query from the table. Even i dont specify any search statement with "where" function still it takes the same time. This is happening for the first time (after opening the application)  then subsequent searches takes from 2-3 seconds. Where as the query from network is way faster than this. This particular table consists of almost 2500 rows locally. Can you please suggest a reason for this ? This is breaking the entire parse integration for my application. So I feel like needs to implement local sqlite db on top of parse to handle this.  If I am implementing parse query adapter , will the behavior change ?
Looking for responses.  Also I have seen that doing anything on parsequery is putting android cpu usage near 70%90%, is that normal ?

**Comment by grantland** [comment]
See #279
