### ISSUE TITLE
Push notifications not delivered to android devices

### ISSUE THREAD

**Issue by dialb4bhas** [ParsePlatform/Parse-SDK-Android#274]
Hey Guys, 

We have been having issues receiving push notifications on android devices.. 

It works ok on iOS apps though..

The issue is happening when triggered via a REST API from an external source or even when issuing a Push Notification directly from Parse.com

Can this be addressed at the earliest please?

These are the details.. 

PUSH ID
9PeEW2RIlj

TARGETING
channels contains "BreakingNews"
deviceType is either "ios" or "android"
SENDING TIME
November 30th, 2015 at 10:58 AM

Before sending the push notification, it displays 
"This will be sent to 43 devices"

But it had only sent 28. Not sure if that makes a difference.

**Comment by kamoljan** [comment]
@dialb4bhas there is some issue with Android GCM. 
If you are using Mixpanel or other services that require a registration their SenderID with GCM
then it can cause this problem.

Try to rid off other services Frist and let only Parse to be registered its SenderID with GCM.
Check if SenderID is correct and also check if your _Installation table is recieving a deviceToken.

Good luck!
