### ISSUE TITLE
DumpApp and ParseStethoInterceptor conflict

### ISSUE THREAD

**Issue by jmfayard** [ParsePlatform/Parse-SDK-Android#275]
Hello, I opened an issue https://github.com/ParsePlatform/Parse-SDK-Android/issues/226 where I had suddenly deleting Parse Objects not working. 

Sorry for the 1 month delay, but I now have a sample project that reproduce the bug

https://github.com/jmfayard/ParseStetho

So with the configuration `Stetho.initializeWithDefaults(this);`, ParseStethoInterceptor is working
But if I initialize Stetho with a DumpApp, deleting an object don't work anymore

**Comment by wangmengyan95** [comment]
Hi @jmfayard, for Stetho, right now we only officially support the Network Inspection feature. I will take a look at this issue. At the same time, it would be great if you can figure out the problem and send a PR back to Parse :smile: .
