### ISSUE TITLE
Installation is not created on Nexus 5 Android 6.0

### ISSUE THREAD

**Issue by kaojohnny** [ParsePlatform/Parse-SDK-Android#277]
I noticed the `Installation` object is not created and saved on Nexus 5 Android 6.0. I got following error:

```
System.err: com.parse.ParseRequest$ParseRequestException: object not found for update
System.err:     at com.parse.ParseRequest.newPermanentException(ParseRequest.java:269)
System.err:     at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:288)
System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:136)
System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:132)
System.err:     at bolts.Task$15.run(Task.java:839)
System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
System.err:     at bolts.Task.completeAfterTask(Task.java:830)
System.err:     at bolts.Task.continueWithTask(Task.java:642)
System.err:     at bolts.Task.continueWithTask(Task.java:653)
System.err:     at bolts.Task$13.then(Task.java:745)
System.err:     at bolts.Task$13.then(Task.java:733)
System.err:     at bolts.Task$15.run(Task.java:839)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
System.err:     at java.lang.Thread.run(Thread.java:818)
```

My SDK version is v1.11.0. And I found no problem on Genymotion Nexus 5 5.1.0, and Genymotion Nexus 5x 6.0.0.

**Comment by wangmengyan95** [comment]
Hi @kaojohnny, the exception means you try to update a nonexistent installation. We store current installation in the device disk for fast access. When you change your current installation(like subscribe to a channel or change some fields), we actually send an update request to Parse if you have installation stored in the device disk. The exception you get means the current installation in the device disk can not match any installation in Parse. It seems it is not related to installation creation. So could you uninstall the app or clear the cache data of the app and try again to see what happens?

**Comment by kaojohnny** [comment]
Hi @wangmengyan95 thanks a lot. After clear cache data, the installation object is created/updated successfully. Though uninstall app doesn't work for me. Thanks!

**Comment by wangmengyan95** [comment]
@kaojohnny glad it helps. I will close this issue.

**Comment by alexblack** [comment]
resetting the installation might do it:

http://stackoverflow.com/questions/31890049/parse-push-notifications-how-to-reset-installation-data

**Comment by MarsVard** [comment]
@alexblack  those classes are private in the latest android sdk :( is there a way around?

**Comment by alexblack** [comment]
@MarsVard that code from SO works for me. The insight is to put the code in the `com.parse` package
