### ISSUE TITLE
Synchronizing locally stored data with saveEventually is broken

### ISSUE THREAD

**Issue by tilowestermann** [ParsePlatform/Parse-SDK-Android#287]
I'm using Parse with localDatastore enabled:

    ParseObject.registerSubclass(MyClass.class);
    Parse.enableLocalDatastore(context);
    Parse.initialize(...);

As I'm not assuming that network is available at all times, I save new data locally first and then try save them to the cloud:

    
    entry.pinInBackground(new SaveCallback() {
        @Override
        public void done(ParseException e) {
            if (e == null) {
                entry.saveEventually();
            } else {
                e.printStackTrace();
            }
        }
    });

However, `entry` is never saved over the network (I also used saveEventually with a SaveCallback in order to get any errors, but the callback is never executed).

I found related but fairly old posts here: https://parse.com/questions/how-do-i-store-parseobject-in-both-local-datastore-and-parse-cloud & http://stackoverflow.com/questions/26057699
Using the approach presented in the OfflineTodos example (https://github.com/ParsePlatform/OfflineTodos/blob/master/android/src/com/parse/offlinetodos/TodoListActivity.java) using `pinInBackground` & `saveInBackground` works as expected.

Is this a known bug, or intended behavior (which I don't assume)?

**Comment by grantland** [comment]
This should work, could you provide a sample project that repros this issue?
