### ISSUE TITLE
LoginInBackground: Attempt to invoke virtual method 'com.parse.ParseHttpClient com.parse.ParsePlugins.restClient()' on a null object 

### ISSUE THREAD

**Issue by thomasbeerten** [ParsePlatform/Parse-SDK-Android#288]
When doing logInInBackground, I get this error:

Process: com.thomascbeerten.cloudscreenwriter, PID: 10189
                                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'com.parse.ParseHttpClient com.parse.ParsePlugins.restClient()' on a null object reference

In my MyApplication (and I have set it in my Manifest):

        ParseObject.registerSubclass(MyClass.class);
        Parse.enableLocalDatastore(this);
        Parse.initialize(this, "key", "key");

Moreover: it doesn't always happen..

A related stackoverflow thread:
http://stackoverflow.com/questions/33043336/parse-throwing-nullpointerexception-for-logininbackground

**Comment by wangmengyan95** [comment]
Hi @thomasbeerten, could you tell us
1. Your test environment
2. The logcat output of the device when you see the exception. You can do this via Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE).
Thanks.

**Comment by thomasbeerten** [comment]
Hi, instead of using the compile parse...1.+ version, I replaced with the specific version,after that I didn't get the error, so I can't reproduce...

Date: Mon, 14 Dec 2015 10:37:26 -0800

**Comment by grantland** [comment]
Awesome to hear that your problem has been resolved! I'll be closing this issue.
