### ISSUE TITLE
Image not get uploaded to Parse!

### ISSUE THREAD

**Issue by rakhtsavelives** [ParsePlatform/Parse-SDK-Android#289]
My app has one sign up form which takes images form user gallery (Picked By User) and resize it in needed size. After it upload image with other details to Parse. On some devices the upload of image never finishes. It continues in loop of 1% to 100% then again start from 100% (If file is big other wise 100% each time directly). I found this out by using ProgressCallBack().
![capture2](https://cloud.githubusercontent.com/assets/16163088/11743797/6dda0618-a030-11e5-9d12-31b350b594a6.PNG)
![capture](https://cloud.githubusercontent.com/assets/16163088/11743796/6db6df44-a030-11e5-8c1a-02aeef856da2.PNG)

**Comment by wangmengyan95** [comment]
Hi @rakhtsavelives, I am sorry but I do not understand your problem. You questions are why upload never finishes or why some upload always start from 100%? Since it is a little bit complicated scenario, probably you can include some repo steps with what is your expected behaviour and what is the real behaviour. Thanks.

**Comment by rakhtsavelives** [comment]
The Problem is some time image upload doesn't complete. It runs again and
again in loop.

**Comment by wangmengyan95** [comment]
Hi @rakhtsavelives, what you mean again and again in loop is ProgressCallBack get called multiple times  and each time with progress 100%?

**Comment by rakhtsavelives** [comment]
Yes

**Comment by rakhtsavelives** [comment]
Yes progress callback called multiple times each time starting from 0 to
100 then repeat

**Comment by grantland** [comment]
Could you describe the issue a bit more in depth so that we could try to attempt this such as device make and model, Android version, network conditions, etc.? We're unable to reproduce this using the Android emulator.

**Comment by rakhtsavelives** [comment]
It happens in lollipop os most of times but no specific model because
sometimes image gets uploaded on the same device and sometimes not

**Comment by mchun** [comment]
I guess I am facing the same issue, using parse android sdks 1.9.1.
I didn't use the ProgressCallBack to check, but the completion callback is just never get called, bit even throwing a timeout exception. Things occurred ramdomly, mainly by my users. But they can upload the image using javascript sdk. So I guess it is not the network problem.

**Comment by grantland** [comment]
Could either of you provide a sample project and environment description so that we could reproduce this?

**Comment by mchun** [comment]
I guess neither rakhtsavelives nor I can reproduce the issue. We just observed there are random cases like that.

**Comment by rakhtsavelives** [comment]
we have removed the image part from our app
