### ISSUE TITLE
Notification not receive Notification on Android 6.0 Marshmallow 

### ISSUE THREAD

**Issue by coensy** [ParsePlatform/Parse-SDK-Android#291]
Basicly my problem: I can send Notification, but cannot receive any notification on Marshmallow.
My application, working properly under 6.0 android version.
Can anyone helpme how can solve it.

Note: I'm using Parse '1.10.1'  version.

Best Regards. 

manifest:.
.
<uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
    <uses-permission android:name="android.hardware.camera"/>
    <uses-permission android:name="android.hardware.camera.autofocus"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.MANAGE_DOCUMENTS"/>

    <permission
        android:name="<my aplication>.permission.C2D_MESSAGE"
        android:protectionLevel="signature"/>

    <uses-permission android:name="<my aplication>.permission.C2D_MESSAGE"/>

<application ...
... Activities... and others.. things ...

<service android:name="com.parse.PushService"/>

        <receiver android:name="com.parse.ParseBroadcastReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.USER_PRESENT"/>
            </intent-filter>
        </receiver>
        <receiver
            android:name="<my custom 'ParsePushBroadcastReceiver' class>"
            android:exported="false">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE"/>
                <action android:name="com.parse.push.intent.DELETE"/>
                <action android:name="com.parse.push.intent.OPEN"/>
            </intent-filter>
        </receiver>
        <receiver
            android:name="com.parse.GcmBroadcastReceiver"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>

                <category android:name="<my application>"/>
            </intent-filter>
        </receiver>

**Comment by wangmengyan95** [comment]
Hi @coensy , thanks for opening this issue. For your case, could you provide us with the following information:
1. You test environment, emulator or a actual device.
2. Enable logging in our SDK with `Parse.setLogLevel(Log.VERBOSE)` and paste the logcat.

Thanks
