### ISSUE TITLE
findAllInBackground & fetchAllInBackground (Bug?)

### ISSUE THREAD

**Issue by k0shk0sh** [ParsePlatform/Parse-SDK-Android#294]
i'm having an issue that soon enough going to blow me.

i have `Database` table lets call it `A`. ``table A`` has field that determines if this row is processed or no. i update the field myself from within the Parse Browser to either True | False, and trying to call ``query.findInBackground()`` to check with the Boolean value however the returned List always returns False if its True and vice versa. enough talking let me show you what i'm doing.

    public static void getMyRequests(ParseUser user, final FindCallback<ServicesModel> callback) {
        ParseQuery<ServicesModel> query = new ParseQuery<>(ServicesModel.class);
        if (!user.getBoolean(ParseHelper.CAN_UPLOAD)) {
            query.whereEqualTo("user", user);
        }
        query.findInBackground(new FindCallback<ServicesModel>() {
            @Override public void done(final List<ServicesModel> objects, ParseException e) {
                if (e == null) {
                    if (objects != null && !objects.isEmpty()) {
                        for (ServicesModel object : objects) {
                            object.setHandlerUser(object.getParseUser("handlerUser"));
                            object.setProcessedTime(object.getLong("processedTime"));
                            object.setCategoryType(object.getString("categoryType"));
                            object.setUser(object.getParseUser("user"));
                            object.setUserRequest(object.getString("userRequest"));
                            object.setImageUrl(object.getString("imageUrl"));
                            object.setProcessed(object.getBoolean("isProcessed"));
                            Logger.e(object.getBoolean("isProcessed") + "");
                        }
                        callback.done(objects, null);
                    } else {
                        callback.done(null, new ParseException(1001, "No Services"));
                    }
                } else {
                    callback.done(null, e);
                }
            }
        });
    }
the code above suppose to refresh my data but however my log always shows that isProcessed is False even tho it's set to True inside the Parse Browser

what i have tried besides this? ``fetchAllInBackground & fetch()`` you name it. the object will always return false until i re-run the application from Android Studio what i'm doing here wrong? btw here is how i initialize Parse

    Parse.setLogLevel(BuildConfig.DEBUG ? DEBUG_LEVEL : Parse.LOG_LEVEL_NONE);
    ParseObject.registerSubclass(ProductsModel.class);
    ParseObject.registerSubclass(ProductRentalModel.class);
    ParseObject.registerSubclass(ServicesModel.class);
    Parse.enableLocalDatastore(context);
    Parse.initialize(context, context.getString(R.string.app_id), context.getString(R.string.client_id));``

this question is asked here too: 
http://stackoverflow.com/questions/34253432/parse-findallinbackground-fetchallinbackground

**Comment by k0shk0sh** [comment]
the answer was to remove

   ``Parse.enableLocalDatastore(context);``
which is bad anyway, without the data are refreshed probably, however with enabling the local database, the data will not refresh unless if i killed the app and/or re-install it. that's bad. but did the trick.

**Comment by k0shk0sh** [comment]
any other solution for this while keeping the local database enabled?

**Comment by grantland** [comment]
Is it possible that you have a call to set `isProcessed` to `false` anywhere in your code? If you do, Local Datastore (LDS) will keep track of that dirty change and any call to `object.get("isProcessed")` will return the dirty value. This will happen even if you try to re-query the object because the SDK gives priority to dirty changes over new values from the server.

A good way to check if this is the case other than looking for `object.set("isProcessed", true)` is to check if the object is dirty:

```java
Log.d(TAG, "dirty=" + object.isDirty() + " dirty[\"isProcessed\"]=" + object.isDirty("isProcessed"));
```

**Comment by k0shk0sh** [comment]
nope, im not using `set` in anywhere. 
``public void setProcessed(boolean isProcessed){
this.isProcessed = isProcessed;
put('isProcessed',isProcessed);
}``
that's what I'm doing.

**Comment by grantland** [comment]
Sorry, typo. I meant `object.put("isProcessed", true)`. Have you checked if it was in fact dirty?

**Comment by k0shk0sh** [comment]
i haven't yet. i will and reply asap.

**Comment by k0shk0sh** [comment]
yup, that was the cause,  in my setter ``put('isProcessed',isProcessed); `` i have this, i never thought put would actually cause the database to be dirty. removing it fix the issue.

**Comment by grantland** [comment]
Awesome! I'll be closing this issue then.
