### ISSUE TITLE
saveInBackground not working after app cache grows to a size of around 20MB

### ISSUE THREAD

**Issue by vr100** [ParsePlatform/Parse-SDK-Android#298]
We are facing an issue with Parse Android SDK. Once the app data grows to a size of about 20 MB, none of the save calls from the SDK initiate a HTTP request. The GET requests are made and go through fine. This happens occasionally to one particular customer. Once the customer clears the app data, the app works fine and save goes through successfully. We are not able to reproduce this consistently. We would like to understand why this is happening. Any pointers as to how to debug this issue or possible root causes would be of great help to us. Thank you!

(Parse Android SDK version used: 1.10.3)

**Comment by vr100** [comment]
I looked into the API events for that particular user using Parse Explorer. During the period when the user faces the issue, Request-type: get and Request-type: update for the class _User are missing. Once the user clears the app data, the get and update requests for the Class _User go through fine. Is it possible that the fetch and save tasks for the current user parse object are stuck in the task queue?

**Comment by grantland** [comment]
The taskQueue would be cleared on cold app starts, so I don't think that would be the issue. Clearing app data doesn't really tell us much since it's the equivalent of reinstalling the application which causes the user to re-login.

Would you be able to reproduce this with debugging attached and possibly Stetho + [ParseInterceptors](https://github.com/ParsePlatform/ParseInterceptors-Android)? This will allow you to view the state of the app and the network requests that it's making.

**Comment by vr100** [comment]
Yes, we did try to get the logs using ParseLogInterceptor. It provided the same info as the ParseExplorer. The http requests for GET _User/<Current_User_Id> and PUT _User/<Current_User_Id> are not made during the period the user faces the issue. Once the user clears the app data and logs in again, the http requests for GET _User/<Current_User_Id> and PUT _User/<Current_User_Id> are made and go through fine.

**Comment by grantland** [comment]
Would you be able to provide a small project that repros this issue as well as device description so that we could look into this issue?

**Comment by vr100** [comment]
We are unable to reproduce the issue ourselves locally. It happens to just one particular test user. We are trying to add more logs in Parse SDK particularly around the enqueuing of tasks for current user. Also, we will be integrating stetho and giving the apk to the user for testing. We will provide you with the device description once we have it from the user. Thank you!

**Comment by vr100** [comment]
The device details are:
Phone Model: Sony Xperia Z3
OS: 4.4.4 ( updated to 5.0.1)
Kernel: 3.4.0
API Level: unknown

Please let me know if any further information is needed

**Comment by grantland** [comment]
A repro project would be best. Just to clarify, how did you manage to get logs with ParseLogInterceptor without being able to reproduce this?

**Comment by vr100** [comment]
We tried growing the app data size to around 40 Mb and tried various scenarios. But we are not able to reproduce the issue.

We gave a special build of the app to that particular user after integrating ParseLogInterceptor. When the user faced the issue again (after the app data grows to a certain size), the user sent us the logs from his device.

**Comment by vr100** [comment]
We will be getting additional data soon from the user. We will update the issue once we have the same

**Comment by vr100** [comment]
We got additional data from the user.
We customized Parse SDK to add a count for the number of tasks in the Parse Object's Task Queue. We find that when the app is in stale state, the current user object's task queue count keeps increasing. (We had a count of around 20 tasks waiting in the task queue when we last checked the logs). 

Could you please guide us by providing some code pointers on how to proceed further or providing us some debugging hints?

**Comment by vr100** [comment]
Here is the json for the current user that we found in the user's offline database:

{"className":"_User","objectId":"<object_id>","createdAt":"2015-03-22T15:00:57.116Z","updatedAt":"2015-12-30T12:38:26.503Z","mobile_verified":true,"mobile_phone_number":"<phone_number>","email":"<email_id>","displayName":"<name>","sessionToken":"<session_token>","location":{"__type":"GeoPoint","latitude":<latitude_value>,"longitude":<longitude_value>},"status":1,"username":"<user_name>","optOut":0,"distanceString":"1","unit":"Kilometers","distance":"3","verification_code":<code>,"is_logged_in":1,"__complete":true,"__isDeletingEventually":0,"__operations":[{"unit":"Kilometers","distance":"0.5","__uuid":"e266fad0-2f9b-434d-993e-0e2737622996","__isSaveEventually":true},{"__uuid":"4fd61ba7-2595-4d57-bb65-bada0a4ef9dc"}]}

Could you let us know what does __operations here signify? Does it indicate a pending operation on the current user?

**Comment by vr100** [comment]
Also, in case a task in the task queue is stuck or blocking, could you let us know if there is a way to get the details of the blocking task?

**Comment by grantland** [comment]
Would you happen to be using `saveEventually()` along with `save()` on the same `ParseObject` instance? If so, this can lead to weird results such as this. `ParseObject`s have a single queue for all operations and a failed `saveEventually()` command can block the entire queue until the next app start or network connectivity changes. 

I would recommend only using `saveEventually()` or `save()` on a `ParseObject`, `saveEventually()` if you don't care about whether or not the save completes, succeeds, or fails and `save()` if you do.

Now, this _might_ relate to the app data size since we might be running out of room to store these `saveEventually()` operations. In this case, I'll need to check to see what our code does when we don't have space to persist these operations to disk. Could you tell me whether you're using Local Datastore or not?

Are you also sure that a cold start of the app doesn't solve this (killing the task via app switcher, swiping away the app, starting the app again)?

Now to answer your questions:

> We find that when the app is in stale state, the current user object's task queue count keeps increasing.

This would happen if your code or your user keeps changing properties of a `ParseObject` and saving it when the queue is stuck since that operation will be enqueued to the back of the queue.

> Could you let us know what does `__operations` here signify? Does it indicate a pending operation on the current user?

`__operations` is how we persist unsaved operations.

> Also, in case a task in the task queue is stuck or blocking, could you let us know if there is a way to get the details of the blocking task?

You could theoretically do this by creating a UUID that gets logged like the following:

```java
String uuid = UUID.randomUUID().toString();
Log.d(TAG, uuid + " starting");
object.save().continueWithTask((t) -> {
  Log.d(TAG, uuid + " finished");
  return t;
});
```

> When we checked the offline database of the user, we found 321 objects with className = "_EventuallyPin". Is this expected? (The user has good internet connectivity in the phone and is able to use other apps without any issue).

This can happen if a lot of `saveEventually()` operations are enqueued that cannot be completed. When one fails we mark the connectivity as `false` until the next app start or until the network connectivity has changed, i.e. cellular -> wifi

**Comment by grantland** [comment]
If LDS is not enabled and there's an issue persisting the command for later, you'll see a log here: https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseCommandCache.java#L386

and if LDS is enabled:
https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParsePinningEventuallyQueue.java#L247

You can enable logging with `Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE)`

**Comment by vr100** [comment]
Thanks a lot for the detailed reply. Here are the answers to your questions.

* We have enabled local data store
* The user rebooted the phone and still the issue persists. (We will request the user to do a cold app start as well and update you on the results). Only clearing the app data resolves the issue so far.
* The user tried switching network. It did not help
* We don't use save() and saveEventually() on the same ParseObject. We could be using saveInBackground() and saveEventually() on the same ParseObject. (For example, we use ParseUser.getCurrentUser() and do saveEventually() in some cases. In some other cases, we do saveInBackground() on the current user)

**Comment by vr100** [comment]
We are considering deleting the first _EventuallyPin object from the local datastore of the user's phone using stetho. Do you think it would help us resolve the issue or understanding the root cause?

**Comment by grantland** [comment]
> We don't use save() and saveEventually() on the same ParseObject. We could be using saveInBackground() and saveEventually() on the same ParseObject. (For example, we use ParseUser.getCurrentUser() and do saveEventually() in some cases. In some other cases, we do saveInBackground() on the current user)

`saveInBackground()` is the same as `save()`, but asynchronous. Only use eventually or not on a `ParseObject`.

Deleting all the eventually pins should solve the issue if you can do that, although this is treading into uncharted territory and could lead to some very odd results.

A reinstall once you've decided to only use `save`/`InBackground()` or `saveEventually()` would yield better results.

**Comment by ramkalari** [comment]
Is this recommendation for a single transaction or across the app. Assuming it is across the app, we need to support offline edits. So, we will definitely need saveEventually. Does this mean we cannot use saveInBackground or saveAllInBackground if we know the internet connection exists.

**Comment by grantland** [comment]
It's not recommended across the app since a `saveEventually()` call can possibly block the entire operation set queue and therefore any subsequent `save`(`InBackground`)`()`, `delete()`, etc.

**Comment by vr100** [comment]
Just to be clear, 
* It is not recommended to use saveEventually and save (or saveInBackground) on the same object.
* We could classify objects / tables into two groups - 
    - objects on which saveEventually will be called (say, messages, etc.)
    - objects on which saveInBackground will be called (say, users, etc.)

Am I correct?

**Comment by vr100** [comment]
* I query and fetch an object from parse, say X, and call saveEventually() on it
* I query again and fetch the same object X from parse and call saveInBackground() on it.

Does this count as performing saveEventually and saveInBackground on the same object? 

(From looking through the SDK source code, I think in both cases, we will working on the same java object. Am I correct?)

**Comment by grantland** [comment]
Yes, all of those are correct.
