### ISSUE TITLE
Remove GET_ACCOUNTS permission from the android quickstart guide, please

### ISSUE THREAD

**Issue by ssomai** [ParsePlatform/Parse-SDK-Android#301]
On this page, remove the following line, please.
\<uses-permission android:name="android.permission.GET_ACCOUNTS" />
https://parse.com/apps/quickstart#parse_push/android/native/existing

Because Parse Android SDK don't need the permission.
https://github.com/ParsePlatform/Parse-SDK-Android/releases

Thank you.

**Comment by grantland** [comment]
It's still required by Google Services Framework on < Android 4.0.4, so we're leaving it in our guides so that it's less confusing for developers in case they're supporting < 4.0.4. If developers desire not to include it, they will find resources that state it's not required for 4.0.4+.
