### ISSUE TITLE
Save ParseObject with ParseUser pointer. "Cannot save a ParseUser that is not authenticated". Bug?

### ISSUE THREAD

**Issue by petersf7** [ParsePlatform/Parse-SDK-Android#308]
I have project where I send messages between 2 and 2 ParseUsers, and save the messages as a ParseObjects where I keep a Pointer to the 2 users sending messages to each other. The code works for every user in the database except when I send a message to 1 particular user. Then I get "Cannot save a ParseUser that is not authenticated", so it seems like Parse tries to save the other User object, together with saving my message ParseObject, just with this one particular user. Tried to create a "Save without data" object, but get the same error. Is this a bug with saving ParseObjects?

    ParseObject message = new ParseObject("MSG");
    message.put("sender", meUser);
    message.put("receiver", otherUser);
    message.saveInBackground(new SaveCallback() {
                            @Override
                            public void done(ParseException e) {
                                if( e== null){
                                    Log.i(TAG, " Worked...");
                                }else {
                                    e.printStackTrace();                                
                                }
                            }
                        }); 

I don't know if its relevant or not, but to add some extra information, these 2 users used to have a ParseRelation user1 to user2, but that ParseRelation column is deleted now. Still does not work.

**Comment by grantland** [comment]
It seems like you might be accidentally making the `ParseUser` dirty somewhere, since the only reason the SDK will try to save a nested object is if it's dirty. You can check this with `ParseObject#isDirty()` and then work your way backwards with the debugger to figure out where you're making it dirty.

**Comment by petersf7** [comment]
Thanks @grantland , that did the trick! Sorry for posting question here, but thought maybe it could be a bug.
