### ISSUE TITLE
Push Notifications Received by some recipients not all

### ISSUE THREAD

**Issue by alsajoo** [ParsePlatform/Parse-SDK-Android#309]
All users are using the same code base on Android only. Pushes being sent using cloud code and target query. GCM token is present on all tagets.

I can see in the console messages are sent successfully but many recipients don't get it. I have conducted a test with over 50 recipients live and less than 50% said they got the message.

The issue started after 1.9 and has been present since even on the current 1.11 version.

I've had issues of users not receiving a token, that's a separate issue that does not affect this particular scenario.

On all my test devices I receive notifications fine.

**Comment by IomarSantos** [comment]
In my case I received not push! See question on stackoverflow:
http://stackoverflow.com/questions/34512258/android-pushes-not-received-after-the-app-is-closed-in-parse

**Comment by wangmengyan95** [comment]
Hi @IomarSantos, I do not think your issue is related to the original issue. Do you mind opening a new one?
