### ISSUE TITLE
Android : Parse Can't set channels for a query-targeted push

### ISSUE THREAD

**Issue by hongzhou85** [ParsePlatform/Parse-SDK-Android#31]
There is no query set for the parse push, but the error is given when pushed.
Parse version 1.9.1. 

Expected: The object should be pushed to targeted channel without error.
Error encounter: Parse Can't set channels for a query-targeted push
Problem: There is clearly no query set for the push to target but the error was thrown.
```
ParsePush push = new ParsePush();
push.setChannel(AppConfig.PARSE_CHANNEL);
push.setData(JSONObject);
push.sendInBackground(new SendCallback() {
    @Override
    public void done(ParseException e) {
        if(e==null) {
            Toast.makeText(getApplicationContext(),"success",Toast.LENGTH_SHORT).show();
        }
    }
});
```

**Comment by grantland** [comment]
I'm not clear on what issue you're encountering. Please take a look at our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md) for reporting issues.

**Comment by Amorino** [comment]
I got the same error.

Heres my code, is the exact same as the documentation.
```java
    ParsePush push = new ParsePush();
        push.setChannel("channel");
        push.setMessage("Message");
        push.sendInBackground(new SendCallback() {
            public void done(ParseException e) {
                if (e == null) {
                    Log.d("push", "The push campaign has been created.");
                } else {
                    Log.d("push", "Error sending push:" + e.getMessage());
                }
            }
        });
```

**Comment by grantland** [comment]
Please follow our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md) so we can help you with your issues. In particular:

> Details are key. The more information you provide us the easier it'll be for us to debug and the faster you'll receive a fix. Some examples of useful tidbits:

> * A description. What did you expect to happen and what actually happened? Why do you think that was wrong?
* A simple unit test that fails. Refer [here][tests-dir] for examples of existing unit tests. See our [README](README.md#usage) for how to run unit tests. You can submit a pull request with your failing unit test so that our CI verifies that the test fails.
* What version does this reproduce on? What version did it last work on?
* [Stacktrace or GTFO][stacktrace-or-gtfo]. In all honesty, full stacktraces with line numbers make a happy developer.
* Anything else you find relevant.

 [stacktrace-or-gtfo]: http://i.imgur.com/jacoj.jpg
 [tests-dir]: /Parse/src/test/java/com/parse

**Comment by hongzhou85** [comment]
Hi grantland, care to share if you know of this issue or any way to resolve it? It is a simple push message and the error returned was "Parse Can't set channels for a query-targeted push".

**Comment by grantland** [comment]
I can't ascertain whether or not this is a known issue without at least a way to reproduce it along with the actual error stack trace.

I see that you've updated the original issue that this occurs with 1.9.1, does it still repro with latest (1.10.1)?

**Comment by hongzhou85** [comment]
Using the codes attached above, this is the actual stack trace:
```
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ com.parse.ParseRequest.newPermanentException(ParseRequest.java:391)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ com.parse.ParseRESTCommand.onResponse(ParseRESTCommand.java:197)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ com.parse.ParseRequest$3.then(ParseRequest.java:258)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ com.parse.ParseRequest$3.then(ParseRequest.java:254)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ bolts.Task$14.run(Task.java:796)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ bolts.Task.completeAfterTask(Task.java:787)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ bolts.Task.continueWithTask(Task.java:599)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ bolts.Task.continueWithTask(Task.java:610)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ bolts.Task$12.then(Task.java:702)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ bolts.Task$12.then(Task.java:690)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ bolts.Task$14.run(Task.java:796)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-20 11:14:45.587    3863-3863/co.myapp.bys I/System.out﹕ java.lang.Thread.run(Thread.java:818)
```

**Comment by grantland** [comment]
I can't repro this with the 1.10.1 (latest). Does 1.10.1 resolve this issue for you?
