### ISSUE TITLE
Facebook login takes minutes to complete

### ISSUE THREAD

**Issue by sandlerben** [ParsePlatform/Parse-SDK-Android#314]
I am using the [ParseUI-Android](https://github.com/ParsePlatform/ParseUI-Android) library. When I try to login with Facebook, it takes between one and five minutes to complete. Note: with Twitter and regular accounts, the process is immediate.

**Comment by wangmengyan95** [comment]
Hi @sandlerben, please open a issue in ParseUI. We only use this repo to track Parse SDK issue.
