### ISSUE TITLE
Not receiving notifications after updating Parse SDK

### ISSUE THREAD

**Issue by SeanOThomas** [ParsePlatform/Parse-SDK-Android#316]
I updated the Parse SDK to the latest version (1.11.0) for the sole reason of getting rid of the `GET_ACCOUNTS` permission. The only other change I had to make was removing `PushService.setDefaultPushCallback()`; which is now deprecated. I didn't think this would be a problem because I handle any intents in a custom broadcast receiver.

However, now push notifications are NOT being received at all (they are being sent successfully, though). I'm confident the problem is removing `PushService.setDefaultPushCallback();`. Why would this be the issue, and what can I replace it with?

**Comment by IomarSantos** [comment]
I am having the same problem, however in some device receives push.
http://stackoverflow.com/questions/34512258/android-pushes-not-received-after-the-app-is-closed-in-parse

**Comment by vincentvictoria** [comment]
@IomarSantos It's probably because PPNS jar is removed. Devices without GCM won't receive any pushes without the jar. Take a look at https://github.com/ParsePlatform/Parse-SDK-Android/issues/197

To Parse Team, Is PPNS going to be removed all together?
I hope not, because PPNS is crucial to devices without GCM even in Marshmallow.

**Comment by wangmengyan95** [comment]
Hi @vincentvictoria, we still support PPNS, check #197.

**Comment by vincentvictoria** [comment]
@wangmengyan95 Thank you for the double confirmation. I had some doubts about the future of PPNS, but that gives me a relief.

**Comment by rogerhu** [comment]
PPNS is no longer in development (https://github.com/ParsePlatform/parse-server/issues/1113).  GCM/APNS are the supported protocols for open source Parse server.  Unless someone decides to pick up the mantle of supporting it...
