### ISSUE TITLE
Invalid GCM Token with new GCM Play Services

### ISSUE THREAD

**Issue by JcMinarro** [ParsePlatform/Parse-SDK-Android#319]
I have updated the GooglePlay Services to version 8.3.0 (The last one at now)
The token always has the next format "APAXX....XXX" But with the new version some of the token has the next format "|ID|1:XX...XX:APAXXX...XXX" where the "XXX" is an alphanumeric character.
All the new token format instalations don't receive any notifications.

**Comment by JcMinarro** [comment]
I am not sure if it is a bug on back, because some time it send a correct token. I think it is a problem on client. With the old version of GooglePlayService it worked fine. If you need I can show you a screenshot from parse dasboard. And I can do some trails with the thing that you need.

**Comment by wangmengyan95** [comment]
Hi @JcMinarro, I am trying to repo this issue. I would be great to see the screenshot. Thanks.

**Comment by JcMinarro** [comment]
Here is the screenshot of my parse dashboard:
![captura de pantalla de 2015-12-24 12 40 55](https://cloud.githubusercontent.com/assets/4047514/11994319/6b11a1d2-aa3c-11e5-9ec1-a33594961293.png)
If you need any other thing, let me know

**Comment by datrixo** [comment]
This same issue here. What is the status of investigation?

**Comment by datrixo** [comment]
That could be connected somehow with another push provider? Because we noticed this change after implementing Pushwoosh for tests.

**Comment by wangmengyan95** [comment]
Hi @datrixo, currently we do not support using other push provider with Parse. Probably that is the source of the issue. I am curious what push provider do you using?
@JcMinarro, I test with google play service 8.3 and 8.4 but I still can not repo the deviceToken you have. I check google doc but it seems they do not mention they change the format of the deviceToken. In this situation, is it possible for you to give us a sample app to repo the issue?

**Comment by datrixo** [comment]
We are using also: https://www.pushwoosh.com/ 
And Pushwoosh works now perfect, but Parse have weird behavior. Sometimes deviceToken is incorrect, and after next app lanuch the device token change to correct one.

**Comment by wangmengyan95** [comment]
Hi @datrixo, we just use the standard Google way to handle the deviceToken. Since we do not have control on other libraries, probably there is nothing more we can do.

**Comment by hofmann** [comment]
Hi, I do see a similar issue in an app I'm developing for a customer. This app uses both the Parse and Layer SDKs. Both SDKs are setup to register to GCM with the same 2 service ids. In my case I see device tokens in the form of ""|ID|1|:<package name>" returned from the Parse installation object. And this happens after logging out from Layer (which also unregisters from GCM for both services). As a consequence the Parse GcmBroadcastReceiver does receive an Intent which contains exactly this strange device token. To me this looks like a Google internal format somehow which probably should not be exposed to the outside world.

What I'm wondering about is why the Parse SDK is still using the "old style" GCM registration, i.e. delivery of the registration token via BroadcastReceiver. From my understanding this is deprecated anyhow and the "new style" does work without using this BroadcastReceiver but instead using the InstanceID API as described here: https://developers.google.com/cloud-messaging/android/client#sample-register.

Any plans to change to the "new style"? Maybe this would fix the issue automatically.

**Comment by wangmengyan95** [comment]
Hi @hofmann , we have this discuession before, check #16

**Comment by hofmann** [comment]
Hi @wangmengyan95, thanks for pointing me to the previous discussion, wasn't aware of  that one.

Looking into the latest GCM documentation it seams to me that the update of tokens would now be reported/triggered via the "com.google.android.gms.iid.InstanceID" Intent action via the InstanceIDListenerService as described here: https://developers.google.com/cloud-messaging/android/client (at least that's how I did it recently within an app which uses the new GCM APIs).

**Comment by datrixo** [comment]
@wangmengyan95 plase check this answers: http://stackoverflow.com/questions/33720401/gcm-and-parse-conflict/35037171#35037171

**Comment by grantland** [comment]
This is due to the application registering with GCM in addition to Parse's automatic registration, which we do not support.

Please refer to #16 regarding support for Google Services Framework.
