### ISSUE TITLE
PPNS support removed?

### ISSUE THREAD

**Issue by ludvigaldrin** [ParsePlatform/Parse-SDK-Android#320]
We have been using PPNS support since GCM is not working when you used cloned android devices. Our product is based on this where we run an android app and use parse to handle a lot of nice things. Since yesterday this has stopped working. We then ran version 1.9.4.

Looking in the loggs I can see this:
12-22 21:38:46.410 19887-19966/com.app.XX V/com.parse.PushConnection: PushConnection write failed: {"oauth_key":"xxxxxxxxx","v":"a1.10.2","installation_id":"xxxxx","ack_keep_alive":true} due to exception: javax.net.ssl.SSLHandshakeException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate expired at Mon Dec 21 13:00:00 GMT+01:00 2015 (compared to Tue Dec 22 21:38:46 GMT+01:00 2015)

So by this it looks like something changed yesterday that made PPNS stop working. So we thought that you had a fix in your latest version 1.11. So we added this and then we start getting messages like this:

com.parse.ManifestInfo: Using none for push.

and with this the old messages about that we are missing stuff in the mainfest. I googled around and found out that you have removed a part for the PPNS. I found the last version in 1.10.2 however adding this we get the same issues as above.

If I add GCM for testing the app works great directly. 

So my question here: Have you removed PPNS support silently. Or is this just a hickup in your system?

**Comment by grantland** [comment]
Closing as duplicate: #197

**Comment by ludvigaldrin** [comment]
Except that Parse screwed it up by forgetting to update the certificate and that they removed the PPNS library "secretly". I would say overall its not okay from parse.
