### ISSUE TITLE
ParseFile.saveInBackground progress callback bug

### ISSUE THREAD

**Issue by ppilip** [ParsePlatform/Parse-SDK-Android#322]
Hi all.
I updated the `Parse SDK` to the latest version (1.11.0) and have issues with the `ProgressCallback.done(Integer percentDone)` method being called up to 100% really fast, while the `ParseFile` has not been uploaded yet.

When I change Parse version back to `v1.10.0` and remove all other PARSE related dependencies, progress call works normal again (percentage reflects the % of file upload). If I use just v1.11.0 without other PARSE dependencies, the problem reappears...I'm puzzled.

I'm using latest Android Studio, and my build file has: 
`compile'com.parse:parse-android:1.11.0'`
`compile files('libs/ParseCrashReporting-1.10.2.jar')`
`compile files('libs/ParseFacebookUtilsV4-1.10.3.jar')`
`compile files('libs/ParseTwitterUtils-1.10.3.jar')`

**Comment by wangmengyan95** [comment]
Hi @ppilip, briefly speaking, the issue you observe is:
If you use parse `1.10.0`, upload progress works fine.
If you use parse `1.11.0`, upload progress goes to 100% really fast.
Is this correct?
In your case, we still need some additional information
1. Your test environment.
2. Enable logging in our SDK with Parse.setLogLevel(Log.VERBOSE) and paste the logcat.
Thanks.

**Comment by ppilip** [comment]
Hello again @wangmengyan95 ,

that is correct. 
But the issue is gone now. I've switched from working on my desktop, to my laptop on the same project (pulled it from the same git repository) and the progress callback started working fine.
I believe that my working environment was corrupted somehow, but I won't be able to test that assumption for the next 30 days until I get my hands on my computer again. I will open another issue, cause I believe this one will be closed by then.

BTW, both systems had Android Studio 1.5.1
Build #AI-141.2456560, built on December 1, 2015
but other parts were different (JRE version, OS versions...)

**Comment by wangmengyan95** [comment]
No problem, glad it works. I will close this issue.

**Comment by ppilip** [comment]
Hello, 
it's me again. Just to let you know that the problem is back. I updated Android studio to 2.0 (preview) version, loaded project in it, and the issue manifested again. I tried to load project into previous AS version (1.5) but the problem remained the same (progress goes from 0% to 100% in a second, while the file upload lasts in the background for a 15 seconds).

Anyways, here's my .build file:

	compile files('libs/quickblox-android-sdk-chat-2.3.3.jar')
	compile files('libs/quickblox-android-sdk-core-2.3.3.jar')
	compile files('libs/quickblox-android-sdk-customobjects-2.3.3.jar')
	compile files('libs/quickblox-android-sdk-messages-2.3.3.jar')`
	compile('com.twitter.sdk.android:twitter:1.10.0@aar') {
		transitive = true;
	}
	compile('com.twitter.sdk.android:tweet-composer:1.0.1@aar') {
		transitive = true;
	}
	compile 'com.google.android.gms:play-services-maps:8.3.0'
	compile 'com.google.android.gms:play-services-gcm:8.3.0'
	compile 'com.google.android.gms:play-services-plus:8.3.0'
	compile 'com.google.android.gms:play-services-identity:8.3.0'
	compile 'com.android.support:support-v13:21.0.3'
	compile 'com.danikula:videocache:2.3.4'
	compile 'com.parse.bolts:bolts-tasks:1.3.0'
	compile 'com.parse:parse-android:1.12.0'

and logcat with `Parse.setLogLevel(Log.VERBOSE)`
[log.txt](https://github.com/ParsePlatform/Parse-SDK-Android/files/99666/log.txt)
