### ISSUE TITLE
Make estimatedData available for data binding

### ISSUE THREAD

**Issue by lucoceano** [ParsePlatform/Parse-SDK-Android#324]
Hi,

With android new feature [data binding](http://developer.android.com/tools/data-binding/guide.html#observable_collections), do you have any plans to change estimatedData/serverData from HashMap to ObservableArrayMap and make it accessible so we can bind objects? or do you have anything else on mind for data binding?

Thanks!

**Comment by grantland** [comment]
Changing `estimatedData`/`serverData` from `HashMap` to `ObservableArrayMap` would be a breaking change as it would require the data binding library.

Supporting data binding may be something we'd look into in the future, but we don't have any plans at the moment.

**Comment by lucoceano** [comment]
@grantland thanks!

**Comment by Jawnnypoo** [comment]
@rogerhu I think this one can be closed out as databinding is probably not going to be supported anytime soon.
