### ISSUE TITLE
Error -1

### ISSUE THREAD

**Issue by andrew44456** [ParsePlatform/Parse-SDK-Android#327]
While trying to SignUp a new user using ParseUser, SignUpInBackgroud fails and shows error -1.

12-31 09:30:10.746 10692-10692/? E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:126:/dev/adsprpc-smd device initialization error: No such file or directory
12-31 09:30:10.746 10692-10692/? E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:179::error: -1: dev != -1
12-31 09:30:10.746 10692-10692/? E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:224::error: -1: 0 == (nErr = remotectl_open(name, (int*)ph, dlerrstr, sizeof(dlerrstr), &dlerr))
12-31 09:30:10.747 10692-10692/? E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:126:/dev/adsprpc-smd device initialization error: No such file or directory
12-31 09:30:10.747 10692-10692/? E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:179::error: -1: dev != -1
12-31 09:30:10.747 10692-10692/? E/adsprpc: vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:23::error: -1: 0 == adsp_default_listener_register()
12-31 09:30:10.747 10692-10692/? E/adsprpc: vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:36:adsprpcd exiting nErr=-1

**Comment by grantland** [comment]
The Parse SDK package isn't anywhere in the stacktrace you posted. Are you sure the problem is with Parse? In addition, please include all information outlined in our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md).
