### ISSUE TITLE
Android, can't upload file

### ISSUE THREAD

**Issue by antoncty** [ParsePlatform/Parse-SDK-Android#332]
My app worked well half month ago -  i 
I uploaded the images well, but now i have problem. I can't upload image into parse.com in certain table. It's problem only on devices, on emulator app working well. I`m trying this code (select image from gallery):

```java
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    if (resultCode == Activity.RESULT_OK && data != null) {
        String realPath;
        // SDK < API11
        if (Build.VERSION.SDK_INT < 11)
            realPath = RealPathUtil.getRealPathFromURI_BelowAPI11(this, data.getData());

            // SDK >= 11 && SDK < 19
        else if (Build.VERSION.SDK_INT < 19)
            realPath = RealPathUtil.getRealPathFromURI_API11to18(this, data.getData());

            // SDK > 19 (Android 4.4)
        else
            realPath = RealPathUtil.getRealPathFromURI_API19(this, data.getData());
        File file = new File(realPath);
        try {
            byte bytes[] = new byte[(int) file.length()];
            BufferedInputStream bf = new BufferedInputStream(new FileInputStream(file));
            bf.read(bytes, 0, bytes.length);
            bf.close();
            Bitmap bmp = BitmapFactory.decodeByteArray(bytes, 0, bytes.length);
            ((ImageView) findViewById(R.id.setIMG)).setImageBitmap(bmp);
            pFile = new ParseFile("file", bytes);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

After it, when user click on special button, execute this code:
```java
void sendPost(String txt) throws ParseException {
    String parseUserId = getIntent().getExtras().getString(ObjConst.OBJECT_ID);
    ParseUser parseUser = null;
    ParseQuery<ParseUser> queryUser = ParseUser.getQuery();
    queryUser.whereEqualTo(ObjConst.OBJECT_ID, parseUserId);
    try {
        parseUser = queryUser.getFirst();
    } catch (ParseException e) {
        Log.e("INTERNET", "Problem with internet connection or can`t find your accaunt.");
    }

    if (parseUser != null) {
        final ParseObject parseObject = new ParseObject(ObjConst.POST);
        parseObject.put(ObjConst.POST_ANONIMOUS, checkBox.isChecked());
        parseObject.put(ObjConst.POST_AUTHOR, parseUser);
        parseObject.put(ObjConst.POST_TEXT, txt);
        final Context ctx = this;
        if (pFile != null) {
            parseObject.put(ObjConst.POST_PHOTO, pFile);
            Log.d("MY_TAG", "Start upload.");
            pFile.saveInBackground(new SaveCallback() {
                @Override
                public void done(ParseException e) {
                    if (e != null) {
                        Log.d("MY_TAG", "ParseException: " + e.getMessage());
                    }
                    Log.d("MY_TAG", "Start save ParseObject");
                    saveParseObject(parseObject, ctx);
                }
            }, new ProgressCallback() {
                @Override
                public void done(Integer percentDone) {
                    Log.d("MY_TAG", percentDone+" %");
                }
            });
        } else saveParseObject(parseObject, ctx);
    }
}

void saveParseObject(ParseObject parseObject, final Context ctx) {
    Log.d("MY_TAG", "Start saveParseObject()");
    parseObject.saveInBackground(new SaveCallback() {
        @Override
        public void done(ParseException e) {
            Log.d("MY_TAG", e.getMessage());
            Log.d("MY_TAG", "End. ParseObject saved. " + e.getMessage());

            if (e != null)
                Log.i("Write post.", "Can`t write post. Problem with internet connection.");
            else Toast.makeText(ctx,
                    "Отправлено", Toast.LENGTH_SHORT).show();
        }
    });

}
```
Output of the program:
```
01-04 21:46:02.376 7360-7360/com.appserv D/MY_TAG: Start upload.
01-04 21:46:02.433 7360-7360/com.appserv D/MY_TAG: 58 %
01-04 21:46:02.434 7360-7360/com.appserv D/MY_TAG: 100 %
01-04 21:46:13.615 7360-7360/com.appserv D/MY_TAG: 58 %
01-04 21:46:13.618 7360-7360/com.appserv D/MY_TAG: 100 %
01-04 21:46:25.941 7360-7360/com.appserv D/MY_TAG: 58 %
01-04 21:46:25.945 7360-7360/com.appserv D/MY_TAG: 100 %
01-04 21:46:40.553 7360-7360/com.appserv D/MY_TAG: 58 %
01-04 21:46:40.557 7360-7360/com.appserv D/MY_TAG: 100 %
01-04 21:46:59.725 7360-7360/com.appserv D/MY_TAG: 58 %
01-04 21:46:59.730 7360-7360/com.appserv D/MY_TAG: 100 %
01-04 21:47:09.754 7360-7360/com.appserv D/MY_TAG: ParseException: i/o failure
01-04 21:47:09.754 7360-7360/com.appserv D/MY_TAG: Start save ParseObject
01-04 21:47:09.754 7360-7360/com.appserv D/MY_TAG: Start saveParseObject()
```
But, if I take image from package drawable: `Bitmap bmp = BitmapFactory.decodeRecource(getRecource(), R.drawable.smallimg);`, where `smallimg`- very small image, my app work very well, this image will upload into server.

My test devices: OnePlus One CyanogenOS 12.1 (android 5.1.1), Fly IQ4514 android 4.4.2.
I not tried it on other devices.
Emulator - Genymotion with android 5.0.0, android 5.1.1.

What is the problem?

**Comment by wangmengyan95** [comment]
Hi @antoncty, I use your snippet as much as I can but I still can not repo this issue in my emulator and test device. Since you mention you can not repo it in your emulator, I highly doubt it is related to your test device or network. 
In this case, could you tell us
1. What is your test device?
2. This issue happens on all your device or just some of them? 
3. Is it possible for your to provide us with a sample project to repo this issue?

**Comment by antoncty** [comment]
@wangmengyan95 , I added more information.
About your point 3. I`m should provide you full project or some part, where the problem? And what you want to see: java code with xml file?

**Comment by antoncty** [comment]
@wangmengyan95 , I added more information.
My test devices: OnePlus One CyanogenOS 12.1 (android 5.1.1), Fly IQ4514 android 4.4.2.
I not tried it on other devices.
Emulator - Genymotion with android 5.0.0, android 5.1.1.
About your point 3. I`m should provide you full project or some part, where the problem? And what you want to see: java code with xml file?

**Comment by wangmengyan95** [comment]
Hi @antoncty, my recommendation is try your app on other devices first.
If the issue still exists, probably we have to rely on you to provide us with a sample project with detail repo steps. The sample project can be a runnale app or a unit test case.
If the issue does not exist on other devices, probably there is not much we can do about it.

**Comment by antoncty** [comment]
Hello @wangmengyan95 , can you check my example app, please: https://github.com/antoncty/parse.com-example-error
It`s very simple app. And this app have the same problem.

**Comment by wangmengyan95** [comment]
Hi @antoncty, thanks, I will take a look. BTW, does this issue exist on other devices?

**Comment by antoncty** [comment]
Hi, @wangmengyan95 , this app it has been tested on: Sony Xperia zl android 5.1.1, Lenovo S820 android 4.4. And wroks well! It is not my devices.But all images were ulpoad on server.
Why I have problem with this app?)

**Comment by siddhpuraamitr** [comment]
My parse version is 1.12.0

Hmm I got that actually issue is not with Genymotion, issue is with version

my personal device is running with 5.0 so in that it is working fine

but Genymotion with version 4.3 so I am getting issue on that

with updated version of Genymotion 5.0 it is working fine

**Comment by wangmengyan95** [comment]
Hi @antoncty, I try my emulator and device with your sample app and it works fine. 
Since you try it on other device and it works, I think probably it is an issue of your test device. For Genymotion, can you consistently repo this issue on your Genymotion or it happens randomly.
BTW, it is better to remove your appId and clientKey in your open source project.

**Comment by antoncty** [comment]
@wangmengyan95, thank you. Mb, this is problem onlyy with my devices.
