### ISSUE TITLE
Android time-out error

### ISSUE THREAD

**Issue by atahir33** [ParsePlatform/Parse-SDK-Android#335]
My app using Parse, today I made some minor changes annd Android app stopped work.
It alway returns time-out error on every requests to Parse:

V/com.parse.ParseRequest: Request failed. Waiting 1859 milliseconds before attempt #1
V/com.parse.ParseRequest: Request failed. Waiting 3718 milliseconds before attempt #2
V/com.parse.ParseRequest: Request failed. Waiting 7436 milliseconds before attempt #3

I found out that only build that made today doesn't work (i reverted to old src code but same result), but when i installed a build that i made couple days ago and its work flawlessly.
Also all Android app use Parse that I made have this iussue.
Please help!! This is a serious issue.

**Comment by lawonga** [comment]
http://stackoverflow.com/questions/34627501/parse-function-suddenly-returning-invalid-json/34663513#34663513

See my answer on there.

**Comment by grantland** [comment]
FYI `1.12.0` is latest

**Comment by grantland** [comment]
See #334 if you think you have the same issue as @lawonga
