### ISSUE TITLE
ParseLoginUI cannot sign up user

### ISSUE THREAD

**Issue by mformetal** [ParsePlatform/Parse-SDK-Android#338]
I'm overriding the ParseLoginUI xml layout files to better match the look and feel of my app. When I try and signup a user, I'm getting the Toast "Could not signup later" error message, which is shown in the default of this switch-block, so my credentials are not invalid.

                case ParseException.INVALID_EMAIL_ADDRESS:
                  break;
                case ParseException.USERNAME_TAKEN:
                  break;
                case ParseException.EMAIL_TAKEN:
                  break;
                default:

My layout files overrides the correct layout id's, and my manifest specifies that you can log in with Parse. If requested, I can link those files. Any idea what could be wrong?

**Comment by wangmengyan95** [comment]
Hi @mformetal, we only track Parse SDK issue in this repo. Could you open your issue under ParseUI repo? Thanks.
