### ISSUE TITLE
ParseRequestException on Genymotion 4.3 API 18 

### ISSUE THREAD

**Issue by siddhpuraamitr** [ParsePlatform/Parse-SDK-Android#346]
I have used latest parse by gradle 

  compile 'com.parse.bolts:bolts-android:1.+'
  compile 'com.parse:parse-android:1.+'

whenever I have tried with genymotion I am always getting below errror 

com.parse.ParseRequest$ParseRequestException: i/o failure
 W/System.err:     at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:289)
 W/System.err:     at com.parse.ParseRequest$2.then(ParseRequest.java:144)
W/System.err:     at com.parse.ParseRequest$2.then(ParseRequest.java:138)
W/System.err:     at bolts.Task$15.run(Task.java:839)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
W/System.err: Caused by: java.io.IOException: unknown format (magic number 227b)
W/System.err:     at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:101)
W/System.err:     at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:81)
W/System.err:     at com.parse.ParseDecompressInterceptor.intercept(ParseDecompressInterceptor.java:40)
W/System.err:     at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
W/System.err:     at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
W/System.err:     at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
W/System.err:     at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:135)
W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:132)
W/System.err:     at bolts.Task$15.run(Task.java:839)
W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
W/System.err:     at bolts.Task.completeAfterTask(Task.java:830)
W/System.err:     at bolts.Task.continueWithTask(Task.java:642)
W/System.err:     at bolts.Task.continueWithTask(Task.java:653)
W/System.err:     at bolts.Task$13.then(Task.java:745)
W/System.err:     at bolts.Task$13.then(Task.java:733)
W/System.err: 

but samething if I am executing from my Nexus 5 device it is working fine

Please resolve this issue as soon as possible

Thanks

**Comment by grantland** [comment]
@siddhpuraamitr could you confirm the exact version of the Parse SDK this is reproducing on and the network request you're trying to make?

@wangmengyan95 FYI, this might be related to #332

**Comment by siddhpuraamitr** [comment]
My parse version is 1.12.0

Hmm I got that actually issue is not with Genymotion, issue is with version

my personal device is running with 5.0 so in that it is working fine

but Genymotion with version 4.3 so I am getting issue on that

with updated version of Genymotion 5.0 it is working fine

**Comment by wangmengyan95** [comment]
Hi @siddhpuraamitr, it seems we have some issue with gradle dynamic version #347. Could you not use dynamic version and try again?
Thanks.

**Comment by wangmengyan95** [comment]
Hi @siddhpuraamitr, I think it is the same issue with #355. We have fixed that issue and pushed to master. It will be shiped in next relase.
