### ISSUE TITLE
no /1/ in api.parse.com

### ISSUE THREAD

**Issue by AndroidGecko** [ParsePlatform/Parse-SDK-Android#352]
I have a very strange issue.
When running a very simple project from scratch with :
```
    Parse.enableLocalDatastore(this);
    Parse.initialize(this);
    ParseObject testObject = new ParseObject("TestObject");
    testObject.put("foo", "bar");
    testObject.saveInBackground();
```

everything works fine
the request is made to 
https://api.parse.com/1/classes/TestObject
and everything works fine

However if I try to integrate my existing app and place same code inside custom application (+keys in manifest) the api call fails with 404. Reason being that it pokes
https://api.parse.com/classes/TestObject

notice lack of /1/ 

If I manually catch above request in proxy and re-execute it with same data, it passes.

Any ideas why the /1/ is not being added?

**Comment by wangmengyan95** [comment]
Hi @AndroidGecko, thanks for your information. We do have a bug in the master branch about the lack of /1 issue you mention. If you are using the snapshot version, then it is fine. But if you are using the formal release verisn, could you tell us your version number and how do you change the manifest, thanks!

**Comment by wangmengyan95** [comment]
#356

**Comment by AndroidGecko** [comment]
Thanks @wangmengyan95 
Got it working with snapshot and
```
Parse.initialize(
        new Parse.Configuration.Builder(this).server("https://api.parse.com/1/").build());
```
also seems to be working on 1.12.0
after running 
```
gradle build --refresh-dependencies
```
since I was using 1.+ earlier

Thanks! 
btw - that is one great sdk!

**Comment by wangmengyan95** [comment]
@AndroidGecko thanks. The fix has been merged into master and it will be shipped in next release.
