### ISSUE TITLE
New example of #38

### ISSUE THREAD

**Issue by aphexcx** [ParsePlatform/Parse-SDK-Android#354]
Hi, I'm creating a new issue because I just found another instance of #38 and was not sure if it would notify the right people.
https://github.com/ParsePlatform/Parse-SDK-Android/issues/38#issuecomment-172790796

**Comment by wangmengyan95** [comment]
Hi @aphexcx, is it possible for you to give us a sample project to repo this issue? If not, could you tell us what Parse functions do you use in your app?
