### ISSUE TITLE
Need PPNS compiled by java 1.6

### ISSUE THREAD

**Issue by z7z8th** [ParsePlatform/Parse-SDK-Android#360]
We're making a product based on android 2.2, since android 2.2 boots up fast and image size is small.
But android 2.2 is compiled by java 1.6, the ppns-1.10.2.jar is compile with java 1.7, and can't work with android 2.2.
Could you help build a ppns jar with java 1.6?
Thanks a lot!
May you consider make ppns open source, since you've made so many good open source projects?

**Comment by z7z8th** [comment]
We're not using the android sdk to build our apk, but including the apk in Android open source tree to build the system.img.
BTW, can we decompile ppns.jar and compile it with java 1.6?

**Comment by Jawnnypoo** [comment]
PPNS is deprecated, so this is a wontfix @rogerhu
