### ISSUE TITLE
 java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by CorentinPacaud** [ParsePlatform/Parse-SDK-Android#362]
Hi,
I just made the update of the Parse Library from 1.9.2 to 1.12.0 and when I do a web request, I've got this error : java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
Everything works well in 1.9.2 but we can't do a web request in 1.12.0.
Does the new version change the Certificate or SSL or anything like that ?

PS : I followed the tutorial.

**Comment by wangmengyan95** [comment]
Hi @CorentinPacaud, the Certificate is related to your device, not our SDK. We do change our network stack from 1.9.2, but most of the changes is done before we open source our SDK. 
In your case, could you give us
1. Your test environment
2. Paste the parse logcat output of the device when you launch the application. You can enable parse log by adding `Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE)`.

**Comment by CorentinPacaud** [comment]
Hi,
I Just enabled Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE). But nothing appears in logcat.
In fact, we have a function that allow SSL Certifcate. Before update, this method was before Parse.initialize.... and worked well. After the Parse update, no request can be done.

01-28 11:54:55.006 11597-11758/fr.citylity.citylity.dev V/com.parse.GcmRegistrar: Received deviceToken <APA91bHDI6jSjh_drKa99Os0VgxHfcxe6zRc4AoSM0zzeN_cH6h5wM3-qOwLCDNQB3DqHizvtyuL7KcB0BZ4sh3OrriJttIGKQqUJyqgIN7BtCtSdwMWVkE35yW_XnEo_cx4K_y30mgO> from GCM.
01-28 11:54:55.041 11597-11625/fr.citylity.citylity.dev W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

BUT : if I put the method which allow SSL certificate after the Parse.initialize.. it's working.
So, maybe Parse change the SSL Certificate ?

Her my code : 

```
public class MyApp extends MultiDexApplication{

    @Override
    public void onCreate() {
        if (BuildConfig.DEBUG) {
            StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                    .detectDiskReads()
                    .detectDiskWrites()
                    .detectNetwork()   // or .detectAll() for all detectable problems
                    .penaltyLog()
                    .build());
            StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectLeakedSqlLiteObjects()
                            //  .detectLeakedClosableObjects()
                    .penaltyLog()
                    .penaltyDeath()
                    .build());
        }

        super.onCreate();

        if (BuildConfig.DEBUG)
            Log.i(TAG, "onCreate");



        HttpsTrustManager.allowAllSSL();
        Fabric.with(this, new Crashlytics());
        Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE);
        Parse.initialize(this, Constant.PARSE_APPLICATION_ID, Constant.PARSE_CLIENT_ID);
        ParseInstallation.getCurrentInstallation().saveInBackground();

    }
}

public class HttpsTrustManager implements X509TrustManager {

    private static TrustManager[] trustManagers;
    private static final X509Certificate[] _AcceptedIssuers = new X509Certificate[]{};

    @Override
    public void checkClientTrusted(
            java.security.cert.X509Certificate[] x509Certificates, String s)
            throws java.security.cert.CertificateException {

    }

    @Override
    public void checkServerTrusted(
            java.security.cert.X509Certificate[] x509Certificates, String s)
            throws java.security.cert.CertificateException {

    }

    public boolean isClientTrusted(X509Certificate[] chain) {
        return true;
    }

    public boolean isServerTrusted(X509Certificate[] chain) {
        return true;
    }

    @Override
    public X509Certificate[] getAcceptedIssuers() {
        return _AcceptedIssuers;
    }

    public static void allowAllSSL() {
        HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() {

            @Override
            public boolean verify(String arg0, SSLSession arg1) {
                return true;
            }

        });

        SSLContext context = null;
        if (trustManagers == null) {
            trustManagers = new TrustManager[]{new HttpsTrustManager()};
        }

        try {
            context = SSLContext.getInstance("TLS");
            context.init(null, trustManagers, new SecureRandom());
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (KeyManagementException e) {
            e.printStackTrace();
        }

        HttpsURLConnection.setDefaultSSLSocketFactory(context
                .getSocketFactory());
    }
}
```

**Comment by subodh-malgonde** [comment]
@CorentinPacaud Did you figure out what was wrong? I am having the same issue.

**Comment by CorentinPacaud** [comment]
Now it works but I don't why. Maybe my API co-worker change SSL or maybe I call allowSSL after Parse.initialize.

**Comment by baiju-emedsim** [comment]
I have used your above code " compile 'com.parse:parse-android:1.13.1'", "AndroidStudio version 2.3.3", "targetSdkVersion 25",but still getting the error "detailMessage:java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.". How you are able to resolve this error.Can you please paste your latest working code.
