### ISSUE TITLE
ParseCrashReporting via gradle

### ISSUE THREAD

**Issue by batkov** [ParsePlatform/Parse-SDK-Android#363]
Hi,

Not sure whether it is good place to ask, but how do I connect ParseCrashReporting via gradle.
I found some third party solutions for this, but I want to be sure that I'm using last version from Parse.

Search on google and mvncental doesn't help.

UPD: 
I mean something like 
``` 
compile 'com.parse:parse-crash-reporting:___'
```
not via downloaded jar.

Thanks

**Comment by wangmengyan95** [comment]
Hi @batkov, we are sorry but we have deprecated CrashReporting. You can check the detail in #247.
