### ISSUE TITLE
ParseFacebookUtils.getSession

### ISSUE THREAD

**Issue by sagaratalatti** [ParsePlatform/Parse-SDK-Android#366]
The latest SDK does not use ParseFacebookUtils.getSession() I tried to find the solution from online. There has been no documentation for that. As facebook has also started using TokenAccess instead of Session in their latest sdk

**Comment by wangmengyan95** [comment]
Hi @sagaratalatti , we use this repo to track Parse Android SDK issue. Could you open your issue under [ParseFacebookUtils](https://github.com/ParsePlatform/ParseFacebookUtils-Android)?

**Comment by grantland** [comment]
`com.facebook.Session` is from facebook-android-sdk v3, but was deprecated in v4. To support this we publish both v3 and v4 ParseFacebookUtils libraries: http://search.maven.org/#search%7Cga%7C1%7Cparsefacebookutils
