### ISSUE TITLE
ParsePushWakefulBroadcastReceiver would be nice

### ISSUE THREAD

**Issue by celiovasconcelos** [ParsePlatform/Parse-SDK-Android#369]
Hi Guys,

It would be nice to have a `ParsePushWakefulBroadcastReceiver` class.
Is that possible?

Thank you very much.

**Comment by grantland** [comment]
Unfortunately `WakefulBroadcastReceiver` is part of the Android Support Library, so we can't do this without forcing a dependency on that library. With this said, the basic use case of `WakefulBroadcastReceiver` is to hand off work to a service that holds a wakelock until complete, which you can still use by implementing a receiver on your own.

**Comment by Jawnnypoo** [comment]
I think this one can be closed as a wontfit @rogerhu
