### ISSUE TITLE
ParseObject's isDataAvailable containing wrong value?

### ISSUE THREAD

**Issue by DeDuckProject** [ParsePlatform/Parse-SDK-Android#370]
This actually looks similar to an issue in the iOS branch (https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/249).
I want the fetch some ParseObjects and do some action when they all arrive, so inside every fetch's *done* function I call an *update* which checks if all the objects in question are indeed fetched (using *isDataAvailable* function.
currRoute and currTask get their values from pointers in currentItem, but when I check their isDataAvailable value right after the getParseObject its true somehow.
at the moment i've worked around this problem using fetchAllIfNeededInBackground, but I still find it disturbing.

    currRoute  = currentItem.getParseObject("routePointer");
    currTask  = currentItem.getParseObject("taskPointer");
    currRoute.fetchIfNeededInBackground(new GetCallback<ParseObject>() {
           @Override
           public void done(ParseObject object, ParseException e) {
               initFetchListener.update();
           }
       });
    currTask.fetchIfNeededInBackground(new GetCallback<ParseObject>() {
           @Override
           public void done(ParseObject object, ParseException e) {
               initFetchListener.update();
           }
       });

**Comment by grantland** [comment]
Correct me if I'm wrong, but is this your current situation?

* You have called `currentItem.fetchInBackground()`
* The code above is executed after the `fetch` is completed
* You're expecting `currentItem["routePointer"]` and `currentItem["taskPointer"]` to be fully available, but `isDataAvailable` is returning `false`

If this is true, things are working as expected. Nested items are not returned/fetched by default when querying/fetching. The only way you can specify them to be returned is via `ParseQuery#include(key)` and it's not possible via `fetch`.

If this isn't the case, could you clarify your issue more? A failing unit test or a small working project that repros your issue would be best.

**Comment by DeDuckProject** [comment]
On the contrary, after calling currentItem.fetchInBackground() I don't expect the nested items to be fetched, and this is why I call fetchIfNeededInBackground() for both currRoute and currTask.
The problem is that when I put a breakpoint before the fetchIfNeededInBackground() line and check the contents of currRoute's state (as a ParseObject) it says isComplete=true.

inside my update() function I check every ParseObject's isDataAvailable to determine if all fetches are done before extracting data from the nested elements. the problem is that the check turns out to be positive even before currRoute has been fetched.

for reference, here's update()

     public boolean update(){
        for (ParseObject item : itemList){
            if (!item.isDataAvailable())
                return false;
        }
        for (BasicCallback callback: callbacks){
            if (callback!=null){
                callback.done();
            }
        }
        return true;
    }

where itemList contains currRoute and currTask.

Thanks for the quick reply by the way!
cheers

**Comment by grantland** [comment]
Could you provide a complete code sample from receiving `currentItem`?

**Comment by DeDuckProject** [comment]
sure.

At first, I update a "global variable" with the currentItem. this happens when selecting the item from a list:

    @Override
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
            faActivity.getEnvironmentObjects().setCurrentNotification((ParseObject) parent.getItemAtPosition(position)); //put item in global var
        viewItem((ParseObject)parent.getItemAtPosition(position)); //open view item fragment
    }

inside EnvironmentObjects:
        public void setCurrentNotification(ParseObject currentNotification) {
        this.currentNotification = currentNotification;
    }

the item was first fetched when initiating the list in the adapter as so:

    public View getItemView(ParseObject object, View v, ViewGroup parent) {
    ParseObject task = object.getParseObject("taskPointer");
                    if (task!=null) task.fetchIfNeededInBackground(new GetCallback<ParseObject>() {
                        @Override
                        public void done(ParseObject object, ParseException e) {
                            //task fetched
                            final ParseObject task = object;
                            final ParseUser askingUser = object.getParseUser("createdBy");
                            if (askingUser!=null) askingUser.fetchIfNeededInBackground(new GetCallback<ParseObject>() {
                                @Override
                                public void done(ParseObject object, ParseException e) {
                                    //asking user fetched from Parse.com
                                     String name = askingUser.getString("firstName");
                                     String itemName = task.getString("itemName");
                                    textView.setText(name + itemName);
                                }
                            });
                        }
                    });
    }

inside the new fragment I get the currentItem from EnvironmentObjects (reminder, it has already been fetched to show on list)
    currentItem =this.faActivity.getEnvironmentObjects().getCurrentNotification();

followed by this:
    
    currRoute  = currentItem.getParseObject("routePointer");
    currTask  = currentItem.getParseObject("taskPointer");
    currRoute.fetchIfNeededInBackground(new GetCallback<ParseObject>() {
           @Override
           public void done(ParseObject object, ParseException e) {
               initFetchListener.update();
           }
       });
    currTask.fetchIfNeededInBackground(new GetCallback<ParseObject>() {
       @Override
       public void done(ParseObject object, ParseException e) {
           initFetchListener.update();
       }
       });

**Comment by grantland** [comment]
Could you simplify your code into a small reproducible project? There's too many things going on with the code you posted to really debug this easily.

**Comment by DeDuckProject** [comment]
Unfortunately I cannot do that at the moment. I hope I can make it happen in the near future :)

**Comment by grantland** [comment]
Please let us know when you do
