### ISSUE TITLE
Getting illegal argument exception all of a sudden

### ISSUE THREAD

**Issue by Mukul-Sharma** [ParsePlatform/Parse-SDK-Android#373]
java.lang.IllegalArgumentException: invalid type for ParseObject: class org.json.JSONArray

Getting this exception all of a sudden when calling cloud code function. Doesn't even hit the servers. so no cloud side issues. Could you tell what's the issue here?  And also tried passing directly char[] in map, still getting same exception. Strange.
            
            JSONArray passArray = new JSONArray();
            for (int i = 0; i < password.length; i++) {
                passArray.put(i, Character.toString(password[i]));
            }

            HashMap<String, Object> params = new HashMap<String, Object>(2);
            params.put(PASSWORD, passArray);
            params.put(EMAIL, email);

            ParseCloud.callFunctionInBackground(LOGIN_FUNCTION_NAME, params, new FunctionCallback<String>() {
                @Override
                public void done(String result, ParseException e) {
                    if (e != null) {
                        try {
                            JSONObject object = new JSONObject(e.getMessage());
                            ParseException exception = new ParseException(object.getInt("code"), object.getString("message"));
                            logInCallback.done(null, exception);
                        } catch (JSONException j) {
                            j.printStackTrace();
                            e.printStackTrace();
                            logInCallback.done(null, e);
                        }
                    } else {
                        ParseUser.becomeInBackground(result, logInCallback);
                    }
                }
            });

**Comment by Mukul-Sharma** [comment]
Thanks for your answer. I have been trying to create the report steps but couldn't and its really head scratching process. The same piece of code have been working alright till now on v 1.12.0 and haven't changed anything. So i really cant tell what hit me. So I'm just here to ask the experts who are contributing more to get me in the right direction.

**Comment by grantland** [comment]
Aside from repro steps, a full stack trace would help.

**Comment by Ishimilated** [comment]
I'm getting the same error after updating the SDK to the newest version (1.13.1). I have a cloud code which takes a JSONArray as an argument. All of a sudden the cloud function doesn't get called any more and I get an IllegalArgumentException with the following stacktrace:

```W/System.err: com.parse.ParseException: java.lang.IllegalArgumentException: invalid type for ParseObject: class org.json.JSONArray
W/System.err:     at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:114)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:146)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5748)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)
W/System.err: Caused by: java.lang.IllegalArgumentException: invalid type for ParseObject: class org.json.JSONArray
W/System.err:     at com.parse.ParseEncoder.encode(ParseEncoder.java:136)
W/System.err:     at com.parse.ParseEncoder.encode(ParseEncoder.java:97)
W/System.err:     at com.parse.ParseRESTCommand.<init>(ParseRESTCommand.java:138)
W/System.err:     at com.parse.ParseRESTCloudCommand.<init>(ParseRESTCloudCommand.java:22)
W/System.err:     at com.parse.ParseRESTCloudCommand.callFunctionCommand(ParseRESTCloudCommand.java:28)
W/System.err:     at com.parse.ParseCloudCodeController.callFunctionInBackground(ParseCloudCodeController.java:28)
W/System.err:     at com.parse.ParseCloud$1.then(ParseCloud.java:64)
W/System.err:     at com.parse.ParseCloud$1.then(ParseCloud.java:60)
W/System.err:     at bolts.Task$15.run(Task.java:917)
W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
W/System.err:     at bolts.Task.completeAfterTask(Task.java:908)
W/System.err:     at bolts.Task.continueWithTask(Task.java:715)
W/System.err:     at bolts.Task.continueWithTask(Task.java:726)
W/System.err:     at bolts.Task$13.then(Task.java:818)
W/System.err:     at bolts.Task$13.then(Task.java:806)
W/System.err:     at bolts.Task$15.run(Task.java:917)
W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
W/System.err:     at bolts.Task.completeAfterTask(Task.java:908)
W/System.err:     at bolts.Task.continueWithTask(Task.java:715)
W/System.err:     at bolts.Task.continueWithTask(Task.java:690)
W/System.err:     at bolts.Task.onSuccessTask(Task.java:806)
W/System.err:     at bolts.Task.onSuccessTask(Task.java:796)
W/System.err:     at bolts.Task.onSuccessTask(Task.java:830)
W/System.err:     at com.parse.ParseCloud.callFunctionInBackground(ParseCloud.java:60)
W/System.err:     at com.parse.ParseCloud.callFunctionInBackground(ParseCloud.java:99)
W/System.err: 	... 14 more```

**Comment by Ishimilated** [comment]
I get the same error in 1.13.0 and 1.12.0, but not in 1.11.0. Something must have broken between 1.11.0 and 1.12.0.

**Comment by ankurgecr** [comment]
Here are the steps or repro.

Code: 
```
HashMap<String, Object> params = new HashMap<>();
params.put("myParam1", new JSONObject()); //any param with JSONObject or JSONArray type
ParseCloud.callFunctionInBackground("my_cloud_function", params, new FunctionCallback<Object>() {
            @Override
            public void done(Object arg0, ParseException arg1) {
                if (arg1 == null) {
					System.out.println("-- callFunctionInBackground::succeed --");
				} else {
					System.out.println("-- callFunctionInBackground::failed --");
                    arg1.printStackTrace();
                }
            }
        });
```

**Case 1:**

> Compile the code with 'com.parse:parse-android:1.10.3' or lower version.

**Output:**
`-- callFunctionInBackground::succeed --`

**Case 2:**

> Compile the code with 'com.parse:parse-android:1.12.0' or newer version.

**Output:**
```
-- callFunctionInBackground::failed --
com.parse.ParseException: java.lang.IllegalArgumentException: invalid type for ParseObject: class org.json.JSONObject
.
.
```

@parse-github-bot or any other moderator, please chk and reopen the issue if necessary.
Also put a comment if I am not clear enough to explain.

**Comment by caltv** [comment]
I'm seeing the same issue

**Comment by muneeshseedoc** [comment]
I am having the same issue

**Comment by sprabs** [comment]
@ankurgecr @ankurgecr @Mukul-Sharma @muneeshseedoc @caltv @Ishimilated   

I'm running into this issue now as well. Same situation (making a Cloud Code with one of the input parameters as a JSONArray). Did you guys come up with a workaround?

**Comment by ankurgecr** [comment]
@sprabs, I haven't found any proper solution yet. So, currently converting JSON to String parameter and inverse on Cloud side.

**Comment by muneeshseedoc** [comment]
Parse has changed ParseEncoder.java:
They removed following block in latest sdk:
 **if (object instanceof JSONArray) {
        JSONArray array = (JSONArray) object;
        JSONArray json = new JSONArray();
        for (int i = 0; i < array.length(); ++i) {
          json.put(encode(array.opt(i)));
        }
        return json;
      }**

while it was in V1.10.2

**Comment by sprabs** [comment]
I best solution is to pass it in as a Map.

**Comment by muneeshseedoc** [comment]
so use sdk library and add following code in  **public Object encode(Object object)** in ParseEncoder.java:

  if (object instanceof JSONArray) {
        JSONArray array = (JSONArray) object;
        return array.toString();
      }
      if (object instanceof JSONObject) {
        JSONObject obj = (JSONObject) object;
        return obj.toString();
      }

//it will stringify json array n object

**Comment by Ishimilated** [comment]
@muneeshseedoc I tried your code and I don't get the illegal argument exception any more, but the cloud code doesn't get called either. Something else must still be broken.

**Comment by keyuls** [comment]
Anyone has find solution for this? Facing same problem while passing JsonObject from Android to cloud code.

**Comment by novo-dimaporo** [comment]
Use JSONArray instead. Then you can still ready it as Array on Cloud.
