### ISSUE TITLE
fetchAllInBackground's callback doesn't fire if fetch isn't needed?

### ISSUE THREAD

**Issue by DeDuckProject** [ParsePlatform/Parse-SDK-Android#375]
Hi,
This might be kind of a follow-up to my latest issue (https://github.com/ParsePlatform/Parse-SDK-Android/issues/370) but I think its a different problem.
When doing a regular fetchInBackground for a ParseObject, the callback's *done* function fires even if the object didn't need any fetching.
However, when using fetchAllInBackground for a list of object, I would expect to see the same behavior, but the opposite happens: if all of the objects are already fetched the callback doesn't fire. This is annoying because I have to try working around too much...
any info about this?
Thanks,
DD

**Comment by grantland** [comment]
Could you clarify the version of the SDK you're using and whether or not LDS is enabled?

**Comment by DeDuckProject** [comment]
using this SDK:
    compile 'com.parse.bolts:bolts-android:1.+'
    compile 'com.parse:parse-android:1.13.0'

LDS is not used. However, I have enabled LDS by running:
    Parse.enableLocalDatastore(this);
but haven't called any other LDS functions during the runtime of the app.
