### ISSUE TITLE
Extended Subclasses Error - Failed to create instance of subclass.

### ISSUE THREAD

**Issue by asilarslan** [ParsePlatform/Parse-SDK-Android#379]
I have been create a Custom class like Word and I am using subclass like this [http://blog.parse.com/announcements/parse-on-android-just-got-classier/](this)
```java 
ParseQuery<Word> query = ParseQuery.getQuery(Word.class);
        query.findInBackground(new FindCallback<Word>() {
            @Override
            public void done(List<Word> objects, ParseException e) {
                if (e == null) {
                    Word word = wordList.get(0);
                } else {
                    Log.d("notretreive", "Error: " + e.getMessage());
                }
            }
        });
```
But get error
Error: java.lang.RuntimeException: Failed to create instance of subclass.

**Comment by asilarslan** [comment]
disable this line  `//Parse.enableLocalDatastore(this);` working fine but why is not working enable this line?

**Comment by grantland** [comment]
Could you post full code samples of your Parse initialization along with subclass registration, your query, your `Word` class, and the stack trace?

**Comment by asilarslan** [comment]
sure

```java
public class App extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        // [Optional] Power your app with Local Datastore. For more info, go to
        // https://parse.com/docs/android/guide#local-datastore
        //Parse.enableLocalDatastore(this);// If this line disable, work fine

        Parse.initialize(this, getString(R.string.parse_application_id), getString(R.string.parse_client_key));
        ParseObject.registerSubclass(Word.class);
        ParseObject.registerSubclass(...);
        ParseObject.registerSubclass(...);
        ParseObject.registerSubclass(...);
    }
}
```
```java
@ParseClassName("Word")
public class Word extends ParseObject implements Serializable {
    private String objectId = "objectId";

    public Word(){

    }

    public String getObjectId() {
        return getString(objectId);
    }

...

}
```
```java
 ParseQuery<Word> query = ParseQuery.getQuery("Word");
        query.findInBackground(new FindCallback<Word>() {
            @Override
            public void done(List<Word> wordList, ParseException e) {
                if (e == null) {
                    
                ....

                } else {
                    Log.d("notretreive", "Error: " + e.getMessage());
                }
            }
        });
```

**Comment by grantland** [comment]
Also your full stack trace?

**Comment by zqqq** [comment]
`        Parse.initialize(this, getString(R.string.parse_application_id), getString(R.string.parse_client_key));
        ParseObject.registerSubclass(Word.class);
        ParseObject.registerSubclass(...);
        ParseObject.registerSubclass(...);
        ParseObject.registerSubclass(...);`


Call ParseObject.registerSubclass(YourClass.class) in your Application constructor before calling Parse.initialize(). The following code sucessfully implements and registers the Armor subclass of ParseObject:

`        ParseObject.registerSubclass(Word.class);
        ParseObject.registerSubclass(...);
        ParseObject.registerSubclass(...);
        ParseObject.registerSubclass(...);
Parse.initialize(this, getString(R.string.parse_application_id), getString(R.string.parse_client_key));
`

**Comment by fredsvanelli** [comment]
I'm having the same problem with Parser Server. And I'm registering the Subclass before Parse.initialize

"java.lang.RuntimeException: Failed to create instance of subclass."

```
public class App extends Application
{

	@Override
	public void onCreate() {
		super.onCreate();
        
		ParseObject.registerSubclass(Place.class);
		Parse.initialize(new Parse.Configuration.Builder(this)
						.applicationId("...")
						.server("...")
                        .enableLocalDataStore() // if this is disabled, it works!
						.build()
		);
	}
}
```
If I remove the line ".enableLocalDataStore()", it works fine. Coul'd this be some incompatibility?

**Comment by waqary705** [comment]
Same Issue is with me I anyone found please me

**Comment by nielswd** [comment]
Same issue here. (works fine without enableLocalDataStore().

Is there any solutions?

**Comment by nielswd** [comment]
Okay, I figured out the problem. If someone is still having trouble here,
if you have          
```
public String getObjectId() {
        return getString(objectId);
    }
```

just delete it. It's useless and it breaks everything.

**Comment by maravilhosinga** [comment]
Resolved my issue, thanks 
I removed these lines

`@Override
    public boolean equals(Object o) {
        if(TextUtils.equals(this.getObjectId(),((User)o).getObjectId())){
            return true;
        } else {
            return false;
        }
    }*`
