### ISSUE TITLE
Can I continue use Parse SDK after migrating Parse to my own hosting?

### ISSUE THREAD

**Issue by yeahio-com** [ParsePlatform/Parse-SDK-Android#381]
Hello,

As the title said, I wonder if I can continue use Parse SDK.
If yes, what should I do to point my apps to new hosting?

**Comment by egorvas** [comment]
Yeah +1. Would like to see method Parse.server() such as in JS library

**Comment by iulianvarzaru** [comment]
Yeah you can use it with your own Parse Server hosting, just create the initialization like this:

```
Parse.Configuration configuration = new Parse.Configuration.Builder(this)
                .applicationId("Your Application ID")
                .clientKey("Your Client Key")
                .server("Your Server Url")
                .build();
Parse.initialize(configuration);
```

Note that your server url should end in `/` like `http://localhost:1337/parse/` and you should have defined an client key inside your server file.

**Comment by yeahio-com** [comment]
Yes, this works. But I have another issue when migrating my existing Parse backend to my own backend.  I have photos on Parse, but after migrating to my own backend, the photo field is changed to url (string). I am not sure if my photos were moved to my backend or not. Any ideas?

**Comment by iulianvarzaru** [comment]
There is a long discussion about the [ParseFile](https://github.com/ParsePlatform/parse-server/issues/8) , at this moment there is no migration for the files hosted on Parse and that's why you have an URL.

**Comment by grantland** [comment]
Thanks for stepping in @iulianvarzaru! I'll be closing this as resolved.
