### ISSUE TITLE
Bad json response error.

### ISSUE THREAD

**Issue by viktor-skarlatov** [ParsePlatform/Parse-SDK-Android#382]
Hi guys,

I believe the the following code in your migration blog is wrong:
Parse.initialize(new Parse.Configuration.Builder(myContext)
    .applicationId("YOUR_APP_ID")
    .clientKey("YOUR_APP_CLIENT_KEY")
    .server("http://localhost:1337/parse").build()
);

The problem is the "/parse" at the end of the url. Your Android SDK truncates that part and the ParseRESTQueryCommand ends up with a url of "http://localhost/login" instead of "http://localhost/parse/login" which results in a "Bad json response" error.

After passing the original url to ParseRESTCommand.createUrl(), the resulting URL is truncated.

**Comment by iulianvarzaru** [comment]
I am getting the same response from the sdk.

My Parse initialization:
```
Parse.Configuration configuration = new Parse.Configuration.Builder(getApplicationContext())
                .applicationId(Constants.PARSE_APP_ID)
                .clientKey(Constants.PARSE_REST_KEY)
                .server(Constants.PARSE_SERVER)
                .build();
Parse.initialize(configuration);
Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE);
```

My Parse Server is located at https://api.frimba.com/cars . This is the log I am getting for this:

```
V/com.parse.ParseRequest: Request failed. Waiting 2616 milliseconds before attempt #2
V/com.parse.ParseRequest: Request failed. Waiting 5232 milliseconds before attempt #3
V/com.parse.ParseRequest: Request failed. Waiting 10464 milliseconds before attempt #4
D/MAIN: Error: bad json response
```

and if I put the server https://api.frimba.com/cars/ I get : 
`D/MAIN: Error: unauthorized`

**Comment by iulianvarzaru** [comment]
You should add an `/` to your server url and have a corresponding clientKey on your server file.

`.server("http://localhost:1337/parse/").build()`

**Comment by viktor-skarlatov** [comment]
Yeah I guess that works but the code example is misleading. I lost some time debugging before I found out what was wrong. Also the "Bad json response" message is not really helpful.

**Comment by iulianvarzaru** [comment]
Yes, you can add an ParseNetworkInterceptor and figure it out, thats what I did :+1:

**Comment by grantland** [comment]
Thanks for stepping in @iulianvarzaru (again)! I'll be closing this as resolved.

@viktor-skarlatov Feel free to send a PR with updated docs.
