### ISSUE TITLE
Unavailability of PPNSService in the latest ParseSDK

### ISSUE THREAD

**Issue by tfKamran** [ParsePlatform/Parse-SDK-Android#389]
I read about `PPNS.jar` [here](https://github.com/ParsePlatform/Parse-SDK-Android/issues/35#issuecomment-133043237). I see the way Parse SDK is added in the project has changed, which has nothing to do with manually downloading JARs anymore.

I tried adding the Parse SDK in a project as a dependency in the gradle file as directed in the documentation, but I am unable to find the class `PPNSService`. As far as I understand it is a fallback in case GCM doesn't work on a device for whatever reason.

What does the absence of that class mean? Does it mean Parse Push Messaging does not work without GCM anymore?

**Comment by grantland** [comment]
PPNSService isn't necessary unless you're utilizing PPNS, our outdated push service from before GCM. If you wish to utilize PPNS, you need to manually include the jar as stated in the your link. Otherwise, we highly recommend moving to GCM.
