### ISSUE TITLE
Parse not assuming new ApplicationID and ClientKey when updating app

### ISSUE THREAD

**Issue by josemssilva** [ParsePlatform/Parse-SDK-Android#391]
This is a very odd issue. Have anyone reported this yet? I update my signed app with a more recent signed version, with different ApplicationId and ClientKey, and the device is not registered in Parse Application.

**Comment by josemssilva** [comment]
I had the need to change the Parse Application that feeds my Android app, therefore I needed to change Application ID and Client Key associated. And i noticed that previous users, when updating the app, couldn't subscribe to the new Parse Application, only fresh installs allowed it.

**Comment by grantland** [comment]
This is not a Parse SDK issue, so I'll be closing this. 

You're users are using older versions of your application that point to the old Parse application. These users will not use the new Parse application until they update to your newest application version.

**Comment by josemssilva** [comment]
> And I noticed that previous users, when updating the app, couldn't subscribe to the new Parse Application, only fresh installs allowed it.

As I said, when users *update the Android app to it's newer version*, which uses the *new* Parse app, with different AppId and Client Key, they don't subscribe to the new Parse app. 

Why can't this be a Parse SDK issue?

**Comment by grantland** [comment]
Could you describe what you mean by "subscribe"?

Changing your Parse application is not supported so weirdness might occur. For instance, client persisted objects would freak out since those objectIds wouldn't exist.

**Comment by josemssilva** [comment]
That's exactly what I was looking for. So, I can't change Installation? Or at least update it, to a new Parse Application? 

Imagine the scenario where I want to provide different Parse Applications to different versions of my Android App. Those who update the Android App to the newer version can't make the shift to the new Parse Application. Is this the desired behaviour?

**Comment by grantland** [comment]
Unfortunately this is not supported for the reasons I described above. I'll be closing this issue since it's working as expected.
