### ISSUE TITLE
Bug in server/Parse.initialize

### ISSUE THREAD

**Issue by rogerhu** [ParsePlatform/Parse-SDK-Android#393]
According to:

https://parse.com/docs/server/guide

```java
Parse.initialize(new Parse.Configuration.Builder(this)
                .server("https://parse-testing-port.herokuapp.com/parse")
```

If I add LogCat interceptor, I see the URL as (assuming I'm posting a Message object):

Url : https://parse-testing-port.herokuapp.com/classes/Message

The workaround is to set PARSE_MOUNT to be '/' to avoid this issue (https://github.com/codepath/android_guides/wiki/Configuring-a-Parse-Server).

**Comment by jpmassena** [comment]
I worked around this issue this way:

parse-server mount point: /my-app
```
Parse.initialize(new Parse.Configuration.Builder(this)
                .server("https://parse-server-url.com/my-app/)
```

Adding the / at the end sends the URLs correctly.

**Comment by liquiddandruff** [comment]
Confirm that adding the / at the end fixes this. Thanks a lot to codepath for the guide.

**Comment by grantland** [comment]
Closing as resolved.

**Comment by rogerhu** [comment]
Fix is here: https://github.com/ParsePlatform/Parse-SDK-Android/pull/436/files
