### ISSUE TITLE
Unable to setup multiple push sources with parse

### ISSUE THREAD

**Issue by ehwright** [ParsePlatform/Parse-SDK-Android#396]
I am working towards migrating my users off parse.  My app now initialises with parse but also registers with gcm in a separate activity.

After reading  the documentation on the parse site I inserted this into the manifest file:

<meta-data android:name="com.parse.push.gcm_sender_id"
           android:value="id:YOUR_SENDER_ID" />;

Replacing the sender id with my gcm app id.  This looked like all was required for what I need.

When I did this, the device successfully registered on parse first, but once it registered for gcm outside of parse, the device token changed to rubbish and no messages sent to that device.

I then tried setting up my app id and key in parse settings, and setting the gcmSenderId from the app via the installation.  This caused the deviceToken to be updated with the latest gcm token created from outside parse.  However, the gcmSenderId field remains undefined and no messages go to the device.

**Comment by grantland** [comment]
We only support the use case where the Parse SDK is the only thing registering with GCM. Adding your own registration code is unsupported.
