### ISSUE TITLE
Localdatastore does not work with personal parse server

### ISSUE THREAD

**Issue by AtomicSpider** [ParsePlatform/Parse-SDK-Android#398]
**Current Code**
        
        //Enable Local Datastore
        Parse.enableLocalDatastore(this);

        //initialize Parse with Parse Server
        Parse.initialize(this, getResources().getString(R.string.parse_app_id), getResources().getString(R.string.parse_client_id));

**Personal Server Code**

        //Enable Local Datastore
        Parse.enableLocalDatastore(this);

        //initialize Parse with Heroku Server
        Parse.initialize(new Parse.Configuration.Builder(this)
                        .applicationId(getResources().getString(R.string.parse_app_id))
                        .clientKey(getResources().getString(R.string.parse_client_id))
                        .server(getResources().getString(R.string.parse_server_url)).build()
        );

App works fine till I replace it with the personal server code, the app crashes while querying from local datastore which is odd. crashes at the code below:

        localQuery.fromLocalDatastore();

**Comment by jpmassena** [comment]
hey @AtomicSpider,

With Personal Server code, you have to enable the local data store like this:

```
Parse.initialize(new Parse.Configuration.Builder(context)
                .server(...)
                .applicationId(...)
                .enableLocalDataStore()
                .build());
```

with the **.enableLocalDataStore()** while "building" the configuration.

You can remove 
`Parse.enableLocalDatastore(this);`

**Comment by AtomicSpider** [comment]
@jpmassena Thanks a lot mate !!!

**Comment by bearprada** [comment]
@jpmassena you save my life

**Comment by allonmj** [comment]
would've been great to see this in the migration guide - you know, before I logged all of my users out of the app...
