### ISSUE TITLE
Migrate existing android app from parse to heroku

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/Parse-SDK-Android#399]
I have android app and i use this method to define parse Parse.initialize(this, "ApplicationKey", "ClientKey);

how to point my app to heroku server ?

**Comment by AtomicSpider** [comment]
Hi,
You can use this code:

    Parse.initialize(new Parse.Configuration.Builder(myContext)
    .applicationId("YOUR_APP_ID")
    .clientKey("YOUR_APP_CLIENT_KEY")
    .server("http://appname.herokuapp.com/parse")
    .build()
);
