### ISSUE TITLE
Future features to be implemented ?

### ISSUE THREAD

**Issue by Kiloreux** [ParsePlatform/Parse-SDK-Android#4]
Is there any list of features that needs to be implemented so we can help building those  ?

**Comment by grantland** [comment]
We're still working on publicizing larger features that we'd like help on, but once they're ready you'll be able to view them with the [help wanted][help-wanted] label. "Watching" this repository would be a good way to be notified when any of these come up.

With this said, I just posted a couple "good first task"/"help wanted" issues :smile: 

 [help-wanted]: https://github.com/ParsePlatform/Parse-SDK-Android/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

**Comment by Kiloreux** [comment]
@grantland  thank you , it's really interesting .

**Comment by grantland** [comment]
I'll be closing this for now, but stay tuned!

**Comment by Kiloreux** [comment]
:+1:
