### ISSUE TITLE
ParseUser: Cannot save parseuser that is not authenticated

### ISSUE THREAD

**Issue by jaytj95** [ParsePlatform/Parse-SDK-Android#404]
I see that many people have this issue, but the thing that baffles me is that the "ParseUser" I'm referring to is `ParseUser.getCurrentUser()`

```
carLikeQuery.getInBackground(carItem.getObjectId(), new GetCallback<ParseObject>() {
                                    @Override
                                    public void done(ParseObject object, ParseException e) {
                                        object.increment("likes");
                                        object.addUnique("usersWhoLike", ParseUser.getCurrentUser().getObjectId());
                                        object.saveInBackground(new SaveCallback() {
                                            @Override
                                            public void done(ParseException e) {
                                                if(e==null) {
                                                    Log.d("SAVE", "It worked!");
                                                } else {
                                                    Log.e("SAVE", "Fail " + e.getLocalizedMessage());
                                                }
                                            }
                                        });
                                    }
                                });


```

Tested scenarios:

A user can create a "Car" post and then like the post without problem

User 1 can create a "Car" post, but if User 2 tries to like it, the save fails with the error message.

Any word on this?

**Comment by grantland** [comment]
With the limited information provided it doesn't seem like a bug in the SDK, but that you're you're modifying a `ParseUser` under `car.usersWhoLike` that's not the current user. 

`ParseObject`s (including `ParseUser`s) do not try to save themselves unless they have been modified, aka "dirty". A `ParseUser` object also cannot be saved, unless it's the current user or else you'd receive this error.

If you end up digging into this enough and find it's an actual bug, please include the required information outlined in our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md).

**Comment by jaytj95** [comment]
I am trying to modify a `ParseObject `though. I am trying to add a ParseUser's objectId to an array that exists within a ParseObject. I am querying the ParseObject to get it ("Car"), then adding the current user's objectId, and then saving the ParseObject.

What I have also found is that THIS does not work either:
```

                                ParseQuery carLikeQuery = new ParseQuery("Car");
                                carLikeQuery.getInBackground(carItem.getObjectId(), new GetCallback<ParseObject>() {
                                    @Override
                                    public void done(ParseObject object, ParseException e) {
                                        object.increment("likes");
                                       //   object.addUnique("usersWhoLike", ParseUser.getCurrentUser().getObjectId());
                                        object.saveInBackground(new SaveCallback() {
                                            @Override
                                            public void done(ParseException e) {
                                                if(e==null) {
                                                    Log.d("SAVE", "It worked!");
                                                } else {
                                                    Log.e("SAVE", "Fail " + e.getLocalizedMessage());
                                                }
                                            }
                                        });
                                    }
                                });
```

**Comment by jaytj95** [comment]
@grantland I just created an entirely new class with the same class structure, and the app works as expected. I will say that this same code was working before this past weekend, and now it is not working. But when I created a new Parse Application and changed all my API Keys over to the new endpoint, the app started to work just fine without any code changes. Have you seen this before, or is this a bug?

Thank you for your time!

**Comment by grantland** [comment]
I can't say with the information provided. Most likely you're making modifications to the `ParseUser` somewhere though. The best way to check is checking `user.isDirty()` before calling `object.save()`.

FYI, I wouldn't recommend updating clients using one Parse application to another as they will fail to look up persisted `ParseObject`s such as the current user and installation on the new application where they do not exist.

**Comment by jaytj95** [comment]
I saw the source code for the ParseUser from somewhere:

```
void validateSave() {
        if (getObjectId() == null) {
            throw new IllegalArgumentException("Cannot save a ParseUser until it has been signed up. Call signUp first.");
        }

        if (!isAuthenticated() && isDirty()) {
            throw new IllegalArgumentException("Cannot save a ParseUser that is not authenticated.");
        }
    }
```
Doing the same kind of checking in my code reveals that the the currentUser is **AUTHENTICATED and NOT DIRTY.**

**Comment by grantland** [comment]
The problem wouldn't normally arise from the current user, but another user attached to the object tree that might be marked as dirty.

Would you be able to provide a repro project for this issue? Also, would you happen to have Local Datastore enabled or disabled?
