### ISSUE TITLE
TransformException: java.util.zip.ZipException: duplicate entry: com/parse/AbstractQueryController$1.class

### ISSUE THREAD

**Issue by ABhimsaria** [ParsePlatform/Parse-SDK-Android#406]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'. > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/parse/AbstractQueryController$1.class

Hey guys I am getting the above error all day long.. Had been trying with different version of Parse but of no use. Can SomeOne please help me out in getting these shit.

**Comment by ABhimsaria** [comment]
Hey Thank You for the documentation.
Issue has beed fixed.
So Closing these Thread.

**Comment by fathurrohmane** [comment]
What is the solution for this problem?
