### ISSUE TITLE
Wrong sort order when having multiple sort keys

### ISSUE THREAD

**Issue by cartierjf** [ParsePlatform/Parse-SDK-Android#407]
I'm trying to sort query results with 2 keys which are dates and it does not work. Here's the code of my query (if useful):
```java
ParseQuery<Deal> query = ParseQuery.getQuery(Deal.PARSE_CLASS_NAME);
query.whereEqualTo(Deal.RETAILER, User.getCurrentUser());
query.whereDoesNotExist(Deal.DELETED_AT);
query.whereGreaterThanOrEqualTo(Deal.END_TIME, now);
query.whereEqualTo(Deal.ACTIVE, true);
query.orderByAscending(Deal.END_TIME);
query.addDescendingOrder(Deal.UPDATED_AT);
query.setLimit(DEAL_LOAD_LIMIT);
query.setSkip(offset);
```
END_TIME is a date and updatedAt is, obviously, also a date. Here's are the results of the query, in order they are received (only END_TIME --- UPDATED_AT are printed):
```
deal: Thu Feb 25 18:30:00 EST 2016 --- Thu Feb 25 13:39:14 EST 2016
deal: Thu Feb 25 18:30:00 EST 2016 --- Thu Feb 25 16:36:45 EST 2016
deal: Thu Feb 25 18:30:00 EST 2016 --- Thu Feb 25 16:05:08 EST 2016
deal: Thu Feb 25 18:30:00 EST 2016 --- Thu Feb 25 16:05:22 EST 2016
deal: Thu Feb 25 18:30:00 EST 2016 --- Thu Feb 25 16:51:24 EST 2016
deal: Thu Feb 25 18:30:00 EST 2016 --- Thu Feb 25 16:17:11 EST 2016
deal: Thu Feb 25 18:30:00 EST 2016 --- Thu Feb 25 13:37:56 EST 2016
deal: Thu Feb 25 19:30:00 EST 2016 --- Thu Feb 25 16:53:00 EST 2016
```
As can by seen, the results are sorted fine by END_TIME, but UPDATED_AT is totally random. If I sort only by UPDATED_AT, the sorting is fine also. The problem seems to be with 2 sort keys only. I tried using `addAscendingOrder` instead of `orderByAscending` for the first sort key, but it does not change anything. My key values are good, I double-checked (and anyway it works in both cases when using only one sort key). The query works on iOS. I am using parse sdk 1.13.0, but I tried with 1.12.0 and 1.11.0 and I get the same result. Am I doing something wrong?

Thanks

**Comment by grantland** [comment]
From a cursory glance it doesn't seem like you're doing anything wrong. Could you enable network logging with https://github.com/ParsePlatform/ParseInterceptors-Android and paste the network request and response of this query?

Also could you add the following information:
* SDK Version
* Local Datastore enabled/disabled
* Code used to print

**Comment by cartierjf** [comment]
Oh well, I didn't know about ParseInterceptors. By intercepting the request/answer, I realized that the milliseconds of the endTimes were different. It works as expected. Thanks for your help!

This issue can be closed.

**Comment by grantland** [comment]
Awesome, glad to hear it's resolved!
