### ISSUE TITLE
Undefine device token android app: Need urgent help

### ISSUE THREAD

**Issue by rajujin1** [ParsePlatform/Parse-SDK-Android#412]
#145

ParseInstallation.getCurrentInstallation().saveInBackground(new SaveCallback() {
            @Override
            public void done(ParseException e) {
                String deviceToken = (String) ParseInstallation.getCurrentInstallation().get("deviceToken");
                Log.e("Q4U", "tbr i got device token as " + deviceToken);
                if (e == null)
                    Log.e("Q4U", "tbr i am null ");
                else
                    Log.e("Q4U", "tbr i am not null" + e.getMessage());
            }
        });

**Comment by rajujin1** [comment]
Application code:--

Parse.initialize(this, getResources().getString(R.string.PARSE_APP_ID),
                getResources().getString(R.string.PARSE_CLN_ID));
        ParseFacebookUtils.initialize(this);
        ParseInstallation.getCurrentInstallation().put("Unique_Id", AppGlobal.UNIQUE_ID);
        //Following is required so as to check the internet connectivity first time only.
        glbls.updateglbls();
        Parse.setLogLevel(Log.VERBOSE);

        ParsePush.subscribeInBackground("", new SaveCallback() {
            @Override
            public void done(ParseException e) {
                if (e == null) {
                    String deviceToken = (String) ParseInstallation.getCurrentInstallation().get("deviceToken");
                    Log.e("Q4U", "tbr 1 got device token as " + deviceToken);
                    Log.d(getClass().getSimpleName(), "tbr successfully subscribed to the broadcast channel.");
                } else {
                    Log.e(getClass().getSimpleName(), "tbr failed to subscribe for push", e);
                }
            }
        });

        ParseInstallation.getCurrentInstallation().saveInBackground(new SaveCallback() {
            @Override
            public void done(ParseException e) {
                String deviceToken = (String) ParseInstallation.getCurrentInstallation().get("deviceToken");
                Log.e("Q4U", "tbr 2 got device token as " + deviceToken);
                if (e == null)
                    Log.e("Q4U", "tbr i am null ");
                else
                    Log.e("Q4U", "tbr i am not null" + e.getMessage());
            }
        });

**Comment by rajujin1** [comment]
Full application code:
// Enable Local Datastore.
        Parse.enableLocalDatastore(this);

//        String  android_id = Settings.Secure.getString(getApplicationContext().getContentResolver(), Settings.Secure.ANDROID_ID);
        AppGlobal.UNIQUE_ID = getUniquePsuedoID();
        Parse.initialize(this, getResources().getString(R.string.PARSE_APP_ID),
                getResources().getString(R.string.PARSE_CLN_ID));
        ParseFacebookUtils.initialize(this);
        ParseInstallation.getCurrentInstallation().put("Unique_Id", AppGlobal.UNIQUE_ID);
        //Following is required so as to check the internet connectivity first time only.
        glbls.updateglbls();
        Parse.setLogLevel(Log.VERBOSE);

        ParsePush.subscribeInBackground("", new SaveCallback() {
            @Override
            public void done(ParseException e) {
                if (e == null) {
                    String deviceToken = (String) ParseInstallation.getCurrentInstallation().get("deviceToken");
                    Log.e("Q4U", "tbr 1 got device token as " + deviceToken);
                    Log.d(getClass().getSimpleName(), "tbr successfully subscribed to the broadcast channel.");
                } else {
                    Log.e(getClass().getSimpleName(), "tbr failed to subscribe for push", e);
                }
            }
        });

        ParseInstallation.getCurrentInstallation().saveInBackground(new SaveCallback() {
            @Override
            public void done(ParseException e) {
                String deviceToken = (String) ParseInstallation.getCurrentInstallation().get("deviceToken");
                Log.e("Q4U", "tbr 2 got device token as " + deviceToken);
                if (e == null)
                    Log.e("Q4U", "tbr i am null ");
                else
                    Log.e("Q4U", "tbr i am not null" + e.getMessage());
            }
        });

**Comment by rajujin1** [comment]
After enabling parse verbose level message getting following in the logcat:--

Cannot use GCM for push because the app manifest is missing some required declarations. Please make sure that these permissions are declared as children of the root <manifest> element:
03-04 10:35:10.715 2664-2664/com.ababies.interviewer.questions4you V/com.parse.ManifestInfo: Using none for push.

**Comment by l-kovachev** [comment]
My problem was that I was missing this permission in the manifest:

**\<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />**

Also I had to add meta-data just before \<service android:name="com.parse.PushService" /> :

**\<meta-data
            android:name="com.parse.APPLICATION_ID"
            android:value="YourParseApplicationID" />**

**\<meta-data
            android:name="com.parse.CLIENT_KEY"
            android:value="YourParseClientKey" />**

Now check if you can get the deviceToken. Also check your app dashboard in Parse if everything is ok.

**Comment by rogerhu** [comment]
Yep. Push can be complicated to  setup. :)
