### ISSUE TITLE
Is this sdk support both parse.com and own hosted parse server?

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/Parse-SDK-Android#423]
My existing application support Push Notification through parse.com. I'm doing the migration now. But I still want to support old version until the end of this year. So my question is if Parse-SDK-Android 1.13.0 still works in parse.com app?

Is there any updated tutorial for Parse-SDK-Android? The PushTutorial is two years old already. Thanks.

**Comment by zhouhao27** [comment]
My previous application with push notification is not working anymore after I upgrade to latest 1.13.0 (previous is 1.9.2). 

My code is:

    Parse.initialize(this, "xxxxxxx", "xxxxxxxx");

    ParsePush.subscribeInBackground("", new SaveCallback() {
      @Override
      public void done(ParseException e) {
        if (e == null) {
          Log.d("com.parse.push", "successfully subscribed to the broadcast channel.");
        } else {
          Log.e("com.parse.push", "failed to subscribe for push", e);
        }
      }
    });

Any idea? Thanks.

**Comment by conanoc** [comment]
Take a look at #197 
PS, I think you'd better change your title of this issue.

**Comment by rogerhu** [comment]
I have a wiki separately maintained here about push: http://guides.codepath.com/android/Push-Notifications-Setup-for-Parse
