### ISSUE TITLE
Parse session disappears while signup an anonymous user on android

### ISSUE THREAD

**Issue by ArrowCross** [ParsePlatform/Parse-SDK-Android#424]
Followed by Parse doc, I created an anonymous user while app is first launched.

```
...
Parse.initialize(this, APPLICATION_ID, CLIENT_KEY);
ParseUser.enableRevocableSessionInBackground();
if (ParseUser.getCurrentUser() == null) {
        ParseUser.enableAutomaticUser();
        ParseUser.getCurrentUser().increment("RunCount");
        ParseUser.getCurrentUser().saveInBackground();
```

In the parse core, it shows that a new "User" and "Session" row is successfully added.

```
...
ParseUser.getCurrentUser().setUsername("Leo");
ParseUser.getCurrentUser().setPassword("sasami");
ParseUser.getCurrentUser().signUpInBackground(new SignUpCallback() {
        @Override
        public void done(ParseException e) {
...
```

Then after I calling the "signUpInBackground" method, I found the just-added User row has been updated, but the just-added Session row was disappear. And consequently the user-related query and execution always returns an

> com.parse.ParseRequest$ParseRequestException: invalid session token

P.S. It doesn't matter if signup successfully or returned error. The Session row disappears anyway.
Sorry for the inconvenient typesetting. It's my first post here. I also posted this issue on StackOverFlow.

[http://stackoverflow.com/questions/36142509/parse-session-disappears-while-signup-an-anonymous-user-on-android](url)

**Comment by grantland** [comment]
`ParseUser.enableAutomaticUser()` shouldn't be within a conditional as it should either **always** be enabled or **never**.
