### ISSUE TITLE
Twitter OAuth failure - "Error parsing a meta element's content"

### ISSUE THREAD

**Issue by grantgumina** [ParsePlatform/Parse-SDK-Android#425]
*I posted this on the Parse Server project page and was recommended I move the issue to this project instead.*

I'm attempting to add Twitter authentication to my Android application, but I'm running into the following issue when I call the ParseTwitterUtils.logIn method. Via Logcat, I can see the following output:

```
03-21 13:19:32.775 24141-24141/com.vearlo I/chromium: [INFO:CONSOLE(8)] "The value "device-width;" for key "width" is invalid, and has been ignored.", source: https://api.twitter.com/oauth/authenticate?oauth_token=hrWTEAAAAAAAuLuOAAABU5rVEyg (8)
03-21 13:19:32.775 24141-24141/com.vearlo I/chromium: [INFO:CONSOLE(8)] "The value "1.0;" for key "initial-scale" was truncated to its numeric prefix.", source: https://api.twitter.com/oauth/authenticate?oauth_token=hrWTEAAAAAAAuLuOAAABU5rVEyg (8)
03-21 13:19:32.775 24141-24141/com.vearlo I/chromium: [INFO:CONSOLE(8)] "The value "1.0;" for key "maximum-scale" was truncated to its numeric prefix.", source: https://api.twitter.com/oauth/authenticate?oauth_token=hrWTEAAAAAAAuLuOAAABU5rVEyg (8)
03-21 13:19:32.776 24141-24141/com.vearlo I/chromium: [INFO:CONSOLE(8)] "Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.", source: https://api.twitter.com/oauth/authenticate?oauth_token=hrWTEAAAAAAAuLuOAAABU5rVEyg (8)

```

This line: `Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.",` seems to be the culprit.

Has anyone seen a similar issue? Facebook login works fine.

**Comment by grantland** [comment]
ParseTwitterUtils hasn't been touched for months, so this sounds like an issue with Twitter's API. 

For future reference this repository only deals with the core Parse SDK, so I'll be closing this issue. I suggest troubleshooting this with Twitter and if you're still having issues you should re-open an issue on the correct project: [ParseTwitterUtils-Android](https://github.com/ParsePlatform/ParseTwitterUtils-Android).

**Comment by LoungeKatt** [comment]
For future visitors (already redirected from the original issue):
https://github.com/parse-community/ParseTwitterUtils-Android/issues/26
