### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by firasalkafri** [ParsePlatform/Parse-SDK-Android#427]
Code in Application's OnCreate:

`Parse.initialize(new Parse.Configuration.Builder(getApplicationContext())
.applicationId(Config.PARSE_APP_ID)
.clientKey(Config.PARSE_APP_SECRET)
.server(Config.PARSE_SERVER)
.build());`

java.lang.IllegalAccessError: Method 'void bolts.Task.<init>()' is inaccessible to class 'bolts.TaskCompletionSource' (declaration of 'bolts.TaskCompletionSource' appears in /data/data/com.*************/files/instant-run/dex/slice-dependencies_de922f332ff77f1b9185f74d0d6d38e078592370-classes.dex)

Our app ran successfully on another device with the same specs but one level higher Android API (22 instead of 21)

**Comment by grantland** [comment]
It seems like you're missing the Bolts-Android dependency somehow. I'd double check your gradle configurations as well as your compiled binary to make sure those classes exist.

**Comment by firasalkafri** [comment]
@grantland I am using 'com.parse:parse-android:1.13.0', could it be dexing?

**Comment by grantland** [comment]
I'm not entirely sure what could be going wrong here, just that it's most likely a configuration issue rather than a bug in the SDK.

**Comment by firasalkafri** [comment]
@grantland this is really weird, I have tried cleaning the project and restarting the whole IDE, it just doesn't run on this device.

**Comment by firasalkafri** [comment]
Had to exclude bolts from facebook sdk in gradle

`        exclude group: 'com.parse.bolts',
                module: 'bolts-tasks'
        exclude group: 'com.parse.bolts',
                module: 'bolts-applinks';`

**Comment by kevinPoklinger** [comment]
same problem.

java.lang.IllegalAccessError: Method 'void bolts.Task.<init>()' is inaccessible to class 'bolts.TaskCompletionSource' (declaration of 'bolts.TaskCompletionSource' appears in /data/app/com.example.kevin.parse-1/split_lib_dependencies_apk.apk:classes2.dex)
![screen shot 2017-08-13 at 12 29 47 am](https://user-images.githubusercontent.com/26736256/29244685-92eac7b6-7fbe-11e7-9391-f8579c58e18d.png)
