### ISSUE TITLE
Query from LocalDataStore with group of pinned objects is not working for Role ACLs.  

### ISSUE THREAD

**Issue by trushit29** [ParsePlatform/Parse-SDK-Android#428]
I am using Parse SDK in my app. When app opens, all the objects fetched from Parse will be pinned to `fromLocalDatastore()`. 

Then in the app, every object will be fetched from **_Local DataStore_** only. `pinAllInBackground()` to **_Local DataStore_** is working fine. 

_But when I'm fetching records from **Local DataStore**, records which has particular **Role ACL set** are not fetched from **Local DataStore**. The **Role ACL** is set from Parse dashboard, and according to Role ACL set, app have to display the records from Local DataStore.  To display all records, I have to forcefully apply **`ignoreACLs()`** for each and every query to get all data I want to display in app._

**Comment by grantland** [comment]
Unfortunately role based ACLs are not supported by Local Datastore and we recommend to use `query#ignoreACLs()` for this situation: https://parse.com/docs/android/api/com/parse/ParseQuery.html#ignoreACLs()
