### ISSUE TITLE
Connection to parse server on localhost refused in android studio

### ISSUE THREAD

**Issue by shubham23596** [ParsePlatform/Parse-SDK-Android#439]
this code results in error that connection to localhost refused, i already given permission in android
manifest

//this is my code but failed to connect and save data
 
Parse.initialize(new Parse.Configuration.Builder(this)
            .applicationId("myAppId")
            .server("http://localhost:1337/parse")

            .build()
    );
    ParseObject score = new ParseObject("Score");
    score.put("username", "tommy");
    score.put("score", 199);
    score.saveInBackground(new SaveCallback() {
      @Override
      public void done(ParseException e) {

        if (e == null) {

          Log.i("SaveInBackground", "Successful");

        } else {

          Log.i("SaveInBackground", "Failed");
          e.printStackTrace();

        }

      }
    });

**Comment by shubham23596** [comment]
yes i have check all the three resources , i have also configured pass server but the request not send from android app , please help me

**Comment by bilthon** [comment]
localhost in this context will probably refer to your device's IP address, which is not what you want. You must instead specify the IP address of the server running the parse-server.
