### ISSUE TITLE
query.fromNetwork() not public

### ISSUE THREAD

**Issue by danielapsmaior** [ParsePlatform/Parse-SDK-Android#451]
Hi,
On #6 there's a discussion about turning query.fromNetwork() public, but I don't have that in the newest version. I'd like to know if it's been done or another way to implement elegantly the CACHE_ELSE_NETWORK with LocalDataStore active. 
Thanks

**Comment by grantland** [comment]
It's still up for grabs if you're up for it!

Let's keep discussion there, so I'll be closing this.
