### ISSUE TITLE
Remove ParseFile 10Mb limitation

### ISSUE THREAD

**Issue by aleksdresen** [ParsePlatform/Parse-SDK-Android#453]
Hey guys, we migrated to Parse Server and on iOS we can now use files larger than 10Mb. On Android however, we can't even create a file larger than 10Mb. We get this error when we run 

ParseFile video1 = new ParseFile("answer_1.mp4", video1ByteArray);

FATAL EXCEPTION: main Process: com.terre.android.terremoto, PID: 7919
                 java.lang.IllegalArgumentException: ParseFile must be less than 10485760 bytes

Our Parse Server supports files larger than 10Mb and on iOS everything works fine.

Is there anything we can do?

**Comment by grantland** [comment]
Can you post the full stack trace?

**Comment by aleksdresen** [comment]
Package Name,Crash Report Date And Time,Crash Report Millis Since Epoch,Device,Android OS Version,App Version Name,App Version Code,Exception Class Name,Exception Message,Throwing File Name,Throwing Class Name,Throwing Method Name,Throwing Line Number,Native Crash Library,Native Crash Location,Crash Link
com.kown.android.fundraiseonkown,2016-05-09T23:15:15Z,1462835715179,hammerhead,23,0.9.1,3,java.lang.IllegalArgumentException,ParseFile must be less than 10485760 bytes,ParseFile.java,com.parse.ParseFile,<init>,190,,,https://play.google.com/apps/publish?dev_acc=04052455048233046270#ErrorClusterDetailsPlace:p=com.kown.android.fundraiseonkown&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1462835715179&et=CRASH&ecn=java.lang.IllegalArgumentException&tf=ParseFile.java&tc=com.parse.ParseFile&tm=%3Cinit%3E
com.kown.android.fundraiseonkown,2016-05-10T01:07:00Z,1462842420318,hammerhead,23,0.9.1,3,java.lang.NullPointerException,Attempt to read from null array,MainActivity.java,com.kown.android.fundraiseonkown.MainActivity,onClick,704,,,https://play.google.com/apps/publish?dev_acc=04052455048233046270#ErrorClusterDetailsPlace:p=com.kown.android.fundraiseonkown&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1462842420318&et=CRASH&ecn=java.lang.NullPointerException&tf=MainActivity.java&tc=com.kown.android.fundraiseonkown.MainActivity&tm=onClick
com.kown.android.fundraiseonkown,2016-05-10T01:11:06Z,1462842666526,hammerhead,23,0.9.1,3,java.lang.IllegalArgumentException,ParseFile must be less than 10485760 bytes,ParseFile.java,com.parse.ParseFile,<init>,190,,,https://play.google.com/apps/publish?dev_acc=04052455048233046270#ErrorClusterDetailsPlace:p=com.kown.android.fundraiseonkown&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1462842666526&et=CRASH&ecn=java.lang.IllegalArgumentException&tf=ParseFile.java&tc=com.parse.ParseFile&tm=%3Cinit%3E

**Comment by grantland** [comment]
Can you post a readable stack trace?

**Comment by kristoprifti** [comment]
java.lang.IllegalArgumentException: ParseFile must be less than 10485760 bytes
	at com.parse.ParseFile.<init>(ParseFile.java:190)
	at com.parse.ParseFile.<init>(ParseFile.java:219)
	at com.kown.android.fundraiseonkown.MainActivity.convertVideos(MainActivity.java:839)
	at com.kown.android.fundraiseonkown.MainActivity.onClick(MainActivity.java:658)
	at android.view.View.performClick(View.java:5204)
	at android.view.View$PerformClick.run(View.java:21153)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by kristoprifti** [comment]
this is a stack trace that i receive in the Android Studio when i try to create a ParseFile. When the byteArray that i pass as an argument is larger than 10485760 bytes i get this error. Otherwise with smaller byteArray it works fine. Do you have any suggestions how to resolve this issue ? The parse SDK is up to date and the parse initialization is done in the new server.

**Comment by grantland** [comment]
Looks like the Android SDK's file limit needs to be updated to be in sync with the other SDKs: https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseFile.java#L167

@nlutsenko do you know if there's a limit in the iOS SDK at all and if so, where it's defined?

**Comment by nlutsenko** [comment]
@grantland this was completely removed on the client in the latest release of iOS SDK ([1.13.0](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases/tag/1.13.0)), so I feel like we can also remove it here completely.

**Comment by grantland** [comment]
@nlutsenko sounds good

with this in mind, we will gladly accept a PR that updates this!

**Comment by aleksdresen** [comment]
What would be the approximate timeframe for solving this issue?

**Comment by kristoprifti** [comment]
@grantland @nlutsenko Can you give us an approximate date when the Parse SDK will be updated for Android and this problem will disappear ?

**Comment by grantland** [comment]
After someone graciously submits a PR :smile:

**Comment by kristoprifti** [comment]
@grantland how can someone submit a PR ? does it have to be one of the employees in Parse or I can also do it ?

**Comment by grantland** [comment]
You can also do it 😄

**Comment by grantespo** [comment]
I get the  "ParseFile must be less than10485760 bytes" when trying to upload a picture to parse from a picture taken from my phone.

**Comment by rogerhu** [comment]
I think this ticket can be closed since it had to do with a wrong Bintary update to 1.13.1.
