### ISSUE TITLE
if you use sdk version is 1.13.0 

### ISSUE THREAD

**Issue by nuan-nuan** [ParsePlatform/Parse-SDK-Android#456]
if you use sdk version is 1.13.0 , you have error for this (bad json request, code error=100),you must check you serve url like this ( http://xxxxxxxxxxx/parse/ ), "/" is  must behind for url ,I solved this after the operation

**Comment by nuan-nuan** [comment]
like this 

// new
.server("http://xxx.xxx.com/parse/")   // is work
// old
//.server("http://xxx.xxx.com/parse")  // not work

**Comment by devcheetah** [comment]
I confirm this issue as I had it myself.  Thanks.

**Comment by crebstock** [comment]
Yep, you'll get a bad json response if you attempt to save the Currrent Installation.  Hopefully anyone who gets that can end up here and find the fix!

**Comment by grantland** [comment]
Fixed by #436

**Comment by nuan-nuan** [comment]
think you @grantland
