### ISSUE TITLE
getCurrentInstallation().saveInBackground() Adding extra ID string in front

### ISSUE THREAD

**Issue by devcheetah** [ParsePlatform/Parse-SDK-Android#460]
When using ParseInstallation.getCurrentInstallation().saveInBackground(); it is adding in "|ID}#|:" to the device Token.  This is causing issues with pushAdapters because it sends that extra bit of string when trying to use a third party push service.  like pushwoosh.

For example

> |ID|1|:es3c-xxxxxxxxxxxxx

I assume its the ID stored in mongodb.  Can we get this extra bit removed?

**Comment by kassim** [comment]
when I stepped through the code it seemed to be the registration token that's been given by GCM, not Parse

if you set a breakpoint in `GcmRegistrar.handleRegistrationIntentAsync()` (which handles the intent) you should be able to see it there

**Comment by devcheetah** [comment]
The only way to get the push to work is remove |ID|#|.   So should I not use getCurrentInstallation?  Or should that function be handling this?  Having to go into parse to remove that string for every new installation would be a pain.

**Comment by jackdewhurst** [comment]
This is causing issues with Amazon SNS for us, the token has an invalid format and is therefore rejected.

Is the GCM token generated with a different structure now that Firebase has taken over?

**Comment by jackdewhurst** [comment]
Ok it seems GcmRegistrar returns two token types from gcm (at random). One like such: 

`com.parse.GcmRegistrar: Received deviceToken <|ID|1|:f4X1TRPndYo:APA91bHcKpUeJEp_ljCnRWV1ROrMXdudnpYRcV51sYAt7Z2uMj74Az-dC_GYKUqIptz1WNSQRCuzbhU3_chdMj2xjNiC2x1qyyLqKk7j2pJLjR0pOGnnAXSGNh24b> from GCM.`

and another: 

`com.parse.GcmRegistrar: Received deviceToken <APA91bGoJirvYsq2ACTppZ9EpCDUCHRF4wT41zoYUpA5uyhY9U40bM9w_nuLq7V1ySEDNW_wQpK2lOp2CEmHztIu-wafBttEBLWLo2Ufhb3HwC1J-_c1WWTNnwwFBZINo5> from GCM.`

I have no idea why.

**Comment by devcheetah** [comment]
If anyone has a solution or temporary work around for this, that would help a lot.  At this point I would have to create something to constantly parse out all the extra prefix stuff.

**Comment by patmelua** [comment]
Hi,

dealing with the same problem.
@jackdewhurst : you're right and the 2 GCM id is different from the first one (after the |ID|1|:...: pattern.

I tried to modify the PushAdapterUtils.js (server side) using
` installation.deviceToken.replace(/\|ID\|1\|:[^:.]*:/,"");`
but with no luck for now.

I encounter this issue just after moving to play-services: 9+ if it helps.

**Comment by jackdewhurst** [comment]
For now we've written a job to trim tokens up to the first colon server side.

So if a GCM token contains `|ID|1|:` we remove it and re-save the installation object. Devices with trimmed tokens seem to receive notifications ok for now. 

Not ideal though.

**Comment by odaeagle** [comment]
@devcheetah 

My current work around is have a new class that extends ParseInstallation in the same package ( so that i can access the protected member of ParseIntallation) and have a helper function to read the current installation and modifiy it if it is in wrong format

however, since we don't know when and we don't have callback when the GCM token is received (it is in the background), i call this helper everytime in my activity onCreate, it's not ideal solution, but at least I only save the installation when the format is wrong, hence it's not that bad...

Before I have this "hack" solution, I tried manually get the GCM token, but parse won't save though

**Comment by firasalkafri** [comment]
Any update on this guys?

**Comment by devcheetah** [comment]
For the time being I made cloud code beforeSave to remove this and is working for now.

`Parse.Cloud.beforeSave(Parse.Installation, function(request, response){
        var id = request.object.get("deviceToken").replace("|ID|1|:","");
        request.object.set("deviceToken",id);
        response.success();
});`

**Comment by FireZenk** [comment]
We have had the same problem, but in our case was a conflict with the gms plugin and firebase lib, so we removed:
```
apply plugin: 'com.google.gms.google-services'
```

and
```
compile 'com.google.firebase:firebase-core:9.0.2'
```

ID's are now correct and push notifications are working again

**Comment by JaviChaques** [comment]
I have the same issue with:
- Parse SDK 1.13.1
- Play Services GCM 9.2.0
- Google Services 3.0.0

How can I solve it?

Thank you!

**Comment by PiXeL16** [comment]
Yep +1 on this! @devcheetah Are you still using your cloud `beforeSave` trigger?

**Comment by ramparttyler** [comment]
@PiXeL16 I am, yes.   It is a decent workaround for us until an official fix is released.

**Comment by devcheetah** [comment]
I am using the beforeSave still.

**Comment by PiXeL16** [comment]
Thanks, @FireZenk fix worked for me. 
Looks like 
```compile 'com.google.firebase:firebase-core:9.0.2'```
Fix the issue

👍

**Comment by bluelabeldeveloper1** [comment]
I have same issue( |ID|1|: prefix in deviceToken ) with : 
compile 'com.parse:parse-android:1.13.1'
compile 'com.google.android.gms:play-services-gcm:8.4.0'

How can i solve it?

Thank you!

**Comment by NodensN** [comment]
I have the same issue, but if I remove ```apply plugin: 'com.google.gms.google-services'``` the screen trackers are down ... 

I used:  
```java 
compile 'com.google.android.gms:play-services-gcm:9.2.1'
compile 'com.google.android.gms:play-services-analytics:9.2.1'

apply plugin: 'com.google.gms.google-services'
```

Any ideas how I can solve this issue?

**Comment by PiXeL16** [comment]
I am adding the relevant parts that works for me:

Root-level `build.gradle`
```
       dependencies {
       .....
        classpath 'com.google.gms:google-services:3.0.0'
       .....
    }
```

Module `build.gradle`

```
   dependencies {
    compile 'com.google.android.gms:play-services-gcm:9.2.0'
   }
```

I didn't need the `apply plugin: 'com.google.gms.google-services'` here.

`Manifest.xml`
```
        <!--GCM Sender ID was provided by the GCM Project information on developerconsole.google.com-->
        <meta-data android:name="com.parse.push.gcm_sender_id"
            android:value="id:YourGCMSenderID" />
```

**Comment by rogerhu** [comment]
We can close by upgrading to a later version of GCM right?
