### ISSUE TITLE
Problem "Peer not authenticated"

### ISSUE THREAD

**Issue by flamesoft** [ParsePlatform/Parse-SDK-Android#467]
I have an Android project which uses Parse. It has been working well. But today when I opened it I found that the error in Gradle. My Android Studio is the v2.1.1.
Then I checked the "https://maven.parse.com/repo" and found that the certificate has expired. 

How shall I use Parse when the certification expires? Will "maven.parse.com/repo" stay after Parse is shut down next year? Shall I use the lib files in my project directly? Any suggestions?

My gradle looks like this
```
buildscript {
    repositories {
        mavenCentral()
        maven {
            url 'https://maven.parse.com/repo'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0'
        classpath 'com.parse.tools:gradle:1.+'
    }
```

**Comment by grantland** [comment]
Duplicate #463
