### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by mliberato** [ParsePlatform/Parse-SDK-Android#469]
As stated in another issue (https://github.com/ParsePlatform/Parse-SDK-Android/issues/463), there is no way to bypass SSL certificate problems in gradle.

Could you please help us in this final phase of Parse by renewing this HTTPS certificate, or at least letting us use HTTP instead?

I get it may not be related to Parse-SDK-Android, but there is no other place to report this problem - not that I know.

Thank you.

**Comment by grantland** [comment]
The issue you've referred to has an explanation of the problem and how to work around it. Closing since there's no clear differences between this new issue and the previously resolved one.
