### ISSUE TITLE
After increment("field", someValue), get("field") returns a ParseIncrementOperation

### ISSUE THREAD

**Issue by all-iver** [ParsePlatform/Parse-SDK-Android#472]
I'm running this code in a subclass of ParseUser:

```
Log.i("Test", get("someNumberField").toString());
increment("someNumberField", -amount);
Log.i("Test", get("someNumberField").toString());
saveInBackground();
```

This seems to work and in the console I get:

```
-5
0
```

After a bit the code runs again and the first Log() prints out:

```
com.parse.ParseIncrementOperation@5b7dd5
```

And the increment() call fails with:

```
You cannot increment a non-number.
```

So something is putting a ParseIncrementOperation in "someNumberField" instead of storing it separately.  I don't know if that's correct or not, but the second increment attempt is failing.

The increment call is the only code in the whole project that references "someNumberField" aside from cloud code that reads it and sets it to an integer directly.  Not really sure how to debug this since I'm not sure if it's correct or not for the field itself to be returning an operation instead of a value.

**Comment by grantland** [comment]
You want `ParseObject#getInt(key)`.

**Comment by all-iver** [comment]
Hmm, the problem is that the second call to increment() is failing because the field somehow winds up with a ParseIncrementOperation in it instead of an integer.  I just put the log statements in to demonstrate the problem.  This code runs fine on legacy Parse.  I'll do some more testing and see if I can come up with a better example.

**Comment by all-iver** [comment]
Here's another example, although I'm not sure this will help much.

```
// put("someNumber", 0); // uncommenting this line makes it work every time
increment("someNumber", -2);
saveInBackground(new SaveCallback() {
    @Override
    public void done(ParseException e) {
        increment("someNumber", 0); // this crashes the app the second time it runs
    }
});
```

This code runs fine the first time.  The second time, the increment() inside the done callback crashes the code.  If I step through the code, I can see that "oldValue" in ParseObject.performOperation() is a ParseIncrementOperation instead of an integer.

The really weird thing is that if I explicitly put() an integer into the field, it works.  If I don't do that, then when the first increment happens "oldValue" is an integer, but by the time the second increment happens there's a ParseIncrementOperation in there instead.  Why would there ever be an operation in that field instead of the actual value?

**Comment by sprabs** [comment]
Any resolution on this? I'm having the same problem through Cloud Code.

**Comment by all-iver** [comment]
I never managed to resolve it.  I ended up just not using increment() for that operation.

**Comment by santafebound** [comment]
Then how do you decrement?

**Comment by santafebound** [comment]
I guess you can always fetch the previous count,, subtract by 1, then replace the field (assuming the column used to store your count is a Number column) with a new put call:

```
int newReplyCount = yeetObject.getInt(ParseConstants.KEY_REPLY_COUNT) - 1;
yeetObject.put(ParseConstants.KEY_REPLY_COUNT, newReplyCount);
```
