### ISSUE TITLE
Add Parse sdk git project as library in android studio

### ISSUE THREAD

**Issue by muneeshseedoc** [ParsePlatform/Parse-SDK-Android#474]
Unable to add  parse open source git project as library in android studio, i don't want to add it by dependency or by jar.

**Comment by minhvu315** [comment]
On android studio go to file -> Project structure . On tag "(Your project name)" select tab dependencies add module dependency -> select source code library.
[http://imgur.com/39DrLsm](url)

**Comment by kristoprifti** [comment]
http://www.truiton.com/2015/02/android-studio-add-library-project/  
Check out this tutorial !

**Comment by muneeshseedoc** [comment]
I know how to add project library in in studio, i wanted to know additional libraries need to add with Parse sdk project.

**Comment by rogerhu** [comment]
http://guides.codepath.com/android/Configuring-a-Parse-Server#enabling-client-sdk-integration as well
