### ISSUE TITLE
[POLL] Live Query Library for Android

### ISSUE THREAD

**Issue by TGIO** [ParsePlatform/Parse-SDK-Android#480]
I'm going to make one. Question is - whats better :

* Seperate Library like iOS implementation for LiveQeury
* Integrated in this SDK

please let me known your opinion by reactions :)
Hurray for Seperate Library
Heart for Integration

**Comment by benitech** [comment]
if you do start work with this, could you also check why starting a LiveQuery server along with a existing Redis instance fails? (When adding parse-server to existing express app, already running a redis instance for messaging or sessions etc).

Could it be bad config on my part?

**Comment by TGIO** [comment]
@benitech this is wrong place to ask, please open issue in [parse-server/issues](https://github.com/ParsePlatform/parse-server/issues) and provide stack trace and detailed info on this issue.

**Comment by thphuc** [comment]
@TGIO We are going to build an app that will use Live Query for real time messages. Could you share me your schedule for Live Query for Android? (I mean how long you will need to finish it)

**Comment by TGIO** [comment]
@thphuc 10 days at most.

**Comment by thphuc** [comment]
@TGIO Great news!

**Comment by grantland** [comment]
I'd recommend doing it in a similar fashion and with a similar API as the iOS and JS libraries, since it'll be easier for everyone to utilize and adding it to the SDK will not be accepted as a PR into this repository.

**Comment by thphuc** [comment]
@TGIO 10 days passed. Any good news for me mate? :)

**Comment by TGIO** [comment]
@thphuc it got delayed by couple more days but not more than a week.

**Comment by thphuc** [comment]
@TGIO It's great. I am eager to try Live query 👍

**Comment by TGIO** [comment]
@thphuc [Enjoy!](https://github.com/TGIO/ParseLiveQuery)

**Comment by TGIO** [comment]
@thphuc have u tried it already ?

**Comment by thphuc** [comment]
@TGIO Thanks for your great works! I will try it soon next week!

**Comment by khirr** [comment]
Hi @TGIO, I've make some changes to can work with subscription easily, maybe you can use it and merge with you library: https://github.com/khirr/ParseLiveQuery

**Comment by DiegoRecalde** [comment]
@thphuc did you try it?

**Comment by thphuc** [comment]
@DiegoRecalde I tried but it doesn't work with pointer query. Any solution?

**Comment by maxto024** [comment]
@TGIO  thanks great work I will try  soon this is awesome
