### ISSUE TITLE
Issue with parse push notifications - Android devices

### ISSUE THREAD

**Issue by MorasSuraj** [ParsePlatform/Parse-SDK-Android#489]
After removing google play services compile **(com.google.android.gms:play-services:8.3.0)** and adding only whats necessary **(com.google.android.gms:play-services-location:9.0.2)** parse push notifications feature started behaving weirdly! (Notifications were received or lost inconsistently) After reverting back to **('com.google.android.gms:play-services:9.0.2')** the behavior is still persisted! Before these changes push notifications were working fine! Any clue on whats gone wrong?

**Other dependencies used**
'com.google.android.gms:play-services-ads:9.0.2'
'com.google.android.gms:play-services-auth:9.0.2'
'com.google.android.gms:play-services-gcm:9.0.2'
'com.google.android.gms:play-services-analytics:9.0.2'

_Parse SDK version used : 1.13.0_

**Comment by rogerhu** [comment]
See: https://github.com/ParsePlatform/Parse-SDK-Android/issues/517
