### ISSUE TITLE
getCurrentInstallation().saveInBackground() does nothing

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/Parse-SDK-Android#493]
I wrote a testing app to test push notification. But it doesn't and I found the installation not saved in my database. Here is my code in my StarterApplication:

```
public class StarterApplication extends Application {

  @Override
  public void onCreate() {
    super.onCreate();

    Parse.initialize(new Parse.Configuration.Builder(this)
        .applicationId("my-app-id")
        .server("https://myserver-url/parse")
        .build()
    );

    ParseInstallation.getCurrentInstallation().saveInBackground(new SaveCallback() {
      @Override
      public void done(ParseException e) {
        if ( e != null ) {
          Log.d("ParseDemo", e.getLocalizedMessage());
        } else {
          Log.d("ParseDemo","Installation saved");
        }
      }
    });
  }
}

```

I always got the following error message:

> 07-05 10:12:09.198 32330-32330/com.wow.parsedemo D/ParseDemo: bad json response

What could be the reason? Or how can I log the json response? Thanks.

By the way, my iOS app works fine and there is even no any log in my parse server when I run android app.

**Comment by sudochownrwhoami** [comment]
I believe your server URL in the Parse.Configuration.Builder should include the forward slash '/' after 'parse':
currently yours is:
> .server("https://myserver-url/parse")
it should be:
> .server("https://myserver-url/parse/")

Give that a shot and see if that helps.

**Comment by zhouhao27** [comment]
@sudochownrwhoami That fixed the bad json response issue. Thanks. Still can't fix the notification issue in android. Anyway it's another problem.
