### ISSUE TITLE
Users are able to intercept HTTPS data in complete plain text and alter it.

### ISSUE THREAD

**Issue by dri94** [ParsePlatform/Parse-SDK-Android#50]
Affected: All android parse users, maybe more

Problem:
When I created an account when I first opened the app, I captured the HTTP request it sent, than I replayed the request and edited the 'satoshi' part to however many satoshis I would want, changed the username so it would register
{"password":"passwordsarefun","device_id":"1111111 1111111111","tampered":false,"totalSatoshi":0,"use rname":"SoAreUsernames","satoshi":9999999999999999 ,"emailAddress0":"emails@arentas.fun","dailyReward ":0}
Than all you have to do is login and withdraw

Proposed solution:
A solution would be to use an encryption method. I assume your sdk is already encrypted and obfuscated. Simply have the sdk make a call to the server with AES encrypted strings. Parse should have a master key only known to them that can then decrypt the data and use it accordingly IE make a new user, or update user object. So there is your solution. You can ofcourse have the master key be different for each unique user and app, and have it reset randomly so no one can begin to try and decipher it. However that would require much more code.

issue has been brought up to no avail here https://groups.google.com/forum/#!topic/parse-developers/3jYTao2C4PY

**Comment by grantland** [comment]
Closing due to not being an SDK issue.

Our SDKs are already using HTTPS and `api.parse.com` does not accept unencrypted traffic. This means that third parties cannot intercept user traffic, nor replay them. In addition, you can enable Email Verification to validate valid users: https://parse.com/docs/android/guide#users-verifying-emails

**Comment by dri94** [comment]
You closed this seeing the results above are possible without offering any solution. That was premature. They are able to be intercepted somehow of course or this wouldnt happen. Also i know of email verification. That would help me find the user but not fix this flaw

**Comment by grantland** [comment]
Please refer to our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md) for more information regarding Issues and Pull Requests on this repository.

**Comment by dri94** [comment]
I do not know enough about this to fix myself, i would definitely help if i could. Simply making aware of a bug. I have shown the actual data intercepted in the first post so i am unsure why it is simply being dismissed as if it didn't happen.
