### ISSUE TITLE
Official Parse LiveQuery Availablility

### ISSUE THREAD

**Issue by faizsameerahmed96** [ParsePlatform/Parse-SDK-Android#503]
Can we please get a timeframe by when you will be able to implement Parse LiveQuery for android in a similar way it is on iOS and JavaScript? I saw the library that TGIO has made and although it is a good start I feel it will be better if there is unity in the design of the library across all platforms. It has been a few months now since this feature was announced!

**Comment by vandersongold** [comment]
Is there any update on issue?

**Comment by rogerhu** [comment]
Dup of https://github.com/ParsePlatform/Parse-SDK-Android/issues/437
