### ISSUE TITLE
Issue deviceToken starts with |ID|1|:

### ISSUE THREAD

**Issue by NodensN** [ParsePlatform/Parse-SDK-Android#504]
We're seeing a strange behaviour while registering token for push notification some starts with |ID|1|: and those won't receive push notification.

For the same device : 
|ID|1|:cYXIT03PJXE:APA91bEgl8H_5NjSWzXuwXhiLBU1z7tFM68-[...]

And sometime I have the good device token for no apparent reason :
APA91bFDP85_s5GpC0Uiq7sxBkSVcnLxnMs1MAPzq2V2M0qD--[...]

Do you have any ideas where it could come from? 

Thanks a lot

**Comment by grantland** [comment]
Please see #460, #39
