### ISSUE TITLE
1.13.1 artifacts have changed

### ISSUE THREAD

**Issue by posativ** [ParsePlatform/Parse-SDK-Android#505]
Hey,

is it possible that you reuploaded the artifacts for 1.13.1? I noticed a difference in the checksums.

**Comment by grantland** [comment]
You're correct, there was an error uploading 1.13.1. Where are you seeing the different checksums?

**Comment by posativ** [comment]
The previous artifacts were actually version 1.13.0 if I noticed correctly. I've detected this, because Gradle doesn't always check for changes and I had different functionality in comparison to the source on GitHub. Did notice some weird behavior in the last few weeks in comparison to the release notes, but finally tracked it down to a wrong artifact. Didn't know that you can change released artifacts.

[gradle-witness](https://github.com/WhisperSystems/gradle-witness) is handy for future silent re-uploads.

**Comment by rogerhu** [comment]
Yeah the 1.13.1 was pushed out incorrectly (https://github.com/ParsePlatform/Parse-SDK-Android/issues/491#issuecomment-231746405). Can this ticket be closed?

**Comment by posativ** [comment]
Yes.
