### ISSUE TITLE
Push notifications stop working after updating to play-services 9.0 or up

### ISSUE THREAD

**Issue by gameleon-dev** [ParsePlatform/Parse-SDK-Android#517]
We recenty updated our apps to include version 9.4 of the play services due to a few new features and bugfixes we would like to use.

```
compile 'com.google.android.gms:play-services-analytics:9.4.0'
compile 'com.google.android.gms:play-services-auth:9.4.0'
```

However, ever since the update push notifications over GCM have stopped working. Users who still use an app version that used v8.4 of the play-services library have no issue.

Aside from updating the play-services library no changes were made to any push notification related code, and the issue seems to appear on all play-services versions above 9.0.
Are there some code changes required to receive push notifications through parse with the 9.+ play libraries?

**Comment by armcha** [comment]
+

**Comment by Gameleon12** [comment]
Looking into it further it seems to be related to the ID prefix as described by issue #460 . 
So far I created the following beforeSave function as a workaround, but it seems like this is just a temporary solution for something that should probably be fixed in the Android SDK:

```
Parse.Cloud.beforeSave(Parse.Installation,function(request, response){
	var deviceToken = request.object.get("deviceToken");
	if(deviceToken !== undefined)
	{
		request.object.set("deviceToken",deviceToken.replace(/\|ID\|1\|:.*:/,""));
	}
	response.success(); 
});
```

**Comment by nthieu90** [comment]
I have the same issue.

**Comment by TaniaSolo** [comment]
The same problem.

**Comment by eduardbosch** [comment]
The same problem here. I use 8.4.0 too in order to work.

I would like to use the latest 9.8.0 gcm library.

**Comment by eduardbosch** [comment]
Hi,

I was trying to use the latest 9.8.0 google play services, and it looks that is working good with GCM and parse for me.

I've configured my gcm credentials with this website:
https://developers.google.com/mobile/add

I've updated the google-services.json in my app and I'm receiving the Push notifications in my app.

And then I've restricted the autocreated credential keys usage in the API console for security:
https://console.developers.google.com/apis/credentials

I've also tried to configure GCM credentials with [firebase console](https://console.firebase.google.com/) and seams to work correctly also.

### Configure Android App

I've added dependency to **level-project** build.gradle:

`classpath 'com.google.gms:google-services:3.0.0'`

I've added plugin to **app-level** build.gradle:

`apply plugin: 'com.google.gms.google-services'`

I've added dependency to **app-level** build.gradle:

`compile 'com.google.android.gms:play-services-gcm:9.8.0'`

### My scenario:
**Backend:**
_Parse_ v1.9.2
_Parse Server_ v2.2.22
**Android App**
_Parse SDK_ v1.13.1

Could anyone check if works for you?

Hope this helps!

**Comment by Helmikku** [comment]
Hello @eduardbosch ,

I used to test it without any success, earlier this year, but **it seems to work now**. Thanks for your post! Here is my setup:

**Parse Server**
Parse Server 2.2.25

**Android**
_Project gradle:_
`classpath 'com.google.gms:google-services:3.0.0'`

_App gradle:_
```
dependencies {
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.google.android.gms:play-services-analytics:10.0.1'
    compile 'com.google.android.gms:play-services-gcm:10.0.1'
    compile 'com.google.android.gms:play-services-location:10.0.1'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
    compile 'com.google.android.gms:play-services-places:10.0.1'
    compile 'com.parse.bolts:bolts-android:1.3.0'
    compile 'com.parse:parse-android:1.13.1'
}

apply plugin: 'com.google.gms.google-services'
```

_google-services.json:_
```
{
  "project_info": {
    "project_number": "012345678910",
    "project_id": "alpha-breaker-012345"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "0:012345678910:android:qwertyuiopasdfgh",
        "android_client_info": {
          "package_name": "my.package"
        }
      },
      "oauth_client": [],
      "api_key": [
        {
          "current_key": "_abcdefghijklmnopqrstuvwxyz_0123456789_"
        }
      ],
      "services": {
        "analytics_service": {
          "status": 2,
          "analytics_property": {
            "tracking_id": "XY-01234567-8"
          }
        },
        "appinvite_service": {
          "status": 1,
          "other_platform_oauth_client": []
        },
        "ads_service": {
          "status": 1
        },
        "cloud_messaging_service": {
          "status": 2,
          "apns_config": []
        }
      }
    }
  ],
  "configuration_version": "1"
}
```

**Comment by eduardbosch** [comment]
@Helmikku good to know that is working also for you, and to know that works with 10+ too!

I tried GCM also some time ago this year without success, but now looks that is working.

**Comment by rogerhu** [comment]
We can close right?
