### ISSUE TITLE
How to upgrade to v1.13.1

### ISSUE THREAD

**Issue by adriano-di-giovanni** [ParsePlatform/Parse-SDK-Android#522]
I maintain a cordova plugin.
I used to upgrade Parse SDK downloading a folder containing several jars.
I used to include Bolts and Parse as follows

```xml
<source-file src="src/android/libs/Parse-1.13.0/bolts-tasks-1.4.0.jar" target-dir="libs" framework="true" />
<source-file src="src/android/libs/Parse-1.13.0/Parse-1.13.0.jar" target-dir="libs" framework="true" />
```

I've just downloaded v1.13.1 and it's only the jar for Parse.

Do I still need Bolts?

**Comment by grantland** [comment]
Yes. You can refer to the build.gradle or Maven POM to confirm dependencies as well.
