### ISSUE TITLE
Why can't I upload a ParseFile with a java.io.File object?

### ISSUE THREAD

**Issue by yuzeh** [ParsePlatform/Parse-SDK-Android#524]
See: https://github.com/ParsePlatform/Parse-SDK-Android/blob/b3f457f556899358da781e902094c863051d6834/Parse/src/main/java/com/parse/ParseOkHttpClient.java#L147

Why does this code only allow `ParseByteArrayHttpBody`?

**Comment by rogerhu** [comment]
Fixed here: https://github.com/ParsePlatform/Parse-SDK-Android/pull/542/files
