### ISSUE TITLE
The parse current user not deleted after app reinstalled

### ISSUE THREAD

**Issue by itman85** [ParsePlatform/Parse-SDK-Android#527]
I uninstalled app, then reinstalled and the parse current user was not deleted. As i know the current user file stored in app_Parse folder, i think it must be cleaned up when app uninstall. When app reinstall, this folder cannot contain current user file until parse user login again. Is there something wrong here? App runs on android 6.0.1

**Comment by ishaan1995** [comment]
On android versions greater than lollipop, the apps are installed for all users of that device.Sometimes while uninstalling , the app might not have been uninstalled for all device users.This makes the app specific folder still inside your device.Reinstalling just installs for that particular user and hence parse user still exists.Can you confirm?Try to uninstall and see if app is still visible in Setting->Apps.

**Comment by itman85** [comment]
I did check app not existed in Settings->Apps.

**Comment by itman85** [comment]
I figured out that my app set allow backup so android automatically backup app data. That's why whenever app reinstalled, app data restored and parse current user file is restored too.
