### ISSUE TITLE
API 19 DUPLICATE ENTRY

### ISSUE THREAD

**Issue by antonio92cop** [ParsePlatform/Parse-SDK-Android#530]
When I change API 23 to 19 send this Error

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.

com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/parse/AbstractQueryController$1.class
compile 'com.parse:parse-android:1.13.1'
compile 'com.parse.bolts:bolts-android:1.3.0'

**Comment by antonio92cop** [comment]
I have the last Parse sdk 1.13.1. This Sdk run very well for Android >= 5.0 but for Android with 4.4 KitKat not work. When launch the emulator the log send this error. Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.

com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/parse/AbstractQueryController$1.class

**Comment by lxknvlk** [comment]
Similar error occured with me when i had two parse sdk's jar files in my libs folder. Two jars of different versions, happened because of my version control.
