### ISSUE TITLE
Cannot save `List<Image[]>` to Parse Array column

### ISSUE THREAD

**Issue by kamoljan** [ParsePlatform/Parse-SDK-Android#54]
Why I cannot save `jsonArray` in Parse Array type column?

Here is my code:

    List<Image[]> images = photoAdapter.getListOfImages();
    JSONArray jsonArray = new JSONArray();
    for (Image[] i : images) {
      JSONArray jsonArray1 = new JSONArray();
      for (Image a : i) {
        jsonArray1.put(a);
      }
      jsonArray.put(jsonArray1);
    }
    parseAd.put("images", jsonArray);

                         E  java.lang.IllegalArgumentException: invalid type for ParseObject: class com.shoppingxxx.data.api.model.Image
                         E      at com.parse.ParseEncoder.encode(ParseEncoder.java:149)
                         E      at com.parse.ParseEncoder.encode(ParseEncoder.java:118)
                         E      at com.parse.ParseEncoder.encode(ParseEncoder.java:118)
                         E      at com.parse.ParseJSONCacheItem.<init>(ParseJSONCacheItem.java:21)
                         E      at com.parse.ParseObject.addToHashedObjects(ParseObject.java:623)
                         E      at com.parse.ParseObject.checkpointMutableContainer(ParseObject.java:1245)
                         E      at com.parse.ParseObject.performOperation(ParseObject.java:2992)
                         E      at com.parse.ParseObject.performPut(ParseObject.java:3026)
                         E      at com.parse.ParseObject.put(ParseObject.java:3010)

`Image` class:

    public final class Image {
      String field, value;
      public String getField() {
        return field;
      }
      public String getValue() {
        return value;
      }
    }

**Comment by grantland** [comment]
The problem here isn't putting a `JSONArray` on `ParseObject`, putting your `Image` object on `ParseObject` is illegal as `Image` isn't a valid data type.

Please refer [here](https://parse.com/docs/android/guide#objects-data-types) for documentation on valid data types.

**Comment by kamoljan** [comment]
@grantland yes you are right. Thank you for your response.
However the documentation doesn't have anything about nested arrays (array inside array).
Had to work with Java List inside other List... 

Anyway, thank you very much for your promt response!

**Comment by grantland** [comment]
Nested arrays should work FWIW

**Comment by kamoljan** [comment]
Maybe someone find it usefull, I just want to share a sample code for nested array case.

To achieve this Array type:

    [
      [
        {
            "field": "xlarge_view",
            "value": "0001-jpeg-xlarge-view-8d862fdbe7bea0b6e79ec44df159814662a9c62e-101010-640-640"
        },
        {
            "field": "xlarge_list",
            "value": "0001-jpeg-xlarge-list-8d862fdbe7bea0b6e79ec44df159814662a9c62e-101010-320-320"
        },
        {
            "field": "large_view",
            "value": "0001-jpeg-large-view-8d862fdbe7bea0b6e79ec44df159814662a9c62e-101010-480-480"
        },
        {
            "field": "large_list",
            "value": "0001-jpeg-large-list-8d862fdbe7bea0b6e79ec44df159814662a9c62e-101010-240-240"
        },
        {
            "field": "medium_view",
            "value": "0001-jpeg-medium-view-8d862fdbe7bea0b6e79ec44df159814662a9c62e-101010-320-320"
        },
        {
            "field": "medium_list",
            "value": "0001-jpeg-medium-list-8d862fdbe7bea0b6e79ec44df159814662a9c62e-101010-160-160"
        }
    ],
    [
        {
            "field": "xlarge_view",
            "value": "0001-jpeg-xlarge-view-f04bd2b088a8f87458ef16b694f7d7a4d0f5bd23-101010-640-640"
        },
        {
            "field": "xlarge_list",
            "value": "0001-jpeg-xlarge-list-f04bd2b088a8f87458ef16b694f7d7a4d0f5bd23-101010-320-320"
        },
        {
            "field": "large_view",
            "value": "0001-jpeg-large-view-f04bd2b088a8f87458ef16b694f7d7a4d0f5bd23-101010-480-480"
        },
        {
            "field": "large_list",
            "value": "0001-jpeg-large-list-f04bd2b088a8f87458ef16b694f7d7a4d0f5bd23-101010-240-240"
        },
        {
            "field": "medium_view",
            "value": "0001-jpeg-medium-view-f04bd2b088a8f87458ef16b694f7d7a4d0f5bd23-101010-320-320"
        },
        {
            "field": "medium_list",
            "value": "0001-jpeg-medium-list-f04bd2b088a8f87458ef16b694f7d7a4d0f5bd23-101010-160-160"
        }
      ]
    ]
    
Had to do like this:

      List<Image[]> images = photoAdapter.getListOfImages();
      List<List> parseImageArray = new ArrayList<>();
      for (Image[] i : images) {
        List<JSONObject> innerList = new ArrayList<>();
        for (Image a : i) {
          JSONObject jsonObject = new JSONObject();
          try {
            jsonObject.put("field", a.getField());
            jsonObject.put("value", a.getValue());
            innerList.add(jsonObject);
          } catch (JSONException e) {
            e.printStackTrace();
          }
        }
        parseImageArray.add(innerList);
      }
      parseAd.put("images", parseImageArray);
