### ISSUE TITLE
Can't compile when compileSdkVersion is 23

### ISSUE THREAD

**Issue by zhoul-HS** [ParsePlatform/Parse-SDK-Android#544]
![image](https://cloud.githubusercontent.com/assets/6669808/20113944/3a28e33a-a5fb-11e6-879c-52b9167ea4ad.png)

Uses some functions and classes that were dropped. Any guidance on how I can make it compile?
I'm trying to use a clone of the master branch with my #542 PR, and my app's compileSdkVersion is 23 (can't be lower)

This doesn't happen when I include parse in my project using `compile 'com.parse:parse-android:1.13.1'`

**Comment by grantland** [comment]
Unfortunately we were never able to find a solution to compiling against 23: #189

**Comment by zhoul-HS** [comment]
ok. what about importing Parse-SDK-Android to a project that compiles to 23? Any chance to make it work the way normal gradle `compile` works? I realize this is not specific to this but if you know it could help :)

**Comment by grantland** [comment]
It should be fine as long as you're using a pre-compiled version of Parse SDK, such as through Maven or a JAR. It only breaks when compiling the Parse source against 23.
