### ISSUE TITLE
com.parse.ParseRequest$ParseRequestException: i/o failure

### ISSUE THREAD

**Issue by iamalroberts** [ParsePlatform/Parse-SDK-Android#545]
All of a sudden, i am not longer able to upload any type of ParseFile objects, specifically in my case images. It runs and runs and finally i get com.parse.ParseRequest$ParseRequestException: i/o failure error with the cause being java.net.SocketTimeoutException.

```
ByteArrayOutputStream stream = new ByteArrayOutputStream();
                imageBitmap.compress(Bitmap.CompressFormat.JPEG, 100, stream);
                byte[] bytearray = stream.toByteArray();
                ParseFile styleImageFile = new ParseFile("styleImage.jpeg", bytearray);
	     
    styleImageFile.saveInBackground(new SaveCallback() {
                    @Override
                    public void done(ParseException e) {
                        if(e==null) {
                            //success
                        }else
                        {
                           //fail
                            Log.e("Edit Style Error", e.getMessage());
                        }
                    }
                });
```

This is my current build file
```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        applicationId "com.iamalroberts.natural"
        minSdkVersion 21
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.parse:parse-android:1.13.1'
    testCompile 'junit:junit:4.12'
    compile 'com.github.clans:fab:1.6.2'
}
```

**Comment by hatpick** [comment]
Your server might be out of space.

**Comment by iamalroberts** [comment]
@hatpick hmmmm...i'll look into it.

**Comment by iamalroberts** [comment]
@hatpick that was the answer. Tried a different server connection and everything worked fine. What led you to think that? Was it just an educated guess?

**Comment by hatpick** [comment]
@iamalroberts I figured when all was good and suddenly stopped working with timeout message, it must be something on the server.

**Comment by iamalroberts** [comment]
@hatpick gotcha. well thanks a billion.

**Comment by sandeep2242** [comment]
@iamalroberts how you tried a different server can you please help.

**Comment by iamalroberts** [comment]
I changed my server to apache and that helped a bit.

**Comment by sandeep2242** [comment]
@iamalroberts I am using Heroku, is there any problem with heroku?

**Comment by iamalroberts** [comment]
Not sure, haven't used it.

**Comment by sandeep2242** [comment]
@iamalroberts When i am saving only one image, then there's no problem. But if I am uploading 5 Images at once this error is shown . Any Guesses?

**Comment by iamalroberts** [comment]
Hmm. Not sure. I would check the logs to see if it's a timeout issue or a memory issue.

**Comment by lyfm** [comment]
![selection_043](https://cloud.githubusercontent.com/assets/21175086/26548675/05e47a72-447e-11e7-9750-ca22fa022ff5.png)

I also have this problem
It don't want to connect and after nearly one minute show me a message
Please help

**Comment by natario1** [comment]
@lyfm could you post your `parse-server` logs when this happens?

**Comment by lyfm** [comment]
I use Parse first time
I only have Server_URL, Client_ID and app_id
Customer sad that this parameters enough for connection

This error come after I try to create new ParseUser
Or I need to add something more in my dependencies ?

**Comment by natario1** [comment]
@lyfm Does this happen on every request? You are getting a network timeout, so there should be something wrong at the server level, not the android app.

**Comment by lyfm** [comment]
No, when I try to login - it works good, but When I try to create a new ParseUser - i show error

**Comment by lyfm** [comment]
Thank's @natario1 
Customer wrote to support and it start work after 10-15 minute
So now it's good)

**Comment by jonathan34c** [comment]
Hi, I have the same issue, but i have already deleted all  the parse file on my parse server, so the server should have enough space...Can anyone help?

**Comment by iamalroberts** [comment]
I gave up with Parse and started using the AWS mobile sdk. Cut out the
middle man.

**Comment by flovilmart** [comment]
@ismalroberts your comment is far from
Constructive and instructive.

**Comment by jonathan34c** [comment]
this is my server error code 


`2017-07-11T03:53:30.816276+00:00 app[web.1]: Error
2017-07-11T03:53:30.816294+00:00 app[web.1]:     at IncomingMessage.onAborted (/app/node_modules/raw-body/index.js:269:10)
2017-07-11T03:53:30.816295+00:00 app[web.1]:     at emitNone (events.js:105:13)
2017-07-11T03:53:30.816296+00:00 app[web.1]:     at IncomingMessage.emit (events.js:207:7)
2017-07-11T03:53:30.816296+00:00 app[web.1]:     at abortIncoming (_http_server.js:410:9)
2017-07-11T03:53:30.816297+00:00 app[web.1]:     at socketOnClose (_http_server.js:404:3)
2017-07-11T03:53:30.816297+00:00 app[web.1]:     at emitOne (events.js:120:20)
2017-07-11T03:53:30.816297+00:00 app[web.1]:     at Socket.emit (events.js:210:7)
2017-07-11T03:53:30.816298+00:00 app[web.1]:     at TCP._handle.close [as _onclose] (net.js:549:12)`

**Comment by jonathan34c** [comment]
this is my servers side error 

`017-07-11T04:09:52.528228+00:00 app[web.1]: Error
2017-07-11T04:09:52.528238+00:00 app[web.1]:     at IncomingMessage.onAborted (/app/node_modules/raw-body/index.js:269:10)
2017-07-11T04:09:52.528240+00:00 app[web.1]:     at emitNone (events.js:105:13)
2017-07-11T04:09:52.528240+00:00 app[web.1]:     at IncomingMessage.emit (events.js:207:7)
2017-07-11T04:09:52.528241+00:00 app[web.1]:     at abortIncoming (_http_server.js:410:9)
2017-07-11T04:09:52.528241+00:00 app[web.1]:     at socketOnClose (_http_server.js:404:3)
2017-07-11T04:09:52.528242+00:00 app[web.1]:     at emitOne (events.js:120:20)
2017-07-11T04:09:52.528243+00:00 app[web.1]:     at Socket.emit (events.js:210:7)
2017-07-11T04:09:52.528243+00:00 app[web.1]:     at TCP._handle.close [as _onclose] (net.js:549:12)`

**Comment by sandeep2242** [comment]
@jonathan34c  this happens when your server space is full. Do you use mongo lab( sandbox )?

**Comment by jonathan34c** [comment]
@sandeep2242  yes, but I thought I delete all the file on my serve using Mongodb lab web site...

**Comment by sandeep2242** [comment]
@jonathan34c  please post your mongolab db stats, which looks something like this
![untitled](https://user-images.githubusercontent.com/25986690/28051136-d59c50a6-661f-11e7-8c15-5b00172b1859.png)

**Comment by jonathan34c** [comment]
@sandeep2242 
![mongodb](https://user-images.githubusercontent.com/8307131/28051193-4e472d5e-6635-11e7-99f0-61a08ca90ae2.JPG)

**Comment by sandeep2242** [comment]
@jonathan34c ok so this dosen't looks like server space problem, you have ample amount of space left.

**Comment by jonathan34c** [comment]
@sandeep2242 i guess im stuck again :((((((((((

**Comment by sandeep2242** [comment]
@jonathan34c  please post your code

**Comment by jonathan34c** [comment]
@sandeep2242  server code or my android code?

**Comment by sandeep2242** [comment]
@jonathan34c android

**Comment by jonathan34c** [comment]
`  final ParseFile file = new ParseFile("profile.jpg", byteArray);
                    file.saveInBackground(new SaveCallback() {
                        @Override
                        public void done(ParseException e) {
                            if (e == null) {
                                hasimg = true;
                                imgfile = file;
                            }else{
                                e.printStackTrace();
                            }
                        }
                    });
`
pretty simple..

**Comment by sandeep2242** [comment]
@jonathan34c  can you please try it with put command, and then save ie.
ParseObject po = new ParseObject("className");
 po.put("columnName", file);
po.saveInBackground();

**Comment by sandeep2242** [comment]
@jonathan34c  slow internet might also be a problem.

**Comment by jonathan34c** [comment]
@sandeep2242 
same thing...
`or
2017-07-11T05:05:44.255564+00:00 app[web.1]:     at IncomingMessage.onAborted (/app/node_modules/raw-body/index.js:269:10)
2017-07-11T05:05:44.255566+00:00 app[web.1]:     at emitNone (events.js:105:13)
2017-07-11T05:05:44.255567+00:00 app[web.1]:     at IncomingMessage.emit (events.js:207:7)
2017-07-11T05:05:44.255567+00:00 app[web.1]:     at abortIncoming (_http_server.js:410:9)
2017-07-11T05:05:44.255568+00:00 app[web.1]:     at socketOnClose (_http_server.js:404:3)
2017-07-11T05:05:44.255569+00:00 app[web.1]:     at emitOne (events.js:120:20)
2017-07-11T05:05:44.255569+00:00 app[web.1]:     at Socket.emit (events.js:210:7)
2017-07-11T05:05:44.255571+00:00 app[web.1]:     at TCP._handle.close [as _onclose] (net.js:549:12)`

**Comment by jonathan34c** [comment]
@sandeep2242  lol im using wifi...alright then..

**Comment by jonathan34c** [comment]
@sandeep2242 I think it really is the slow internet problem. I changed a network and it works ! thank you so much for the help !

**Comment by Shamsudeen12** [comment]
Hi, I am also getting the i/o failure issue, I have a good connection, and I have switched from aws to google cloud, but i'm still getting the error

**Comment by davimacedo** [comment]
I've answered you in your StackOverflow question (https://stackoverflow.com/questions/56775841/parse-error-com-parse-parserequestparserequestexception-i-o-failure). Please take a look.

**Comment by AdarshPan** [comment]
I am getting the same error in retrieving the image from the parse DataBase. Can anyone help??
Details::
Uploading the Image is working absolutely fine but retrieving the image is a Big issue..
The error i am getting is this :
W/System.err: com.parse.ParseRequest$ParseRequestException: i/o failure

**Comment by Shamsudeen12** [comment]
What android or sdk version are you running the app on?
