### ISSUE TITLE
Infinite pinnig of cycling objects

### ISSUE THREAD

**Issue by AKlimashevskyCedon** [ParsePlatform/Parse-SDK-Android#55]
if object A is connected to object B using array and object B is connected to object C using array and object C is connected to object A using array pinning of any of this objects is infinite according to recursion. 

Test case;

    public void testPinning(){
        
        ParseObject user1 = ParseObject.createWithoutData(ParseUser.class,"1");
        ParseObject user2 = ParseObject.createWithoutData(ParseUser.class,"2");
        ParseObject user3 = ParseObject.createWithoutData(ParseUser.class,"3");

        user1.add("follower",user2);

        user2.add("follower", user3);

        user3.add("follower", user1);

        List<ParseObject> users = new ArrayList<>();

        users.add(user1);
        users.add(user2);
        users.add(user3);

        try {
            ParseObject.pinAll(users);
        } catch (ParseException e) {
            e.printStackTrace();

            Assert.assertTrue(false);
        }

        Assert.assertTrue(true);
    }

**Comment by grantland** [comment]
You're code snippet runs perfectly for me, could you please double check it?

**Comment by AKlimashevskyCedon** [comment]
@grantland 

Ok, I checked it. And find out root of problem: pin operation takes at least O(n) time, where n - is a count of objects in local storage. 

example:

public void testPinning() {

        int count = 1000;
        int fcount = 20;
        try {
            ParseObject.unpinAll();

            for (int i = 0; i < count; i++) {
                ParseObject obj = ParseObject.createWithoutData("Super", "id_" + i);
                for(int j = 0 ; j < fcount; j++){
                    obj.put("key_j",j);
                }
                long t1 = new Date().getTime();

                obj.pin();

                long t2 = new Date().getTime();
                long d = t2 - t1;
                Log.d("TAG","time:"+d);
            }
        } catch (ParseException e) {
            e.printStackTrace();
        }
        Log.d("TAG", "done");
        // Assert.assertTrue(true);
    }

on my phone pin of first obj takes near 50ms and the last more then 1 sec.

During debug I see that in method OfflineStore#pinAllObjectsAsync(String name, final List<T> objects, final boolean includeChildren, final ParseSQLiteDatabase db) there is an iteration around all items in local data storage

**Comment by lukas1994** [comment]
duplicate: https://github.com/ParsePlatform/Parse-SDK-Android/issues/61
