### ISSUE TITLE
ParseCloud callFunction With Headers

### ISSUE THREAD

**Issue by tru3d3v** [ParsePlatform/Parse-SDK-Android#550]
Hi,  How to send my headers data to ParseCloud ?. 

I try to set HasMap but is not work

HashMap<String, Object> headers = new HashMap<String, Object>();
            headers.put("lan","en");

            HashMap<String, Object> prm = new HashMap<String, Object>();
            prm.put("_skip", 0);
            prm.put("_limit", 100);
            prm.put("headers",headers );

 Object result =   ParseCloud.callFunction("myCloudFunction",prm);

Thank You before.

**Comment by rogerhu** [comment]
Set: https://parseplatform.github.io/docs/cloudcode/guide/#setting-headers.  I think this can only be done with Parse Server, but you could implement a Parse cloud function to pass the headers from the Android SDK.
