### ISSUE TITLE
TaskUtils and InterruptedException

### ISSUE THREAD

**Issue by danepowell** [ParsePlatform/Parse-SDK-Android#553]
I have an Android app that periodically crashes when I call save() on a ParseObject. Here is the top of the stack trace:

> java.lang.RuntimeException: java.lang.InterruptedException
>  at com.parse.ParseTaskUtils.wait(ParseTaskUtils.java:47)
>  at com.parse.ParseObject.save(ParseObject.java:1395)

I have no clue what would be throwing this InterruptedException. It's possible that this isn't Parse's fault, but I've never seen this exception anywhere else and I'm not sure how to proceed with debugging this. Can anyone point me in the right direction?

**Comment by danepowell** [comment]
Now I'm seeing this when calling other functions as well, such as `ParseCloud.callFunction`:

> java.lang.RuntimeException: java.lang.InterruptedException
                      at com.parse.ParseTaskUtils.wait(ParseTaskUtils.java:47)
                      at com.parse.ParseCloud.callFunction(ParseCloud.java:83)

Does anyone have any idea how to at least start to troubleshoot this?

**Comment by danepowell** [comment]
At least in the first case, this actually appears to not be a problem with Parse. I was updating Parse objects in an Android Sync Adapter, which apparently can be interrupted if the sync is cancelled. The solution was to override the Sync Adapter `onSyncCanceled` method to prevent the thread from being killed.

**Comment by matthewkrueger** [comment]
Hey @danepowell.  I'm seeing this same crash and I have the same situation as you (Parse inside an Android Sync Adapter).

I've @Override'd onSyncCanceled, but I've no clue what to put inside that method - can you give me any tips for what onSyncCanceled needs to do?  Also, have you seen this issue since you made your original post?

Thanks!

**Comment by danepowell** [comment]
@matthewkrueger you can put anything (or nothing) inside of onSyncCanceled. This is what I have:

```java
@Override
public void onSyncCanceled() {
    Log.d(LOG_TAG, "Sync was cancelled.");
}
```

Depending on how complex or long-running your sync process is, you might want to actually do something in response to a call to onSyncCanceled, such as, I don't know, cancel the sync 😄 (i.e., set a flag that logic in onPerformSync periodically checks and uses to abort the sync gracefully)

I haven't seen this error since implementing this method.
