### ISSUE TITLE
Please update your Android SDK

### ISSUE THREAD

**Issue by sashakhail** [ParsePlatform/Parse-SDK-Android#560]
Respectable Sir / Team

Please update your Parse Android SDK instead of updating server so contentiously. This SDK is not much stable, It gives okhttp errors, Okhttp and parseokhttp conflicts means its behavior is intermittent, Whenever I download file with http of https its give me java.net.UnknownHostException exception or other error some thing like okhttp, and other time same code and same file / same URL works fine, means it behavior is intermittent.

Please Do something and especially at least respond.
Thanks
SashaKhail

**Comment by hatpick** [comment]
This repo seems to be dead. Don't waste your time

**Comment by thphuc** [comment]
Parse-server is updated continuously but Parse Android SDK seems to stop updating?

**Comment by natario1** [comment]
Agreed, this sucks, the library should be maintained by someone who actually uses it.

**Comment by HarishGitCode** [comment]
It seems like we are not having the stable version of SDK for android here. whereas SDK for IOs works like a charm. I have been scratching my head to resolve issues on android.

**Comment by rogerhu** [comment]
Can you send a repo for java.net.UnknownHostException issues?  Closing this because I think you have another ticket opened about it.
