### ISSUE TITLE
Unable to use local store when setting Parser server URL

### ISSUE THREAD

**Issue by jianwatertown** [ParsePlatform/Parse-SDK-Android#562]
In order to migrate existing app to a new service URL, 
_Parse_ object needs to be _initialize_ with a _Parse.Configuration.Builder_:
```
Parse.initialize(new Parse.Configuration.Builder(myContext)
    .applicationId("YOUR_APP_ID")
    .clientKey(null)
    .server("http://localhost:1337/parse/") // The trailing slash is important.
    ...
    .build()
);
```
As suggested here: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#using-parse-sdks-with-parse-server

**However**, _localStore_ cannot be used. As there is no way to set _Parse.isLocalDatastoreEnabled =true_ when _Parse.Configuration.Builder(...)_ is used.

To fix this, the _private_ builder method in _Parse.java#Configuration#Builder_ needs to be changed to _public_

```
Parse.java#Configuration#Builder
...
private Builder setLocalDatastoreEnabled(boolean enabled) {
````
Note, calling the following wouldn't help
```
public static void enableLocalDatastore(Context context) {
```
because Parse.initialize(Configuration) resets localDataStoreEnable value based on _Configuration.localDataStoreEnabled_ which is always set to false(default)

**Comment by alexblack** [comment]
Here's what I do:

```
      Parse.initialize(new Parse.Configuration.Builder(ctx)
        .applicationId(appId)
        .clientKey(clientKey)
        .server(parseServerUrl)
        .enableLocalDataStore()
        .build()
      );
```

**Comment by rogerhu** [comment]
we can close this ticket then right?

**Comment by rogerhu** [comment]
Closing.
