### ISSUE TITLE
SDK locking (no response to requests)

### ISSUE THREAD

**Issue by natario1** [ParsePlatform/Parse-SDK-Android#564]
This is indeed very similar to #556 .

It is very difficult to understand what is causing this issue, but I can tell that at some point, after a request, every subsequent request returns no response. By every request I mean:
- fetches
- queries
- (not sure) saves

No success callback, no fail callback is invoked, and that makes me think that somewhere a task queue is not being emptied, e.g. there’s a lock going on. Parse Server shows no relevant logs, e.g. it seems that the request is not even forwarded.

This does not happen on every device.

I’ll be happy to contribute (i.e. debug deeper: which devices does this happen in? with what network adapters? and so on) if I see that maintainers are really interested in fixing this.

Otherwise this is the right (sad) time I’ll move to maintain it on my own.

**Comment by natario1** [comment]
It happens when loading two files concurrently.

```
public static Task<Void> applyToImage(final ImageView image, 
                                      final ParseFile file, 
                                      final ParseFile preview) {
        final Capture<Boolean> fileSet = new Capture<>(false);
        
        // Load the preview, async
        Log.e(TAG, "applyToImage: STARTING”);
        Task.callInBackground(new Callable<Bitmap>() {
            @Override
            public Bitmap call() throws Exception {
                Log.e(TAG, "preview: getData”);
                byte[] data = preview.getData();
                Log.e(TAG, "preview: gotData”);
                return BitmapFactory.decodeByteArray(data, 0, data.length);
            }
        }).onSuccess(new Continuation<Bitmap, Void>() {
            @Override
            public Void then(Task<Bitmap> task) throws Exception {
                if (!fileSet.get()) image.setImageBitmap(task.getResult());
                return null;
            }
        }, Task.UI_THREAD_EXECUTOR);

        // Load the real picture
        return Task.callInBackground(new Callable<Bitmap>() {
            @Override
            public Bitmap call() throws Exception {
                Log.e(TAG, "mainFile: getData”);
                byte[] data = file.getData();
                Log.e(TAG, "mainFile: gotData”);
                return BitmapFactory.decodeByteArray(data, 0, data.length);
            }
        }).onSuccess(new Continuation<Bitmap, Void>() {
            @Override
            public Void then(Task<Bitmap> task) throws Exception {
                fileSet.set(true); // Stop the preview.
                image.setImageBitmap(task.getResult());
                return null;
            }
        }, Task.UI_THREAD_EXECUTOR);
}
```

When calling this method the first time, I get the logs:

> applyToImage: STARTING
> preview: getData
> mainFile: getData

It never gets beyond (to gotData), and `file.getData()` is not throwing. They are just hanging there, both tasks, will never resolve.

When calling this method the second time, I get only:

> applyToImage: STARTING

So we are not even getting inside `Task.callInBackground()`. The first call (with the two parallel requests) locks everything from then on. This seems to happen on mid-low end devices.

**Comment by natario1** [comment]
- the lock is not triggered only by file fetches. queries and object fetches also make it break, as long as you try to execute a (big enough) pool of tasks in parallel

- doing every async action in an executor like the following:

        new ThreadPoolExecutor(Runtime.getRuntime().availableProcessors() + 1, Integer.MAX_VALUE,
                1, TimeUnit.SECONDS,
                new LinkedBlockingQueue<Runnable>());

does not help. I thought that Task.BACKGROUND_EXECUTOR could be overused, but it does not seem the case.

- happens with the ApacheHttpClient as well as OkHttpClient

**Comment by alexblack** [comment]
Did you try ending the chain with `continueWith` instead of `onSuccess`? Presumably if `getData` throws an exception, then the task will return an error

**Comment by natario1** [comment]
The whole SDK was locked, continueWith was never called.

This was caused by a bad implementation of equals() in one of my ParseObjects. If this happens, the SDK is not closing the SQLite database used for caching and you get stuck forever.

Took days to debug but in the end it was my fault.
