### ISSUE TITLE
Parse-android-1.13.1 version is used,getting this exception with okhttp3 java.lang.IllegalArgumentException: url == null

### ISSUE THREAD

**Issue by AlgoRepublic** [ParsePlatform/Parse-SDK-Android#567]
FATAL EXCEPTION: main java.lang.IllegalArgumentException: url == null at okhttp3.Request$Builder.url(Request.java:133) at com.parse.ParseOkHttpClient.getRequest(ParseOkHttpClient.java:133) at com.parse.ParseOkHttpClient.executeInternal(ParseOkHttpClient.java:64) at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158) at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122) at com.parse.ParseRequest$3.then(ParseRequest.java:136) at com.parse.ParseRequest$3.then(ParseRequest.java:133) at bolts.Task$15.run(Task.java:917) at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) at bolts.Task.completeAfterTask(Task.java:908) at bolts.Task.continueWithTask(Task.java:715) at bolts.Task.continueWithTask(Task.java:726) at bolts.Task$13.then(Task.java:818) at bolts.Task$13.then(Task.java:806) at bolts.Task$15.run(Task.java:917) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) at java.lang.Thread.run(Thread.java:818)

**Comment by sashakhail** [comment]
Sir/Team
This and similar like that error with OkHttpClient occurs with my apps, I tried allot of things to solve it but it occurs with parse, 
Actually This repo needs a serious update but gurus dont even look at Parse Android SDK.
Please come forward Some nice heard gurus and solve this serious problem.
Please Update it so that we can benefit from parse server also. 
Sasha Khail.

**Comment by rogerhu** [comment]
can you provide a repo case?

**Comment by rogerhu** [comment]
It seems you're trying to pass in null to the request? https://github.com/square/okhttp/blob/802c029b82672ea90534e8da1bd42100c194aca9/okhttp/src/main/java/okhttp3/Request.java#L120

Doesn't seem related to this SDK.
