### ISSUE TITLE
Provide a way for ParseFile to stream data to server

### ISSUE THREAD

**Issue by grennis** [ParsePlatform/Parse-SDK-Android#57]
Currently when uploading a file (i.e. image) to the server, all ParseFile constructors require taking a byte array. This requires me to read in the entire file into memory in order to send it.

Please provide a way for ParseFile to accept a stream (i.e., InputStream or StreamReader) and/or local file path so that the content of the file can be streamed to the server without reading the entire thing into memory.

**Comment by grantland** [comment]
Currently being worked on :smile:

**Comment by grennis** [comment]
Awesome thanks!

**Comment by wangmengyan95** [comment]
Related PR #113 and #115 .
