### ISSUE TITLE
Application Id and Client key

### ISSUE THREAD

**Issue by HassanSiddique** [ParsePlatform/Parse-SDK-Android#576]
How Can i get my Application Id and Client key for Android app as **Parse** Sign Up not available yet. I don't have a account on Parse.

**Comment by pulse1989** [comment]
The parse project is closed down. You're meant to be hosting your own parse server (or have one via 3rd party.) The parse server page has more information on how to get started here: 

https://github.com/ParsePlatform/parse-server

once you have it up and running you can generate your own keys

Hope this helps

**Comment by Madhav9085** [comment]
Please Explain this more
How to get client id and application id

**Comment by Jawnnypoo** [comment]
Parse.com no longer exists, you have to create the server yourself using the linked instructions, and when doing so, you will generate the client id and application id.

**Comment by rogerhu** [comment]
See: http://guides.codepath.com/android/Configuring-a-Parse-Server as well.
