### ISSUE TITLE
IllegalStateException: An object cannot be updated if it wasn't fetched when creating new objects

### ISSUE THREAD

**Issue by alexb-geronimo** [ParsePlatform/Parse-SDK-Android#580]
From time to time, when I create a new object and try to save it on Parse I get this exception I don't know why. I have checked for any thread concurrency and everything seems to be fine. I get this when trying to create some new objects one after another or when I delete some objects from the table and then try to create new ones.` ACL Public Read+ Write.`

```
Room room = new Room();
        room.setTitle("title");
        room.setDescription("Description...");
        room.setCreator(user);
        room.addMember(user);
        room.saveInBackground(new SaveCallback() {.
```

> com.parse.ParseException: java.lang.IllegalStateException: An object cannot be updated if it wasn't fetched.
>       at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:114)
>       at android.os.Handler.handleCallback(Handler.java:739)
>       at android.os.Handler.dispatchMessage(Handler.java:95)
>       at android.os.Looper.loop(Looper.java:148)
>       at android.app.ActivityThread.main(ActivityThread.java:5417)
>       at java.lang.reflect.Method.invoke(Native Method)
>       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>   Caused by: java.lang.IllegalStateException: An object cannot be updated if it wasn't fetched.
>       at com.parse.OfflineStore.updateDataForObjectAsync(OfflineStore.java:948)
>       at com.parse.ParseObject$7.then(ParseObject.java:1359)
>       at com.parse.ParseObject$7.then(ParseObject.java:1356)
>       at bolts.Task$15.run(Task.java:917)
>       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>       at bolts.Task.completeAfterTask(Task.java:908)
>       at bolts.Task.continueWithTask(Task.java:715)
>       at bolts.Task.continueWithTask(Task.java:726)
>       at bolts.Task$13.then(Task.java:818)
>       at bolts.Task$13.then(Task.java:806)
>       at bolts.Task$15.run(Task.java:917)
>       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>       at bolts.Task.completeAfterTask(Task.java:908)
>       at bolts.Task.access$100(Task.java:32)
>       at bolts.Task$11.then(Task.java:708)
>       at bolts.Task$11.then(Task.java:705)
>       at bolts.Task.runContinuations(Task.java:956)
>       at bolts.Task.trySetResult(Task.java:994)
>       at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
>       at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
>       at bolts.Task$14.run(Task.java:873)
>       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>       at bolts.Task.completeImmediately(Task.java:863)
>       at bolts.Task.access$000(Task.java:32)
>       at bolts.Task$10.then(Task.java:654)
>       at bolts.Task$10.then(Task.java:651)
>       at bolts.Task.runContinuations(Task.java:956)
>       at bolts.Task.trySetError(Task.java:1011)
>       at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
>       at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
>       at bolts.Task$15$1.then(Task.java:932)
>       at bolts.Task$15$1.then(Task.java:921)
>       at bolts.Task$14.run(Task.java:872)
>       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>       at bolts.Task.completeImmediately(Task.java:863)
>       at bolts.Task.access$000(Task.java:32)
>       at bolts.Task$10.then(Task.java:654)
>       at bolts.Task$10.then(Task.java:651)
>       at bolts.Task.runContinuations(Task.java:956)
>       at bolts.Task.trySetError(Task.java:1011)
>       at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
>       at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
>       at bolts.Task$15$1.then(Task.java:932)
>       at bolts.Task$15$1.then(Task.java:921)
>       at bolts.Task$14.run(Task.java:872)
>       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>       at bolts.Task.completeImmediately(Task.java:863)
>       at bolts.Task.access$000(Task.java:32)
>       at bolts.Task$10.then(Task.java:654)
>       at bolts.Task$10.then(Task.java:651)
>       at bolts.Task.runContinuations(Task.java:956)
>       at bolts.Task.trySetError(Task.java:1011)
>       at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
>       at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
>       at bolts.Task$15$1.then(Task.java:932)
>       at bolts.Task$15$1.then(Task.java:921)
>       at bolts.Task$14.run(Task.java:872)
>       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>       at bolts.Task.completeImmediately(Task.java:863)
>       at bolts.Task.continueWith(Task.java:661)
>       at bolts.Task.continueWith(Task.java:672)
>       at bolts.Task$15.run(Task.java:921)
>       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>       at bolts.Task.completeAfterTask(Task.java:908)
>       at bolts.Task.access$100(Task.java:32)
>       at bolts.Task$11.then(Task.java:708)
>       at bolts.Task$11.then(Task.java:705)
>       at bolts.Task.runContinuations(Task.java:956)
>       at bolts.Task.trySetError(Task.java:1011)
>       at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
>       at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
>       at bolts.Task$15$1.then(Task.java:932)
>       at bolts.Task$15$1.then(Task.java:921)
>       at bolts.Task$14.run(Task.java:872)
>       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>       at bolts.Task.completeImmediately(Task.java:863)
>       at bolts.Task.continueWith(Task.java:661)
>       at bolts.Task.continueWith(Task.java:672)
>       at bolts.Task$15.run(Task.java:921)
>       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>       at bolts.Task.completeAfterTask(Task.java:908)
>       at bolts.Task.access$100(Task.java:32)
>       at bolts.Task$11.then(Task.java:708)
>       at bolts.Task$11.then(Task.java:705)
>       at bolts.Task.runContinuations(Task.java:956)
>       at bolts.Task.trySetResult(Task.java:994)
>       at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
>       at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
>       at bolts.Task$15$1.then(Task.java:934)
>       at bolts.Task$15$1.then(Task.java:921)
>       at bolts.Task$14.run(Task.java:872)
>       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>       at bolts.Task.completeImmediately(Task.java:863)
>       at bolts.Task.continueWith(Task.java:661)
>       at bolts.Task.continueWith(Task.java:672)
>       at bolts.Task$15.run(Task.java:921)
>       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>       at bolts.Task.completeAfterTask(Task.java:908)
>       at bolts.Task.access$100(Task.java:32)
>       at bolts.Task$11.then(Task.java:708)
>       at bolts.Task$11.then(Task.java:705)
>       at bolts.Task.runContinuations(Task.java:956)
>       at bolts.Task.trySetResult(Task.java:994)
>       at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
>       at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
>       at bolts.Task$15$1.then(Task.java:934)
>       at bolts.Task$15$1.then(Task.java:921)
>       at bolts.Task$14.run(Task.java:872)
>       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>       at bolts.Task.completeImmediately(Task.java:863)
>       at bolts.Task.continueWith(Task.java:661)
>       at bolts.Task.continueWith(Task.java:672)
>       at bolts.Task$15.run(Task.java:921)
>       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>       at java.lang.Thread.run(Thread.java:818)

**Comment by abhisheksalokhe** [comment]
Hi, may I know how are you accessing `user` for `setCreator` & `addMember` methods? I don't see any issue with saving your `Room` object.

**Comment by natario1** [comment]
Are you doing something strange in Room?
Maybe you have overriden equals() ? In that case, don’t.

**Comment by hermanliang** [comment]
Agree with @abhisheksalokhe  
Execute `user.fetch()` before creating Room may solve the problem.

**Comment by rogerhu** [comment]
Going to close then unless there is more info
