### ISSUE TITLE
cannot run the project

### ISSUE THREAD

**Issue by varun9696** [ParsePlatform/Parse-SDK-Android#581]
error:
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzqq$zza.class

gradle file:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId "com.moneytracker.moneytracker"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {

    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.google.firebase:firebase-ads:10.0.1'
    compile 'com.android.support:support-v4:23.0.1'

}

apply plugin: 'com.google.gms.google-services'

**Comment by Jawnnypoo** [comment]
This error is completely irrelevant to this SDK, its a conflict with the fact that you are including Google Play Services twice in your project. You don't even have the Parse SDK being compiled from what you pasted in here. @rogerhu This can be closed.
