### ISSUE TITLE
bad json response in parse 1.13.1

### ISSUE THREAD

**Issue by Amr-Elsharawi** [ParsePlatform/Parse-SDK-Android#582]
the Application has been working three months ago, but now there is this problem.
bad json response in parse 1.13.1
org.json.JSONException: Value ��������������� of type java.lang.String cannot be converted to JSONObject

**Comment by rogerhu** [comment]
Do you have a repro?  Can you add the StethoInterceptor to see what's coming back? http://guides.codepath.com/android/Configuring-a-Parse-Server#troubleshooting-parse-server

**Comment by Jawnnypoo** [comment]
I don't think this actually links back to the Parse SDK, I believe this was actually an attempt to fetch data from Parse that was saved as a String, then attempted to be fetched as a JSONObject. @Amr-Elsharawi  Make sure you are fetching the data in the same format that you stored it in.

**Comment by rogerhu** [comment]
Closing then..
