### ISSUE TITLE
Return null data for everything

### ISSUE THREAD

**Issue by mikelanza** [ParsePlatform/Parse-SDK-Android#583]
Hi,

 if I extends any object from ParseObject or ParseUser, it everytime returns me null for every variable it contains. For example:

```
public class User extends ParseUser {

    private boolean emailVerified;
    private String facebookID;

    private int fiveHundredID;
    private String fiveHundredUsername;

    private String firstName;
    private String lastName;

    private String canonicalFirstName;
    private String canonicalLastName;

    private Date birthday;
    private Photo profilePicture;

    private int followeeCount;
    private int followerCount;

}
```

And then I call User.fetchInBackground(), it doesn't fill any variable except objectId, email and the others variable, that are contained only in ParseUser class. Of course, I already initialize Parse in App class like:

```
Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE);
Parse.enableLocalDatastore(getApplicationContext());
Parse.initialize(new Parse.Configuration.Builder(getApplicationContext())
        .applicationId(Const.X_PARSE_APPLICATION_ID)
        .clientKey(Const.X_PARSE_REST_API_KEY)
        .server(Const.PARSE_SERVER_URL)
        .enableLocalDataStore()
        //.addNetworkInterceptor(new JsonInterceptor())
        .build());

ParseObject.registerSubclass(User.class);
```

Im not using any proguard, because Im testing that on the Debug version. Any help? Also when I have enabled LocalDataStore, it store my current User. But when I call fetchInBackground(), it returns me the same data as Local data are stored. Also when I call unpinInBackground() and after that I'll call fetchInBackground(), it still returns me the local data stored in DB. 

Any help?

Many thanks

**Comment by itolisto** [comment]
Hi @mikelanza are you using annotations? You must use **@ParseClassName("className")**. To get/set a variable you can use a method. For example:

```
@ParseClassName("_User")
public class Account extends ParseUser {

    public String getDisplayName() {
        return getString("displayName");
    }

   public void setDisplayName(String displayName) {
        put("displayName", displayName);
    }

}
```

And you are registering your subclass after you initialize Parse, this is incorrect, you must register any subclass before initialize Parse.

```
ParseObject.registerSubclass(Account.class);
// Initialize Parse.
Parse.initialize(this, "PARSE_APP_ID");
```

Hope it helps you!
