### ISSUE TITLE
Can we able to migrate existing live project to other technology?

### ISSUE THREAD

**Issue by partikles** [ParsePlatform/Parse-SDK-Android#585]
We have completed a project in iOS/Android and planning to go live soon. We worried that iOS/Android SDKs won't be updated like facebook did.

What is the best way of migrating Live ParsePlatform project iOS/Android ? Because of Client & Server SDK, everything interconnected.

Guide Us.

https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/1109

**Comment by rogerhu** [comment]
Being discussed here: https://github.com/ParsePlatform/parse-server/issues/3356
