### ISSUE TITLE
IllegalStateExceptions thrown when using query.selectKeys()

### ISSUE THREAD

**Issue by natario1** [ParsePlatform/Parse-SDK-Android#595]
I am inclined to believe that this is a Android SDK bug rather than parse-server.

Steps to reproduce:

1. Create a TestTable like the following, with just to objects:

        key:        foo            bar           else
                    “yes”          111           “unwanted key”
                    “yes”                        “unwanted key”
    
    That is,

        ParseObject o1 = new ParseObject(“TestTable”);
        o1.set(“foo”, “yes”);
        o1.set(“bar”, 111);
        o1.set(“else”, “unwanted key”);
        o1.save();
        ParseObject o2 = new ParseObject(“TestTable”);
        o2.set(“foo”, “yes”);
        o2.set(“else”, “unwanted key”);
        o2.save();

2. No issues arise if you call find() as is:

        ParseQuery q = ParseQuery.getQuery(“TestTable”);
        List<ParseObject> objs = q.find();

    Calling `obj.getInt(“bar”)` will return 111 for the first object, 0 for the second.
    That’s what we are used to.

3. But if we want to exclude the “else” key,

        ParseQuery q = ParseQuery.getQuery(“TestTable”);
        q.selectKeys(Arrays.asList(“foo”, “bar”));
        List<ParseObject> objs = q.find();

    Calling `obj.getInt(“bar”)` returns 111 for the first object indeed, but throws an exception for the first object, the IllegalStateException asking you to fetch the object.

I hope the report is clear: if a selected key exists in the server but is simply undefined, <strike> `obj.has(“key”)` incorrectly returns false</strike> `obj.get(“key”)` incorrectly throws. This makes selectKeys() useless for any table that might have some undefined data among the selected keys. I am surprised this was not brought up yet.

_Note: make sure to wipe out app cache between point 2 or 3, or 3 will work because the object is cached. Or, just test 3. before testing 2._

Thank you @rogerhu for stepping up, I am happy to see this back on track.

**Comment by natario1** [comment]
I have looked for issues in the JSON decoding but there aren't. As far as I can see the issue is much simpler (and harder to fix):

Get calls [do not fail](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseObject.java#L3435) if `object.isDataAvailable() || estimatedData.containsKey(key)` returns true. That is,  _object is complete, or it is not but we got key data from the server_.

For our object `estimatedData.containsKey(key)` will always be false, because the server is not sending that data neither in case 2 nor 3. The bad thing is that `isDataAvailable()` (i.e. object is complete) returns true in case 2, and false in case 3, [because we selected some keys](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/NetworkQueryController.java#L139).

The worst part (for this bug) is that this behavior makes actually sense, e.g. it’s clear that in case 3 `object.isDataAvailable() || estimatedData.containsKey(key)` must be false. I can’t see any elegant fix. We might have to add a `safeKeys` set to `ParseObject` and check that `key` is contained there to enable get access.

**Comment by rogerhu** [comment]
So iOS throws an exception too:

```2017-03-12 10:01:42.423 ParseFun[34091:3327744] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Key "elseKey" has no data.  Call fetchIfNeeded before getting its value.'
*** First throw call stack:
(
```

```swift
class TestTable: NSObject {
    var foo: String
    var bar: String
    var elseKey : String

    override init() {
        self.foo = ""
        self.bar = ""
        self.elseKey = ""
    }
}

```

Saving the entries:

```swift
       let o1 = PFObject(className: "TestTable");
        o1["foo"] = "yes";
        o1["bar"] = 111;
        o1["elseKey"] = "unwanted key";

        do {
         try o1.save()
        } catch {
            print("Error saving o1")
        }
        let o2 = PFObject(className: "TestTable");
        o2["foo"] = "yes";
        o2["elseKey"] = "unwanted key";

        do {
            try o2.save()
        } catch {
            print("Error saving o2")
        }
```

Querying the data will crash if selectKeys() is used:

```swift
        let pf = PFQuery(className: "TestTable");
        do {
            // comment/uncomment this line
            pf.selectKeys(["foo", "bar"]);
            let objs = try pf.findObjects()
            print("objs: \(objs)")

            for obj in objs {
                let fooVal = obj.value(forKey: "foo") as! String
                let elseVal = obj.value(forKey: "elseKey") as! String
                print("obj: fooVal: \(fooVal) elseKey: \(elseVal)")
            }
//            print("obj0: " . objs[0].elseKey);
 //           print("obj1: " . objs[1]["else"])
        } catch {
            print("Error querying")
        }
```

**Comment by natario1** [comment]
@rogerhu I can barely read iOS code, but I think you should try `obj.value(forKey: “bar”)` , that’s where we fail for o2. Throwing on `elseKey` access seems legit because it was not selected.

**Comment by rogerhu** [comment]
```swift
            for obj in objs {
                let fooVal = obj.value(forKey: "foo") as! String
                let barVal = obj.value(forKey: "bar") as! Int
                print("obj: fooVal: \(fooVal) barVal: \(barVal)")
            }

```

Outputs:

```
obj: fooVal: yes barVal: 111
fatal error: unexpectedly found nil while unwrapping an Optional value

```

**Comment by rogerhu** [comment]
Let me change to optional...1 sec

**Comment by rogerhu** [comment]
Works fine:

```

            for obj in objs {
                let fooVal = obj.value(forKey: "foo") as! String
                let barVal = obj.value(forKey: "bar") as? Int
                print("obj: fooVal: \(fooVal) barVal: \(barVal)")
            }

```
obj: fooVal: yes barVal: Optional(111)
obj: fooVal: yes barVal: nil
```
