### ISSUE TITLE
Duplicate Notification.

### ISSUE THREAD

**Issue by parseserverpush** [ParsePlatform/Parse-SDK-Android#608]
Hi Team.

When user uninstalls the app and installs it again it creates a duplicate installation object. we sending push notify them device get duplicate notification . Plesae help me. Thanks Team.

<img width="855" alt="screen shot 2017-03-20 at 14 51 36" src="https://cloud.githubusercontent.com/assets/19681442/24091839/2eb2decc-0d7d-11e7-8c46-95b90bab0024.png">

**Comment by rogerhu** [comment]
There's no way to avoid this issue unless we move to GCM Sender ID's as the unique install ID's:

See: https://github.com/ParsePlatform/Parse-SDK-Android/issues/572

**Comment by rogerhu** [comment]
Your best bet is to dedup the push notifications.  Do we not do this on the GCM push side?  In any case it's related more to the push adapter right now I believe..

**Comment by flovilmart** [comment]
I believe there should be something on Parse-server that would prevent that duplication but I'm not sure

**Comment by parseserverpush** [comment]
Ok.Thanks u.
