### ISSUE TITLE
ParseObject.pin() takes longer time with more objects saved in LocalDataStore

### ISSUE THREAD

**Issue by noughts** [ParsePlatform/Parse-SDK-Android#61]
It seems that ParseObject.pin() takes longer time with more objects saved in LocalDataStore
When LocalDataStore is empty, it takes only 500ms to pin 10 ParseObjects.
When there are 500 objects in LocalDataStore, it takes 2,000ms to pin.
When there are 1,000 objects in LocalDataStore, it takes 4,000ms to pin.

Of course we can avoid UI blocking by using pinInBackground, but meanwhile it seems that other pins and query processes are blocked, so when users transit to the next screen that uses ParseQueryAdapter right after pinInBackground, there's a black moment we can't show any data until pinInBackground is done.

I've attached a repro project file using Starter Project.
https://dl.dropboxusercontent.com/u/309225/ParseLocalDataStorePerformance.zip
By running it, you can see that pin is repeated, and its process time gets longer and longer.

Is there any way to make this faster?
Thanks for your advice.

Environment:
Galaxy Nexus Android 4.2.2
Parse SDK 1.10.1

**Comment by lukas1994** [comment]
I can confirm linear dependency on the number of objects: https://gist.github.com/lukas1994/67834f6cc1a6f12ed4dc

**Comment by grantland** [comment]
See #279
