### ISSUE TITLE
Problem with unity Game engine

### ISSUE THREAD

**Issue by kami-j** [ParsePlatform/Parse-SDK-Android#62]
Hello 

I have found a vital problem using parse in unity engine. we have developed a game  using unity  which works perfectly fine without using parse. The problem is that when we attach the parse to our game, in the first opening of the game application on ANDROID - IF YOU CLICK IN A FEW SECOND RIGHT AFTER INSTALLATION- a force close happens. After some deliberation, I came to know that the problem happens right at the initialization of the parse due to some code related to " Receiver Functions" in manifest. 
receiver android:name="com.parse.ParsePushBroadcastReceiver"

When I remove this part of the code the application works fine ; But , when existing, There is a problem if you click on open in a few minutes right at the beginning of the installation.

I'd be so appreciated if you could answer me as soon as possible since the game's release date is about to arrive. 
Thank you so much for your attention

**Comment by grantland** [comment]
This repo is only for issues regarding our Android SDK. You can find resources for our Unity SDK [here](https://parse.com/help).
