### ISSUE TITLE
Link to facebook alway successfull in case of got exception

### ISSUE THREAD

**Issue by kenilt** [ParsePlatform/Parse-SDK-Android#64]
I'm using Parse 1.10.1 and ParseFacebookUtils 1.10.1
When I try to link to facebook function, i got a problem. 
Here is my simple code:
 
    List<String> permissions = Arrays.asList("public_profile", "email", "user_birthday");
    ParseFacebookUtils.linkWithReadPermissionsInBackground(ParseUser.getCurrentUser(), activity, permissions, new SaveCallback() {
        @Override
        public void done(ParseException e) {
            if (ParseFacebookUtils.isLinked(user)) {
                // linked success
                
            } else if (e != null) {
                // has error
                if (e.getCode() == 208) {
                    MaterialDialogUtils.showOopsMaterialDialogs(activity, "Another user is already linked to this facebook ID. Please try another FB account.");
                } else {
                    MaterialDialogUtils.showOopsMaterialDialogs(activity, "Can't link your account to FB. Code = " + e.getCode());
                }
            }
        }
    });

The problem is this function is alway successfull, when I link to a user has linked by another parseUser, It's return errorCode 208, but ParseFacebookUtils.isLinked(user) is true.
Is it a bug of ParseFacebookUtils?

**Comment by grantland** [comment]
This is working as intended. What you're seeing is that the `user` currently has Facebook auth data attached to it, but is currently in a dirty state as the request has failed. 

You should update your callback as the request has only succeeded if `e != null`.

**Comment by kenilt** [comment]
When I check this function again <code>ParseFacebookUtils.isLinked(user)</code> in some where, it's return true, but <code>currentUser</code> not linked to any Facebook account, and <code>currentUser</code> don't have <code>authData</code> on parse.com

**Comment by grantland** [comment]
The information isn't persisted on the server as your request failed, however, the `ParseUser` you have locally has the `authData` attached since it attempted to link to a Facebook account, but failed. Since it has it locally, `ParseFacebookUtils.isLinked(user)` will return `true.

**Comment by SobanMahmood** [comment]
This behavior of ParseFacebookUtils library does not seem to be correct. Because this may produce inconsistencies in some cases as on server user is saved as Anonymous user whereas on device it is non-Anonymous user. So I think ParseFacebookUtils.isLinked(user) should return false after failed linking.
Also I think on iOS platform, if this 208 error occurs, iOS version of this library do not start returning true for ParseFacebookUtils.isLinked(user) instead it returns false. I am not sure about this though as I am an Android guy. This behavior seems consistent with the server.
I tried to use persistent storage for tracking if user is actually not linked, which was overkill. Then I have managed to retain correct state by calling ParseFacebookUtils.unlink(user) for current user in case 208 error had occurred. I am not sure if this workaround is correct, but it seems to be working.
By the way even if this behavior seems fine this should be mentioned in docs and sample codes.

It has possible workarounds, but I still think that library behavior needs to be changed.

**Comment by SobanMahmood** [comment]
@grantland could you please help a little here.
Could this issue be reopened as suggested in my last comment, or should I create new issue for it, or is it not worth it?

**Comment by kenilt** [comment]
@SobanMahmood I tried to find some solution for this problem, Finally I called unlikFacebook account if I got error code 208 in response, I wrote some code like below:

    List<String> permissions = Arrays.asList("public_profile", "email", "user_birthday");
    ParseFacebookUtils.linkWithReadPermissionsInBackground(currentUser, getActivity(), permissions, new SaveCallback() {
        @Override
        public void done(ParseException e) {
            if (e != null) {
                // has error
                if (e.getCode() == 208) {
                    ParseFacebookUtils.unlinkInBackground(ParseUser.getCurrentUser());
                    MaterialDialogUtils.showOopsMaterialDialogs(getActivity(), "Another user is already linked to this facebook ID. Please try another FB account.");
                } else {
                    MaterialDialogUtils.showOopsMaterialDialogs(getActivity(), "Can't link your account to FB. Code = " + e.getCode());
                }
            } else if (LoginHelper.isLinkedWithFacebook()) {
                // linked success
            }
        }
    });

**Comment by SobanMahmood** [comment]
Thank you @kenilt . That seems to be working. I am using the similar solution. For more consistency with future version changes, I have also included `ParseFacebookUtils.isLinked(user)` condition before calling unlink in case of error 208 like this.
```
            ...
            if (e.getCode() == 208) {
                if (ParseFacebookUtils.isLinked(ParseUser.getCurrentUser())) {
                    ParseFacebookUtils.unlinkInBackground(ParseUser.getCurrentUser());
                }
                MaterialDialogUtils.showOopsMaterialDialogs(getActivity(), "Another user is already linked to this facebook ID. Please try another FB account.");
            } else {
            ...
```
