### ISSUE TITLE
No deviceToken on Android 6 (API 23)

### ISSUE THREAD

**Issue by tuomaslaa** [ParsePlatform/Parse-SDK-Android#65]
I noticed that I can't get deviceToken with Android 6 (emulator). I tried also with Android 5 emulator and it works. Can't test with the real device yet because I don't have compatible device.

Is Android Parse SDK prepared also for these changes:
*In Android 6 SDK app has to request permissions in runtime. 
*In Android 6 SDK device goes to Doze mode which means that "Network access is disabled, unless your app receives a high-priority Google Cloud Messaging".

**Comment by wangmengyan95** [comment]
@tuomaslaa thanks for open the issue. Have you installed google play service in your emulator? Could you provide us with the following information:
* Enable logging in our SDK with Parse.setLogLevel(Log.VERBOSE) and paste the logcat.

* Your entire AndroidManifest.xml with any private information removed.

Thanks.

**Comment by grantland** [comment]
> * In Android 6 SDK app has to request permissions in runtime. 

The only portion of our SDK that uses anything that would require runtime permissions is `ParseGeoPoint.getCurrentLocation()`, in which we expect the developer to properly check/verify/request location permissions.

> * In Android 6 SDK device goes to Doze mode which means that "Network access is disabled, unless your app receives a high-priority Google Cloud Messaging".

Our core SDK does not run any background services on it's own, so this shouldn't be a problem.

**Comment by tuomaslaa** [comment]
@wangmengyan95 You are right about google play service. It's missing from the device image. 

and because of that in I can see on logcat:
PackageManager: Unknown permission com.android.vending.BILLING
PackageManager: Unknown permission com.google.android.c2dm.permission.RECEIVE 

@grantland Good to know. 

Thank you very much both of you.

**Comment by grantland** [comment]
No problem! I'll be closing this issue now since it has been resolved.
