### ISSUE TITLE
PPNS is not working properly

### ISSUE THREAD

**Issue by silviucpp** [ParsePlatform/Parse-SDK-Android#66]
Hello I just installed the tutorial on a device and tested the pushes. If we use GCM is working fine all pushes being delivered. Once we remove the GCM from android manifest we can see in logs that the app is using the ppns but seems the ppns service is reconnecting in loop.

08-26 16:20:25.175  21482-21482/com.parse.starter V/com.parse.ManifestInfo﹕ Using ppns for push.
08-26 16:20:25.225  21482-21534/com.parse.starter V/com.parse.CachedCurrentInstallationController﹕ Successfully deserialized Installation object
08-26 16:20:25.235  21482-21482/com.parse.starter D/StarterApplication﹕ 5d0c6c16-5c45-43a5-b347-1fff6ae9a69a
08-26 16:20:25.235  21482-21482/com.parse.starter W/ApplicationPackageManager﹕ getCSCPackageItemText()
08-26 16:20:25.245  21482-21482/com.parse.starter I/PersonaManager﹕ getPersonaService() name persona_policy
08-26 16:20:25.285  21482-21482/com.parse.starter I/dalvikvm﹕ Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
08-26 16:20:25.285  21482-21482/com.parse.starter W/dalvikvm﹕ VFY: unable to resolve virtual method 449: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
08-26 16:20:25.285  21482-21482/com.parse.starter D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
08-26 16:20:25.285  21482-21482/com.parse.starter I/dalvikvm﹕ Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
08-26 16:20:25.285  21482-21482/com.parse.starter W/dalvikvm﹕ VFY: unable to resolve virtual method 471: Landroid/content/res/TypedArray;.getType (I)I
08-26 16:20:25.285  21482-21482/com.parse.starter D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
08-26 16:20:25.345  21482-21482/com.parse.starter V/PPNSService﹕ Received request to start service if required
08-26 16:20:25.345  21482-21482/com.parse.starter D/StarterApplication﹕ sbscribed to aila
08-26 16:20:25.345  21482-21482/com.parse.starter I/StarterApplication﹕ Installation saved successfully
08-26 16:20:25.345  21482-21546/com.parse.starter V/com.parse.PushConnection﹕ PushConnection transitioning from com.parse.PushConnection$WaitStartState@42b41aa0 to com.parse.PushConnection$ConnectState@42b4b260
08-26 16:20:25.376  21482-21482/com.parse.starter I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:381>: EGL 1.4 QUALCOMM build:  (CL3869936)
    OpenGL ES Shader Compiler Version: 17.01.11.SPL
    Build Date: 01/17/14 Fri
    Local Branch:
    Remote Branch:
    Local Patches:
    Reconstruct Branch:
08-26 16:20:25.426  21482-21482/com.parse.starter D/OpenGLRenderer﹕ Enabling debug mode 0
08-26 16:20:26.066  21482-21546/com.parse.starter V/com.parse.PushConnection﹕ PushConnection transitioning from com.parse.PushConnection$ConnectState@42b4b260 to com.parse.PushConnection$ConnectedState@42c41b30
08-26 16:20:26.226  21482-21546/com.parse.starter V/com.parse.PushConnection﹕ PushConnection transitioning from com.parse.PushConnection$ConnectedState@42c41b30 to com.parse.PushConnection$WaitRetryState@42c68230
08-26 16:20:26.226  21482-21546/com.parse.starter V/com.parse.PushConnection﹕ PushConnection transitioning from com.parse.PushConnection$WaitRetryState@42c68230 to com.parse.PushConnection$ConnectState@42c68e50
08-26 16:20:27.037  21482-21546/com.parse.starter V/com.parse.PushConnection﹕ PushConnection transitioning from com.parse.PushConnection$ConnectState@42c68e50 to com.parse.PushConnection$ConnectedState@42cd1070
08-26 16:20:27.247  21482-21546/com.parse.starter V/com.parse.PushConnection﹕ PushConnection transitioning from com.parse.PushConnection$ConnectedState@42cd1070 to com.parse.PushConnection$WaitRetryState@42ce6eb8
08-26 16:20:27.247  21482-21546/com.parse.starter V/com.parse.PushConnection﹕ PushConnection transitioning from com.parse.PushConnection$WaitRetryState@42ce6eb8 to com.parse.PushConnection$ConnectState@42ce79e8
08-26 16:20:28.168  21482-21546/com.parse.starter V/com.parse.PushConnection﹕ PushConnection transitioning from com.parse.PushConnection$ConnectState@42ce79e8 to com.parse.PushConnection$ConnectedState@42d4d068
08-26 16:20:28.348  21482-21546/com.parse.starter V/com.parse.PushConnection﹕ PushConnection transitioning from com.parse.PushConnection$ConnectedState@42d4d068 to com.parse.PushConnection$WaitRetryState@42d6a010
08-26 16:20:28.348  21482-21546/com.parse.starter V/com.parse.PushConnection﹕ PushConnection transitioning from com.parse.PushConnection$WaitRetryState@42d6a010 to com.parse.PushConnection$ConnectState@42d6ab40
08-26 16:20:29.830  21482-21546/com.parse.starter V/com.parse.PushConnection﹕ PushConnection transitioning from com.parse.PushConnection$ConnectState@42d6ab40 to com.parse.PushConnection$ConnectedState@42de59d8

Looking into the PushConnection source code (over the sources resulted from AndroidStudio decompiler)

Seems in this method readLine is always null. I guess the server close the connection and the client tries to reconnect. 

           private void runReaderLoop(BufferedReader reader) {
            while(true) {
                String line = null;

                try {
                    line = reader.readLine();
                    PushConnection.this.lastReadTime.set(SystemClock.elapsedRealtime());
                } catch (IOException var9) {
                    ;
                }
        ......

Any idea on how can I debug on what's going wrong ? I tried several devices all behaves in the same way.

Silviu

**Comment by wangmengyan95** [comment]
@silviucpp thanks for opening this issue. Is there a reason you don't want to use GCM push? For GCM enabled device, we strongly recommend you to use GCM push instead of PPNS.

**Comment by silviucpp** [comment]
Hello, the main reason is that GCM is very unstable and unreliable. We found a lot of use cases where GCM pushes are not delivered comparing with other apps that bypass GCM like: Viber or Watsapp and I think also FB Messenger. 

Anyway we succeed to make the PPNS working but not sure what was the problem. We will try to test how PPNS behaves on all scenarios we have and what impact has against the battery.

Silviu

**Comment by wangmengyan95** [comment]
@silviucpp one thing maybe you should pay attention is in new Android M, google introduce doze mode which will disable the network access for the app. Since PPNS relies on the long persistent connection to Parse server, PPNS will be effected. 
Since you have solved the problem, I will close this for now. Feel free to reopen it when you have further questions.
