### ISSUE TITLE
ParseObjectCoder.encode is not thread-safe

### ISSUE THREAD

**Issue by hallucinogen** [ParsePlatform/Parse-SDK-Android#76]
`ParseObjectCoder.encode` signature accepts `ParseObject.State`, `ParseOperationSet` and `ParseEncoder`. While `ParseObject.State` and `ParseEncoder` is immutable and thread-safe, `ParseOperationSet` can be mutated anytime and is not guarded by any mutex. We need to either guard the `ParseOperationSet` with mutex or make a copy of this `ParseOperationSet` somewhere and pass the copy to `ParseObjectCoder.encode`.

**Comment by hallucinogen** [comment]
This is an example of how `ParseObjectCoder.encode` is not thread-safe: https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/NetworkUserController.java#L41

**Comment by lukas1994** [comment]
We could make a deep-copy of the operation set in ```encode()``` but that might not be very efficient. What do you think?

**Comment by hallucinogen** [comment]
Deep-copy won't solve the problem I mentioned in #78.

**Comment by lukas1994** [comment]
from https://github.com/ParsePlatform/Parse-SDK-Android/pull/78 :
I checked all places where ```ParseOperationSet``` is used and couldn't find any concurrency issues.
The scenario you described above can't happen because if ```save()``` gets called a new ```ParseOperationSet``` gets enqueued (to ```operationSetQueue```) and all methods mutate the top of the queue.

**Comment by hallucinogen** [comment]
Sounds good. Closing this one
