### ISSUE TITLE
ParseQuery.findInBackground() never calls FindCallback.done()

### ISSUE THREAD

**Issue by VictorOjeda** [ParsePlatform/Parse-SDK-Android#8]
Trying to make a ParseQuery.findInBackground never receives the callback ParseUser.done().

    Steps to reproduce the bug:
    1.- Call ParseQuery.findInBackground after it has been called in different places.
    2.- Notice done callback stops being invoked.

For further details, please refer to this bug:
https://developers.facebook.com/bugs/451257781712794/?search_id

**Comment by stanleyw** [comment]
We are switching to GitHub issues for new bugs found after today.  However, since your bug was already previously filed in the FB bug tracker, let's use that to discuss it.

**Comment by wangmengyan95** [comment]
@stanleyw, it seems the DSE guy open a same issue here, so maybe let's discuss it here?
