### ISSUE TITLE
Push sent with REST API is received on 2 different devices

### ISSUE THREAD

**Issue by aila-cherim** [ParsePlatform/Parse-SDK-Android#80]
Hi,
I installed your stater project on 2 devices, i got 2 installation ids.
device 1: b5eb7d9c-90c7-4540-89e0-087def1e5f6b (does not have google play services)
device 2 : 030d7e15-a7bc-48a3-8c29-27f888a37759 (has google play services)

I sent a push message using curl

curl -X POST \
-H "X-Parse-Application-Id: 14BflXC3svxopSMAa5phOTbD40mwdmViu6J8Z2qi" \
-H "X-Parse-REST-API-Key: efJgKlzORqXpyUniFU1S4reZqloi9mD5ACG8aNxy" \
-H "X-Parse-Installation-Id: b5eb7d9c-90c7-4540-89e0-087def1e5f6b" \
-H "Content-Type: application/json" \
-d '{
"where": {
"channels": "silviu"
},
"data": {
"alert": "Alert message here."
}
}' \
https://api.parse.com/1/push

I put in header the installation id because i want to target one specific device.

Both devices are subcribed to channel "silviu".

Push message is received on both devices.

This wasn't happening from the beginning, we tested with installation id in header and the push message was received on the targeted device. Somehow yesterday when we tested the push message was received on both devices.

Is something changed on your side or is my command wrong?

Thank you.

**Comment by grantland** [comment]
You're not supposed to use `X-Parse-Installation-Id` to target specific `installationId`s. This is supposed to be done in the `where` clause in your REST command. Please refer to the following message for more information.
