### ISSUE TITLE
How to get parseObjet from jsonObject

### ISSUE THREAD

**Issue by jyoungrok** [ParsePlatform/Parse-SDK-Android#84]
I'm developing push notification including ParseObject in data field 
As you know, PushBroadcastReceiver should process received push notification.
So parse object should be jsonobject, but i don't know how to convert this object to parse object 

I tried below codes, but It represented error (I added parse object to data field and Picture is subclass of parseobject)

``
    JSONObject receiveData = new JSONObject(intent.getExtras().getString("com.parse.Data"));
     Picture picture= (Picture) receiveData.get("data");
``

``
Caused by: java.lang.ClassCastException: org.json.JSONObject cannot be cast to com.claude.sharecam.parse.Picture
``

Please, explain me how to get parse object from push notification

**Comment by jyoungrok** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

jyr3357@naver.com 님께 보내신 메일 <Re: [Parse-SDK-Android] How to get parseObjet from jsonObject (#84)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by wangmengyan95** [comment]
Hi @jyoungrok , right now `ParseObject` is not parcelable and serializable, so you can not pass a `ParseObject` around through an `intent`. 
If your data in the `ParseObject` is not so complicated and can be parcelable or serializable,  you can directly put them in your intent.
You can also put `objectId` in your intent. When you get the `objectId` from the push notification, you can use  `setObjectId()` and `fetchInBackground()` to recreate the exactly `ParseObject`.
Hope it helps.

**Comment by jyoungrok** [comment]
@wangmengyan95  thank you for your comment
Howerver, It's so bad news for me that I should make another request for fetching....
so inefficient...

Is there any plan to make ParseObject parcelable or serializable?

**Comment by grantland** [comment]
In terms of allowing decoding a `ParseObject` from `JSONObject` for push notifications, no we don't have any plans for this right now. You generally wouldn't be modifying an object received from a push notification, so there's no real need for this functionality. As Mengyan described, you can inflate your `Notification` with the `JSONObject` and use `ParseObject.createWithoutData(className, objectId)` and `object.fetchInBackground()` if you need the `ParseObject` instance.

Regarding `ParseObject` implementing `Parcelable` or `Serializable`, let's move that conversation into #122.

**Comment by thomasdao** [comment]
@grantland I saw in the source code there is a method [fromJSON](https://github.com/ParsePlatform/Parse-SDK-Android/blob/a7f3f9b71ed24978e8dd0b675b88e6d5e19f41dd/Parse/src/main/java/com/parse/ParseObject.java#L647) which converts JSON to ParseObject. I wonder why you don't expose it to client to use. While it's easy to do `object.fetchInBackground()`, it's slow especially on mobile where user do not always has good internet connection. I hope you do consider to expose it to client to use, maybe mark it as unsafe or something, which client can fallback on fetching object from server if the conversion fails

**Comment by thomasdao** [comment]
@grantland I also do the exactly the same thing on iOS, where method `
+ (id)_objectFromDictionary:(NSDictionary *)dictionary defaultClassName:(NSString *)defaultClassName  completeData:(BOOL)completeData;` is private, but thanks to Objective C, I still can call it. I do wrap it in a try catch to prevent bad thing happens and fall back on fetching on server. This gives much better performance since the app don't have to fetch every messages arrived
