### ISSUE TITLE
Parse database next page loader

### ISSUE THREAD

**Issue by ijazfahad** [ParsePlatform/Parse-SDK-Android#9]
I'm using a custom view adapter and not the parse query adapter. Is there any that I can load the next page of the database without using Parse query adapter?

**Comment by wangmengyan95** [comment]
Hi @ijazfahad, we provide `setSkip()` method for a `ParseQuery`, you can use this method to set the skip number you want and load the next page. We also open source `ParseQueryAdapter`, you can take a look how we do that through this link [GitHub](https://github.com/ParsePlatform/ParseUI-Android/blob/master/ParseLoginUI/src/com/parse/ParseQueryAdapter.java). Hope it helps.

**Comment by ijazfahad** [comment]
oh i didn't even think about that. Thanks for the help :)
