### ISSUE TITLE
createWithoutData does not create...without data - Pointer User Exception

### ISSUE THREAD

**Issue by thieu75** [ParsePlatform/Parse-SDK-Android#95]
Hi !

I have a Class Game, extended from ParseObject. In this class there are 2 pointers : targetUser and senderUser. Those pointers are pointing to my User class (extends ParseUser).

senderUser is the currentUser
targetUser is a User, grabbed from the server, and store locally (pin)

When I create a new instance of Game, I want to add the two pointers :

    public static Game newInstance(User currentUser, User targetUser, Boolean iAmSender) {...
    Game game = new Game();
    game.setSenderUser(currentUser);
    game.setTargetUser(targetUser);
    }

Here is the setter of Target:

    public void setTargetUser(User user) {
        put("targetUser", user);
    }

**First problem**
When I want to save my game object on Parse I have this exception:
java.lang.IllegalArgumentException: Cannot save a ParseUser that is not authenticated.
Note that I have no problem with the same iOS code.

**Expected solution: let's try to create the pointer with createWithoutData to create the pointer**

    ParseObject emptyDataUser = ParseUser.createWitoutData(User.class, user.getObjectId()); //I have also tried with ParseObject/ ParseUser, ...
    game.put("targetUser", emptyDataUser);

When I save the game Object, I have the same error. 
When I check with the values of emptyDataUser with the debugger, the emptyDataUser contains all the data of the otherUser ans is the same object (@5253)

So 2 questions remains:
- how create a pointer to another user than the current user
- why createWithoutData grab the datas from the existing object

Thanks,
Matthieu

**Comment by wangmengyan95** [comment]
Hi @thieu75 , thanks for opening this issue. Could you provide the code snippet about how you get the `targetUser` and what did you do before you save the `game` object? Have you tried to modified the `targetUser` before you save the `game` object?
Thanks.

**Comment by MarsVard** [comment]
Can this please be re-opened? I am experiencing this issue on Android using version 1.10.3.

**Comment by grantland** [comment]
@MarsVard I'd recommend opening a new issue with information outlined in our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md) and with a reference to this issue commenting that it may be similar since we can't be sure if it's the same issue or not with the information you've provided thus far.

**Comment by moshea444** [comment]
I have the same issue. I am setting 2 user pointers:

ParseUser currentUser = ParseUser.getCurrentUser();

ParseObject mGame = new ParseObject("Game");
mGame .put("playerOne", currentUser);
mGame .put("playerTwo", otherUser);
mGame .put("status", "create");
mGame .put("price", mPrice);
mGame .saveInBackground();

Note above I obtain otherUser using getInBackground on a ParseUser query. It is a ParseUser object. I make sure it is not null before calling the above code.

That throws the error "java.lang.IllegalArgumentException: Cannot save a ParseUser that is not authenticated."

**Comment by Rioner123** [comment]
A little late to the party, but what is happening here is that you are using the parse local/offline storage. When you create an object using "createWithoutData", the SDK searches the offline storage to see if it can fill out the data using a local copy. Then the SDK will go through each one of the pointers and save this.

I'm not sure why the SDK is doing this, but it hindered us as well, and it would be ideal if this wasn't the case. Maybe someone with more knowledge can chime in and let us know if this is critical... if not, then I propose that it is removed

**Comment by flovilmart** [comment]
I’m usually against removing a behavior that some people may rely upon. If a particular behavior is causin issues, I suggest we fix it, or we provide a way to bypass it without affecting the other users.
